/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _GOOGLE_IRM_REG_H
#define _GOOGLE_IRM_REG_H

#define DVFS_REQ_RD_BW_AVG_GMC		0x0
#define DVFS_REQ_WR_BW_AVG_GMC		0x4
#define DVFS_REQ_RD_BW_VCDIST_GMC	0x8
#define DVFS_REQ_WR_BW_VCDIST_GMC	0xc
#define DVFS_REQ_RD_BW_PEAK_GMC		0x10
#define DVFS_REQ_WR_BW_PEAK_GMC		0x14
#define DVFS_REQ_LATENCY_GMC		0x18
#define DVFS_REQ_LTV_GMC		0x1c
#define DVFS_REQ_RD_BW_AVG_GSLC		0x20
#define DVFS_REQ_WR_BW_AVG_GSLC		0x24
#define DVFS_REQ_RD_BW_VCDIST_GSLC	0x28
#define DVFS_REQ_WR_BW_VCDIST_GSLC	0x2c
#define DVFS_REQ_RD_BW_PEAK_GSLC	0x30
#define DVFS_REQ_WR_BW_PEAK_GSLC	0x34
#define DVFS_REQ_LATENCY_GSLC		0x38
#define DVFS_REQ_LTV_GSLC		0x3c
#define DVFS_REQ_TRIG			0x40
#define SIZE_DVFS_REQ_REG		(DVFS_REQ_TRIG + 0x4)

#endif /* _GOOGLE_IRM_REG_H */
