/* SPDX-License-Identifier: GPL-2.0-only */
/**
 * Internal defines for GPCA commands.
 *
 * Copyright (C) 2022-2023 Google LLC.
 */

#ifndef _GOOGLE_GPCA_CMD_DEFINES_INTERNAL_H
#define _GOOGLE_GPCA_CMD_DEFINES_INTERNAL_H

/* Max GPCA request size in words */
#define GPCA_FIFO_MAX_WORDS (256 * 1024)

/* GPCA General Request */
#define CMD_ID_FIELD GENMASK(4, 0)

#define KEY_REQ_SIZE_FIELD GENMASK(14, 5)
#define CRYPTO_REQ_SIZE_FIELD GENMASK(10, 5)
#define CRYPTO_REQ_OPSLOT_ID_FIELD GENMASK(15, 11)

/* GPCA General Response */
#define RSP_NUM_DW 2
#define RSP_STATUS_FIELD GENMASK(23, 16)
#define RSP_ERR_FIELD0 GENMASK(31, 24)
#define RSP_ERR_FIELD1 GENMASK(31, 0)

#define KEY_RSP_SIZE_FIELD GENMASK(14, 5)
#define CRYPTO_RSP_SIZE_FIELD GENMASK(10, 5)
#define CRYPTO_RSP_OPSLOT_ID_FIELD GENMASK(15, 11)

#define BYTES_TO_WORDS(b) (((b) + sizeof(u32) - 1) / (sizeof(u32)))
#define WORDS_TO_BYTES(w) ((w) * sizeof(u32))

/* Max key size = RSA key 10240b */
#define MAX_KEY_SIZE_WORDS (10240 / 32)

/* Key Generation fields */
#define KEY_GENERATION_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define KEY_GENERATION_REQ_NUM_DW 3
#define KEY_GENERATION_REQ_KEY_POLICY_WORD_OFFSET 1

/* Key Derivation fields */
#define KEY_DERIVATION_REQ_ROOT_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define KEY_DERIVATION_REQ_DERIVED_KEYSLOT_ID_FIELD GENMASK(30, 23)
#define KEY_DERIVATION_REQ_CONTEXT_SIZE_FIELD GENMASK(2, 0)
#define KEY_DERIVATION_REQ_NUM_DW 12
#define KEY_DERIVATION_MAX_CONTEXT_SIZE_NUM_DW 8
#define KEY_DERIVATION_REQ_KEY_POLICY_WORD_OFFSET 2
#define KEY_DERIVATION_REQ_SW_CONTEXT_WORD_OFFSET 4

/* Key Wrap fields */
#define KEY_WRAP_REQ_WRAPPING_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define KEY_WRAP_REQ_KEYSLOT_ID_FIELD GENMASK(30, 23)
#define KEY_WRAP_REQ_NUM_DW 1
#define KEY_WRAP_RSP_NUM_DW \
	(RSP_NUM_DW + BYTES_TO_WORDS(MAX_WRAPPED_KEY_SIZE_BYTES))

/* Key Unwrap fields */
#define KEY_UNWRAP_REQ_WRAPPING_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define KEY_UNWRAP_REQ_KEYSLOT_ID_FIELD GENMASK(30, 23)
#define KEY_UNWRAP_REQ_MIN_NUM_DW 1
#define KEY_UNWRAP_REQ_NUM_DW \
	(KEY_UNWRAP_REQ_MIN_NUM_DW + BYTES_TO_WORDS(MAX_WRAPPED_KEY_SIZE_BYTES))
#define KEY_UNWRAP_REQ_WRAPPED_KEY_BLOB_WORD_OFFSET 1

/* Send Key fields */
#define SEND_KEY_REQ_SRC_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define SEND_KEY_REQ_DEST_KEYSLOT_ID_FIELD GENMASK(30, 23)
#define SEND_KEY_REQ_DEST_KEYTABLE_ID_FIELD GENMASK(6, 0)
#define SEND_KEY_REQ_NUM_DW 2

/* Clear Key Slot fields */
#define CLEAR_KEYSLOT_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define CLEAR_KEYSLOT_REQ_NUM_DW 1

/* Get Software Seed fields */
#define GET_SOFTWARE_SEED_REQ_KEYSLOT_FIELD GENMASK(22, 15)
#define GET_SOFTWARE_SEED_REQ_SEED_SIZE_FIELD GENMASK(25, 23)
#define GET_SOFTWARE_SEED_REQ_LABEL_SIZE_FIELD GENMASK(28, 26)
#define GET_SOFTWARE_SEED_REQ_CONTEXT_SIZE_FIELD GENMASK(31, 29)
#define GET_SOFTWARE_SEED_REQ_NUM_DW 17
#define GET_SOFTWARE_SEED_RSP_MIN_NUM_DW 2
#define GET_SOFTWARE_SEED_REQ_LABEL_WORD_OFFSET 1
#define GET_SOFTWARE_SEED_REQ_CONTEXT_WORD_OFFSET 9
#define GET_SOFTWARE_SEED_MAX_LABEL_SIZE_NUM_DW 8
#define GET_SOFTWARE_SEED_MAX_CONTEXT_SIZE_NUM_DW 8
#define GET_SOFTWARE_SEED_MAX_SEED_SIZE_NUM_DW 16

/* Key Import fields */
#define KEY_IMPORT_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define KEY_IMPORT_REQ_MIN_NUM_DW 3
#define KEY_IMPORT_REQ_NUM_DW (3 + MAX_KEY_SIZE_WORDS)
#define KEY_IMPORT_REQ_KEY_POLICY_WORD_OFFSET 1
#define KEY_IMPORT_REQ_KEY_WORD_OFFSET 3

/* Get Key policy fields */
#define GET_KEY_POLICY_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define GET_KEY_POLICY_REQ_NUM_DW 1
#define KEY_POLICY_SIZE_BYTES 8
#define GET_KEY_POLICY_RSP_NUM_DW \
	(RSP_NUM_DW + BYTES_TO_WORDS(KEY_POLICY_SIZE_BYTES))

/* Get Key metadata fields */
#define GET_KEY_METADATA_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define GET_KEY_METADATA_REQ_NUM_DW 1
#define KEY_METADATA_SIZE_BYTES 12
#define GET_KEY_METADATA_RSP_NUM_DW \
	(RSP_NUM_DW + BYTES_TO_WORDS(KEY_METADATA_SIZE_BYTES))
#define GET_KEY_METADATA_RSP_ACV_PDID_WORD 0
#define GET_KEY_METADATA_RSP_ACV_FIELD GENMASK(0, 0)
#define GET_KEY_METADATA_RSP_INPUT_PDID_FIELD GENMASK(4, 1)
#define GET_KEY_METADATA_RSP_OUTPUT_PDID_FIELD GENMASK(8, 5)
#define GET_KEY_METADATA_RSP_VALIDITY_WORD_OFFSET 1

/* Set key metadata fields */
/* Word 0 */
#define SET_KEY_METADATA_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
/* Word 1 */
#define SET_KEY_METADATA_REQ_ACV_FIELD GENMASK(0, 0)
#define SET_KEY_METADATA_REQ_INPUT_PDID_FIELD GENMASK(4, 1)
#define SET_KEY_METADATA_REQ_OUTPUT_PDID_FIELD GENMASK(8, 5)
/* Word 2 */
#define SET_KEY_METADATA_REQ_VALIDITY_WORD_OFFSET 2
#define SET_KEY_METADATA_REQ_NUM_DW 4

/* Get Public key fields */
#define GET_PUBLIC_KEY_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define GET_PUBLIC_KEY_REQ_NUM_DW 1
/* Max supported public key size = 10240b = 1280B */
#define MAX_PUBLIC_KEY_SIZE_BYTES 1280
#define GET_PUBLIC_KEY_RSP_NUM_DW \
	(RSP_NUM_DW + BYTES_TO_WORDS(MAX_PUBLIC_KEY_SIZE_BYTES))

/* Set Public key fields */
#define SET_PUBLIC_KEY_REQ_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define SET_PUBLIC_KEY_REQ_MIN_NUM_DW 1
#define SET_PUBLIC_KEY_REQ_NUM_DW        \
	(SET_PUBLIC_KEY_REQ_MIN_NUM_DW + \
	 BYTES_TO_WORDS(MAX_PUBLIC_KEY_SIZE_BYTES))
#define SET_PUBLIC_KEY_REQ_PUBLIC_KEY_WORD_OFFSET 1

/* Secure key import fields */
#define MAX_CONTEXT_SIZE_BYTES 32
#define MAX_SALT_SIZE_BYTES 16

#define SECURE_KEY_IMPORT_REQ_CLIENT_KEYSLOT_ID_FIELD GENMASK(22, 15)
#define SECURE_KEY_IMPORT_REQ_SERVER_PUBLIC_KEYSLOT_ID_FIELD GENMASK(30, 23)
/* Word 1 */
#define SECURE_KEY_IMPORT_REQ_OUTPUT_KEYSLOT_ID_FIELD GENMASK(7, 0)
#define SECURE_KEY_IMPORT_REQ_SP_FIELD GENMASK(8, 8)
#define SECURE_KEY_IMPORT_REQ_IKP_FIELD GENMASK(9, 9)
/* Word 2 */
#define SECURE_KEY_IMPORT_REQ_KEY_POLICY_WORD_OFFSET 2
/* Word 4 */
#define SECURE_KEY_IMPORT_REQ_CONTEXT_WORD_OFFSET       \
	(SECURE_KEY_IMPORT_REQ_KEY_POLICY_WORD_OFFSET + \
	 BYTES_TO_WORDS(KEY_POLICY_SIZE_BYTES))
/* Word 12 */
#define SECURE_KEY_IMPORT_REQ_SALT_WORD_OFFSET       \
	(SECURE_KEY_IMPORT_REQ_CONTEXT_WORD_OFFSET + \
	 BYTES_TO_WORDS(MAX_CONTEXT_SIZE_BYTES))
/* Word 16 */
#define SECURE_KEY_IMPORT_REQ_WRAPPED_KEY_WORD_OFFSET \
	(SECURE_KEY_IMPORT_REQ_SALT_WORD_OFFSET +     \
	 BYTES_TO_WORDS(MAX_SALT_SIZE_BYTES))

#define SECURE_KEY_IMPORT_REQ_MIN_NUM_DW \
	SECURE_KEY_IMPORT_REQ_WRAPPED_KEY_WORD_OFFSET
#define SECURE_KEY_IMPORT_REQ_NUM_DW        \
	(SECURE_KEY_IMPORT_REQ_MIN_NUM_DW + \
	 BYTES_TO_WORDS(MAX_WRAPPED_KEY_SIZE_BYTES))

/* Set Crypto Param */
/* IV sizes in bytes */
#define TDES_CBC_IV_SIZE 8
#define AES_GCM_IV_SIZE 12
#define AES_CBC_CTR_IV_SIZE 16
/* Word 0*/
#define SET_CRYPTO_PARAMS_CRYPTO_PARAMS_FIELD GENMASK(23, 16)
#define SET_CRYPTO_PARAMS_KEYSLOT_ID_FIELD GENMASK(31, 24)
/* Word 1 */
#define SET_CRYPTO_PARAMS_PURPOSE_FIELD GENMASK(3, 0)
#define SET_CRYPTO_PARAMS_IV_SIZE_FIELD GENMASK(5, 4)
/* Word 2 */
#define SET_CRYPTO_PARAMS_IV_WORD_OFFSET 2
#define SET_CRYPTO_PARAMS_MAX_IV_SIZE_WORDS 4
#define SET_CRYPTO_PARAMS_HASH_SIZE_WORDS 1
#define SET_CRYPTO_PARAMS_REQ_MIN_SIZE_WORDS 2
#define SET_CRYPTO_PARAMS_REQ_MAX_SIZE_WORDS    \
	(SET_CRYPTO_PARAMS_REQ_MIN_SIZE_WORDS + \
	 SET_CRYPTO_PARAMS_MAX_IV_SIZE_WORDS)

/* Start Crypto Op (Pointers) */
/* Word 0 */
#define START_CRYPTO_OP_PTRS_UNENCRYPTED_SIZE_FIELD GENMASK(31, 16)
/*Word 1 */
#define START_CRYPTO_OP_PTRS_AAD_SIZE_FIELD GENMASK(15, 0)
#define START_CRYPTO_OP_PTRS_SIGNATURE_SIZE_FIELD GENMASK(28, 16)
#define START_CRYPTO_OP_PTRS_LAST_FIELD GENMASK(29, 29)
#define START_CRYPTO_OP_PTRS_FWD_FIELD GENMASK(30, 30)
/* Word 2 */
#define START_CRYPTO_OP_PTRS_DATA_ADDR_LSB_FIELD GENMASK(31, 0)
/* Word 3 */
#define START_CRYPTO_OP_PTRS_DATA_ADDR_MSB_FIELD GENMASK(7, 0)
#define START_CRYPTO_OP_PTRS_INPUT_DATA_SIZE_FIELD GENMASK(31, 8)
/* Word 4 */
#define START_CRYPTO_OP_PTRS_OUTPUT_DATA_ADDR_LSB_FIELD GENMASK(31, 0)
/* Word 5 */
#define START_CRYPTO_OP_PTRS_OUTPUT_DATA_ADDR_MSB_FIELD GENMASK(7, 0)
#define START_CRYPTO_OP_PTRS_OUTPUT_DATA_SIZE_FIELD GENMASK(31, 8)

#define START_CRYPTO_OP_PTRS_REQ_SIZE_WORDS 6
#define START_CRYPTO_OP_PTRS_MAX_UNENCRYPTED_SIZE_BYTES (64 * 1024 - 1)
#define START_CRYPTO_OP_PTRS_MAX_AAD_SIZE_BYTES (64 * 1024 - 1)
#define START_CRYPTO_OP_PTRS_MAX_SIGNATURE_SIZE_BYTES (8 * 1024 - 1)
/* As per spec it should be 16MB -1 but in A0 8MB -1 due to b/257074744 */
#define START_CRYPTO_OP_PTRS_MAX_INPUT_SIZE_BYTES (8 * 1024 * 1024 - 1)

/* Start Crypto Op (Data) */
#define START_CRYPTO_OP_DATA_AAD_SIZE_FIELD GENMASK(21, 16)
#define START_CRYPTO_OP_DATA_INPUT_SIZE_FIELD GENMASK(26, 22)
#define START_CRYPTO_OP_DATA_LAST_FIELD GENMASK(27, 27)
#define START_CRYPTO_OP_DATA_AAD_WORD_OFFSET 1
#define START_CRYPTO_OP_DATA_MAX_AAD_SIZE_BYTES 32
/* Ideally it should be 32 bytes b/245150690 */
#define START_CRYPTO_OP_DATA_MAX_INPUT_SIZE_BYTES 31
#define START_CRYPTO_OP_DATA_REQ_MAX_SIZE_WORDS                    \
	(START_CRYPTO_OP_DATA_AAD_WORD_OFFSET +                    \
	 BYTES_TO_WORDS(START_CRYPTO_OP_DATA_MAX_AAD_SIZE_BYTES) + \
	 BYTES_TO_WORDS(START_CRYPTO_OP_DATA_MAX_INPUT_SIZE_BYTES))

#define START_CRYPTO_OP_DATA_MAX_RSP_SIZE_WORDS 18

/* Get/Set Operation context */
/* Word 0 */
#define GET_SET_OP_CTX_GET_OR_SET_FIELD GENMASK(16, 16)
/* Word 1 */
#define GET_SET_OP_CTX_CONTEXT_ADDR_LSB_FIELD GENMASK(31, 0)
/* Word 2 */
#define GET_SET_OP_CTX_CONTEXT_ADDR_MSB_FIELD GENMASK(7, 0)
#define GET_SET_OP_CTX_CONTEXT_SIZE_FIELD GENMASK(23, 8)

#define GET_SET_OP_CTX_REQ_SIZE_WORDS 3
#define GET_SET_OP_CTX_MAX_SIZE_BYTES (64 * 1024)

/* Clear Operation slot */
#define CLEAR_OPSLOT_REQ_SIZE_WORDS 1

/* Response status */
#define RSP_STATUS_OK 0x55
#define RSP_STATUS_ERROR 0xAA

/* GPCA Command IDs */
enum gpca_cmd_id {
	GPCA_CMD_SET_CRYPTO_PARAMS = 0,
	GPCA_CMD_START_CRYPTO_OP_PTRS,
	GPCA_CMD_START_CRYPTO_OP_DATA,
	GPCA_CMD_GET_SET_CONTEXT,
	GPCA_CMD_CLEAR_OPSLOT,
	GPCA_CMD_KEY_GENERATION,
	GPCA_CMD_KEY_DERIVATION,
	GPCA_CMD_KEY_IMPORT,
	GPCA_CMD_SECURE_KEY_IMPORT,
	GPCA_CMD_KEY_WRAP,
	GPCA_CMD_KEY_UNWRAP,
	GPCA_CMD_SET_PUBLIC_KEY,
	GPCA_CMD_GET_PUBLIC_KEY,
	GPCA_CMD_SET_KEY_METADATA,
	GPCA_CMD_CLEAR_KEY_SLOT,
	GPCA_CMD_SEND_KEY,
	GPCA_CMD_GET_SOFTWARE_SEED,
	GPCA_CMD_GET_KEY_POLICY,
	GPCA_CMD_GET_KEY_METADATA
};

/* GPCA error codes */
enum gpca_cmd_error_code {
	GPCA_CMD_NO_ERROR = 0x0,
	GPCA_CMD_CRYPTO_ERROR = BIT(0),
	GPCA_CMD_DATA_READ_WRITE_ERROR = BIT(1),
	GPCA_CMD_GENERIC_ERROR = BIT(2),
	GPCA_CMD_INVALID_AAD = BIT(3),
	GPCA_CMD_INVALID_CLIENT_KEYSLOT = BIT(4),
	GPCA_CMD_INVALID_CONTEXT_SIZE = BIT(5),
	GPCA_CMD_INVALID_CRYPTO_CLASS = BIT(6),
	GPCA_CMD_INVALID_CRYPTO_PARAMS = BIT(7),
	GPCA_CMD_INVALID_DERIVED_KEYSLOT = BIT(8),
	GPCA_CMD_INVALID_DEST_KEYSLOT_ID = BIT(9),
	GPCA_CMD_INVALID_INPUT_PDID = BIT(10),
	GPCA_CMD_INVALID_INPUT_SIZE = BIT(11),
	GPCA_CMD_INVALID_IV = BIT(12),
	GPCA_CMD_INVALID_KDK = BIT(13),
	GPCA_CMD_INVALID_KEK = BIT(14),
	GPCA_CMD_INVALID_KEY = BIT(15),
	GPCA_CMD_INVALID_KEY_CLASS = BIT(16),
	GPCA_CMD_INVALID_KEY_OWNER_DOMAIN = BIT(17),
	GPCA_CMD_INVALID_KEYSLOT = BIT(18),
	GPCA_CMD_INVALID_KWK = BIT(19),
	GPCA_CMD_INVALID_OPERATION_SLOT = BIT(20),
	GPCA_CMD_INVALID_OUTPUT_KEYSLOT = BIT(21),
	GPCA_CMD_INVALID_OUTPUT_SIZE = BIT(22),
	GPCA_CMD_INVALID_PDID = BIT(23),
	GPCA_CMD_INVALID_REQUEST = BIT(24),
	GPCA_CMD_INVALID_ROOT_KEYSLOT = BIT(25),
	GPCA_CMD_INVALID_SERVER_PUBKEY_KEYSLOT = BIT(26),
	GPCA_CMD_INVALID_SIGNATURE_SIZE = BIT(27),
	GPCA_CMD_INVALID_SUPPORTED_PURPOSES = BIT(28),
	GPCA_CMD_INVALID_WRAPPING_CONSTRAINT = BIT(29),
	GPCA_CMD_KEY_POLICY_CHECK_FAILED = BIT(30),
	GPCA_CMD_KEYSLOT_EMPTY = BIT(31),
	GPCA_CMD_KEYSLOT_NOT_EMPTY = BIT(32),
	GPCA_CMD_UNAUTHORIZED_KEY_REQUEST = BIT(33),
	GPCA_CMD_UNSUPPORTED_CRYPTO_CLASS = BIT(34),
	GPCA_CMD_UNSUPPORTED_CRYPTO_PARAMS = BIT(35),
};

/**
 * enum  gpca_cmd_iv_type - IV type.
 *
 * @GPCA_CMD_NO_IV: No IV for ECB mode.
 * @GPCA_CMD_12B_IV: 12 bytes IV for GCM mode.
 * @GPCA_CMD_16B_IV: 16 bytes IV for CTR/CBC mode.
 * @GPCA_CMD_8B_IV: 8 bytes IV for TDES CBC.
 */
enum gpca_cmd_iv_type {
	GPCA_CMD_NO_IV = 0,
	GPCA_CMD_12B_IV,
	GPCA_CMD_16B_IV,
	GPCA_CMD_8B_IV
};

#endif /* _GOOGLE_GPCA_CMD_DEFINES_INTERNAL_H */
