/* SPDX-License-Identifier: GPL-2.0-only or BSD-2-Clause */

#ifndef __DT_BINDINGS_LPCM_CLOCK_H
#define __DT_BINDINGS_LPCM_CLOCK_H

/*
 * define LPCM's clock ID of different SSWRPs, should match values defined in
 * cpm/google/dev/lpcm/include/dev/lpcm/rdo/lcm_plat.h.
 * TODO(b/283348013): create shared C header files and replace the include path
 */
#define LSIOS_GPIO_CLK 0
#define LSIOS_MCLK0_CLK 1
#define LSIOS_PWM_CLK 2
#define LSIOS_PWM_CFG_CLK 3
#define LSIOS_CLI0_CFG_CLK 4
#define LSIOS_CLI1_CFG_CLK 5
#define LSIOS_CLI2_CFG_CLK 6
#define LSIOS_CLI3_CFG_CLK 7
#define LSIOS_CLI4_CFG_CLK 8
#define LSIOS_CLI5_CFG_CLK 9
#define LSIOS_CLI6_CFG_CLK 10
#define LSIOS_CLI0_SPI_CLK 11
#define LSIOS_CLI1_SPI_CLK 12
#define LSIOS_CLI2_SPI_CLK 13
#define LSIOS_CLI3_SPI_CLK 14
#define LSIOS_CLI4_SPI_CLK 15
#define LSIOS_CLI5_SPI_CLK 16
#define LSIOS_CLI6_SPI_CLK 17
#define LSIOS_CLI0_I2C_CLK 18
#define LSIOS_CLI1_I2C_CLK 19
#define LSIOS_CLI2_I2C_CLK 20
#define LSIOS_CLI3_I2C_CLK 21
#define LSIOS_CLI4_I2C_CLK 22
#define LSIOS_CLI5_I2C_CLK 23
#define LSIOS_CLI6_I2C_CLK 24
#define LSIOS_CLI0_UART_CLK 25
#define LSIOS_CLI1_UART_CLK 26
#define LSIOS_CLI2_UART_CLK 27
#define LSIOS_CLI3_UART_CLK 28
#define LSIOS_CLI4_UART_CLK 29
#define LSIOS_CLI5_UART_CLK 30
#define LSIOS_CLI6_UART_CLK 31
#define LSIOS_CLI0_I3C_CLK 32
#define LSIOS_CLI1_I3C_CLK 33
#define LSIOS_CLI2_I3C_CLK 34
#define LSIOS_CLI3_I3C_CLK 35
#define LSIOS_CLI4_I3C_CLK 36
#define LSIOS_CLI5_I3C_CLK 37
#define LSIOS_CLI6_I3C_CLK 38
#define LSIOS_MCLK1_CLK 39
#define LSIOS_MCLK2_CLK 40
#define LSIOS_MCLK3_CLK 41
#define LSIOS_MCLK4_CLK 42
#define LSIOS_MCLK5_CLK 43
#define LSIOS_MCLK6_CLK 44
#define LSIOS_MCLK7_CLK 45

#define LSION_GPIO_CLK 0
#define LSION_CLI_INT0_I2C_CLK 1
#define LSION_CLI_INT0_I3C_CLK 2
#define LSION_CLI_INT0_UART_CLK 3
#define LSION_CLI_INT0_SPI_CLK 4
#define LSION_CLI_INT0_CFG_CLK 5
#define LSION_CLI_INT1_I2C_CLK 6
#define LSION_CLI_INT1_I3C_CLK 7
#define LSION_CLI_INT1_UART_CLK 8
#define LSION_CLI_INT1_SPI_CLK 9
#define LSION_CLI_INT1_CFG_CLK 10
#define LSION_CLI_INT2_I2C_CLK 11
#define LSION_CLI_INT2_I3C_CLK 12
#define LSION_CLI_INT2_UART_CLK 13
#define LSION_CLI_INT2_SPI_CLK 14
#define LSION_CLI_INT2_CFG_CLK 15
#define LSION_CLI_INT3_I2C_CLK 16
#define LSION_CLI_INT3_I3C_CLK 17
#define LSION_CLI_INT3_UART_CLK 18
#define LSION_CLI_INT3_SPI_CLK 19
#define LSION_CLI_INT3_CFG_CLK 20
#define LSION_CLI_INT4_I2C_CLK 21
#define LSION_CLI_INT4_I3C_CLK 22
#define LSION_CLI_INT4_UART_CLK 23
#define LSION_CLI_INT4_SPI_CLK 24
#define LSION_CLI_INT4_CFG_CLK 25
#define LSION_CLI15_CFG_CLK 26
#define LSION_CLI16_CFG_CLK 27
#define LSION_CLI15_I2C_CLK 28
#define LSION_CLI16_I2C_CLK 29
#define LSION_CLI15_SPI_CLK 30
#define LSION_CLI16_SPI_CLK 31
#define LSION_CLI15_UART_CLK 32
#define LSION_CLI16_UART_CLK 33
#define LSION_CLI15_I3C_CLK 34
#define LSION_CLI16_I3C_CLK 35

#define LSIOE_GPIO_CLK 0
#define LSIOE_CLI7_CFG_CLK 1
#define LSIOE_CLI8_CFG_CLK 2
#define LSIOE_CLI9_CFG_CLK 3
#define LSIOE_CLI10_CFG_CLK 4
#define LSIOE_CLI11_CFG_CLK 5
#define LSIOE_CLI12_CFG_CLK 6
#define LSIOE_CLI13_CFG_CLK 7
#define LSIOE_CLI14_CFG_CLK 8
#define LSIOE_CLI7_SPI_CLK 9
#define LSIOE_CLI8_SPI_CLK 10
#define LSIOE_CLI9_SPI_CLK 11
#define LSIOE_CLI10_SPI_CLK 12
#define LSIOE_CLI11_SPI_CLK 13
#define LSIOE_CLI12_SPI_CLK 14
#define LSIOE_CLI13_SPI_CLK 15
#define LSIOE_CLI14_SPI_CLK 16
#define LSIOE_CLI7_I2C_CLK 17
#define LSIOE_CLI8_I2C_CLK 18
#define LSIOE_CLI9_I2C_CLK 19
#define LSIOE_CLI10_I2C_CLK 20
#define LSIOE_CLI11_I2C_CLK 21
#define LSIOE_CLI12_I2C_CLK 22
#define LSIOE_CLI13_I2C_CLK 23
#define LSIOE_CLI14_I2C_CLK 24
#define LSIOE_CLI7_UART_CLK 25
#define LSIOE_CLI8_UART_CLK 26
#define LSIOE_CLI9_UART_CLK 27
#define LSIOE_CLI10_UART_CLK 28
#define LSIOE_CLI11_UART_CLK 29
#define LSIOE_CLI12_UART_CLK 30
#define LSIOE_CLI13_UART_CLK 31
#define LSIOE_CLI14_UART_CLK 32
#define LSIOE_SPMI_CLK 33
#define LSIOE_CLI7_I3C_CLK  34
#define LSIOE_CLI8_I3C_CLK  35
#define LSIOE_CLI9_I3C_CLK  36
#define LSIOE_CLI10_I3C_CLK  37
#define LSIOE_CLI11_I3C_CLK  38
#define LSIOE_CLI12_I3C_CLK  39
#define LSIOE_CLI13_I3C_CLK  40
#define LSIOE_CLI14_I3C_CLK  41

#define HSIOS_MPHY_REF_OSC_CLK 0
#define HSIOS_MPHY_REF_TCX0_CLK 1
#define HSIOS_GPIO_REF_OSC_CLK 2
#define HSIOS_GPIO_REF_TCX0_CLK 3
#define HSIOS_HCLK_CLK 4
#define HSIOS_SYS_CLK 5
#define HSIOS_T_CLK 6
#define HSIOS_LP_T_CLK 7
#define HSIOS_MPHY_CFG_CLK 8
#define HSIOS_UFS_CFG_CLK 9
#define HSIOS_PHY_FW_CLK 10
#define HSIOS_PCIE_REF_CLK 11
#define HSIOS_UFS_RESET_CLK 12
#define HSIOS_UFS_LP_RESET_CLK 13
#define HSIOS_UFS_ARESET_CLK 14
#define HSIOS_UFS_PHY_RESET_CLK 15
#define HSIOS_AUX_CLK 16

#define HSION_USB_CLK 0
#define HSION_DP0_CLK 1
#define HSION_DP1_CLK 2
#define HSION_PHY_FW_CLK 3
#define HSION_PCIE_REF_CLK 4
#define HSION_U2PHY_REF_CLK 5
#define HSION_USBDP_SUSPEND_CLK 6
#define HSION_USBC_NON_STICKY_CLK 7
#define HSION_USBC_STICKY_CLK 8
#define HSION_USB_DRD_BUS_CLK 9
#define HSION_CSR_CLK 10
#define HSION_USB_TOP_CSR_CLK 11
#define HSION_DP_PCLK_CLK 12
#define HSION_DP_CFG_CLK 13
#define HSION_U2PHY_APB_CLK 14
#define HSION_DP_VCC_CLK 15
#define HSION_U3PHY_REF_CLK 16
#define HSION_USB2_PHY_RESET_CLK 17
#define HSION_USB3DP_PHY_RESET_CLK 18
#define HSION_EBU_CLK 19

#define DPU_DP0_PIX_CLK 0
#define DPU_DP1_PIX_CLK 1
#define DPU_DSI0_PIX_CLK 2
#define DPU_DSI1_PIX_CLK 3
#define DPU_DSI1_PHY_CLK 4
#define DPU_FE0_CLK 5
#define DPU_FE1_CLK 6
#define DPU_BE_CLK 7
#define DPU_AON_CLK 8

#define GPCM_DPU_PLL_DP_CLK 0
#define GPCM_HSION_PLL_DP_CLK 1

#define CPU_SSWRP_TSS_CLK 1

#endif /* __DT_BINDINGS_LPCM_CLOCK_H */
