/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO BE_MSA Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_BE_MSA_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_BE_MSA_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define BE_MSA_RSTCTL_IRQ_BASE (HW_EVENT_MASK + 0)

#define BE_MSA_RSTCTL_IRQ_SW_RESET_DONE 0
#define BE_MSA_RSTCTL_IRQ_INPUT_FLUSH_DONE 1
#define BE_MSA_RSTCTL_IRQ_SW_MODE 2
#define BE_MSA_RSTCTL_IRQ_APB_GKP_ERR 3
#define BE_MSA_RSTCTL_IRQ_AXI_GKP_ERR 4

#define BE_MSA_FRAMECTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 32)

#define BE_MSA_FRAMECTL_NS_AP_IRQ_CURR_RDMA_AXI_ERR 0
#define BE_MSA_FRAMECTL_NS_AP_IRQ_PREV_RDMA_AXI_ERR 1
#define BE_MSA_FRAMECTL_NS_AP_IRQ_LMV_WDMA_AXI_ERR 2
#define BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_BATCH 3
#define BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_BATCH 4
#define BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_FRAME 5
#define BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_FRAME 6
#define BE_MSA_FRAMECTL_NS_AP_IRQ_A2S_COPY_DONE 7
#define BE_MSA_FRAMECTL_NS_AP_IRQ_S2A_COPY_DONE 8
#define BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY 9
#define BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY 10
#define BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY 11
#define BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY 12
#define BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE 13

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_BE_MSA_RSTCTL_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_MSA_RSTCTL_IRQ_BASE, \
		 BE_MSA_RSTCTL_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_RSTCTL_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_MSA_RSTCTL_IRQ_BASE, \
		 BE_MSA_RSTCTL_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_RSTCTL_IRQ_SW_MODE \
	EVENT_ID(BE_MSA_RSTCTL_IRQ_BASE, \
		 BE_MSA_RSTCTL_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_RSTCTL_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_MSA_RSTCTL_IRQ_BASE, \
		 BE_MSA_RSTCTL_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_RSTCTL_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_MSA_RSTCTL_IRQ_BASE, \
		 BE_MSA_RSTCTL_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_CURR_RDMA_AXI_ERR \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_CURR_RDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_PREV_RDMA_AXI_ERR \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_PREV_RDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_LMV_WDMA_AXI_ERR \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_LMV_WDMA_AXI_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_BATCH \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_BATCH \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_BATCH)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_FRAME \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_START_OF_FRAME)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_FRAME \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_END_OF_FRAME)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_A2S_COPY_DONE \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_A2S_COPY_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_S2A_COPY_DONE \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_S2A_COPY_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY)
#define LWIS_PLATFORM_EVENT_ID_BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE \
	EVENT_ID(BE_MSA_FRAMECTL_NS_AP_IRQ_BASE, \
		 BE_MSA_FRAMECTL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE)

#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_BE_MSA_H_ */
