/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO BE_PDMA Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_BE_PDMA_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_BE_PDMA_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 0)

#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE 0
#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE 1
#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE 2
#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR 3
#define BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR 4

#define BE_PDMA_ISPBE_INST0_PDMA_NS_AP_BASE (HW_EVENT_MASK + 32)

#define BE_PDMA_ISPBE_INST0_PDMA_NS_AP_IRQ_CMD 0
#define BE_PDMA_ISPBE_INST0_PDMA_NS_AP_ALMOST_EMPTY 1

#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 64)

#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE 0
#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE 1
#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE 2
#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR 3
#define BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR 4

#define BE_PDMA_ISPBE_INST1_PDMA_NS_AP_BASE (HW_EVENT_MASK + 96)

#define BE_PDMA_ISPBE_INST1_PDMA_NS_AP_IRQ_CMD 0
#define BE_PDMA_ISPBE_INST1_PDMA_NS_AP_ALMOST_EMPTY 1

#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 128)

#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE 0
#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE 1
#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE 2
#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR 3
#define BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR 4

#define BE_PDMA_ISPBE_INST2_PDMA_NS_AP_BASE (HW_EVENT_MASK + 160)

#define BE_PDMA_ISPBE_INST2_PDMA_NS_AP_IRQ_CMD 0
#define BE_PDMA_ISPBE_INST2_PDMA_NS_AP_ALMOST_EMPTY 1

#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 192)

#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE 0
#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE 1
#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE 2
#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR 3
#define BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR 4

#define BE_PDMA_GSW_INST0_PDMA_NS_AP_BASE (HW_EVENT_MASK + 224)

#define BE_PDMA_GSW_INST0_PDMA_NS_AP_IRQ_CMD 0
#define BE_PDMA_GSW_INST0_PDMA_NS_AP_ALMOST_EMPTY 1

#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 256)

#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE 0
#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE 1
#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE 2
#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR 3
#define BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR 4

#define BE_PDMA_GSW_INST1_PDMA_NS_AP_BASE (HW_EVENT_MASK + 288)

#define BE_PDMA_GSW_INST1_PDMA_NS_AP_IRQ_CMD 0
#define BE_PDMA_GSW_INST1_PDMA_NS_AP_ALMOST_EMPTY 1

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                       \
		 BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                          \
		 BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                 \
		 BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_NS_AP_IRQ_CMD \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_NS_AP_BASE,                 \
		 BE_PDMA_ISPBE_INST0_PDMA_NS_AP_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST0_PDMA_NS_AP_ALMOST_EMPTY \
	EVENT_ID(BE_PDMA_ISPBE_INST0_PDMA_NS_AP_BASE,                      \
		 BE_PDMA_ISPBE_INST0_PDMA_NS_AP_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                       \
		 BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                          \
		 BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                 \
		 BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_NS_AP_IRQ_CMD \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_NS_AP_BASE,                 \
		 BE_PDMA_ISPBE_INST1_PDMA_NS_AP_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST1_PDMA_NS_AP_ALMOST_EMPTY \
	EVENT_ID(BE_PDMA_ISPBE_INST1_PDMA_NS_AP_BASE,                      \
		 BE_PDMA_ISPBE_INST1_PDMA_NS_AP_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE,                       \
		 BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE,                          \
		 BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE,                 \
		 BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_ISPBE_INST2_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_NS_AP_IRQ_CMD \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_NS_AP_BASE,                 \
		 BE_PDMA_ISPBE_INST2_PDMA_NS_AP_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_ISPBE_INST2_PDMA_NS_AP_ALMOST_EMPTY \
	EVENT_ID(BE_PDMA_ISPBE_INST2_PDMA_NS_AP_BASE,                      \
		 BE_PDMA_ISPBE_INST2_PDMA_NS_AP_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                       \
		 BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                          \
		 BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                 \
		 BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_GSW_INST0_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_NS_AP_IRQ_CMD \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_NS_AP_BASE,                 \
		 BE_PDMA_GSW_INST0_PDMA_NS_AP_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST0_PDMA_NS_AP_ALMOST_EMPTY \
	EVENT_ID(BE_PDMA_GSW_INST0_PDMA_NS_AP_BASE,                      \
		 BE_PDMA_GSW_INST0_PDMA_NS_AP_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                       \
		 BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                          \
		 BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                 \
		 BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_BASE,                     \
		 BE_PDMA_GSW_INST1_PDMA_RSTCTL_NS_AP_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_NS_AP_IRQ_CMD \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_NS_AP_BASE,                 \
		 BE_PDMA_GSW_INST1_PDMA_NS_AP_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_BE_PDMA_GSW_INST1_PDMA_NS_AP_ALMOST_EMPTY \
	EVENT_ID(BE_PDMA_GSW_INST1_PDMA_NS_AP_BASE,                      \
		 BE_PDMA_GSW_INST1_PDMA_NS_AP_ALMOST_EMPTY)

#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_BE_PDMA_H_ */
