/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO GSE Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_GSE_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_GSE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define GSE_RSTCTL_IRQ_BASE (HW_EVENT_MASK + 0)

#define GSE_RSTCTL_IRQ_SW_RESET_DONE 0
#define GSE_RSTCTL_IRQ_INPUT_FLUSH_DONE 1
#define GSE_RSTCTL_IRQ_SW_MODE 2
#define GSE_RSTCTL_IRQ_APB_GKP_ERR 3
#define GSE_RSTCTL_IRQ_AXI_GKP_ERR 4

#define GSE_FRAMECTRL_NS_AP_IRQ_BASE (HW_EVENT_MASK + 32)

#define GSE_FRAMECTRL_NS_AP_IRQ_RDMA_AXI_ERR_IRQ 0
#define GSE_FRAMECTRL_NS_AP_IRQ_RDMA_FBC_ERR_IRQ 1
#define GSE_FRAMECTRL_NS_AP_IRQ_COEF_RDMA_AXI_ERR_IRQ 2
#define GSE_FRAMECTRL_NS_AP_IRQ_WDMA0_AXI_ERR_IRQ 3
#define GSE_FRAMECTRL_NS_AP_IRQ_WDMA1_AXI_ERR_IRQ 4
#define GSE_FRAMECTRL_NS_AP_IRQ_START_OF_BATCH_IRQ 5
#define GSE_FRAMECTRL_NS_AP_IRQ_END_OF_BATCH_IRQ 6
#define GSE_FRAMECTRL_NS_AP_IRQ_START_OF_FRAME_IRQ 7
#define GSE_FRAMECTRL_NS_AP_IRQ_END_OF_FRAME_IRQ 8
#define GSE_FRAMECTRL_NS_AP_IRQ_CSR_A2S_COPY_DONE_IRQ 9
#define GSE_FRAMECTRL_NS_AP_IRQ_CSR_S2A_COPY_DONE_IRQ 10
#define GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY_IRQ 11
#define GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY_IRQ 12
#define GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY_IRQ 13
#define GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY_IRQ 14
#define GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE_IRQ 15

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_GSE_RSTCTL_IRQ_SW_RESET_DONE \
	EVENT_ID(GSE_RSTCTL_IRQ_BASE, GSE_RSTCTL_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_RSTCTL_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(GSE_RSTCTL_IRQ_BASE, GSE_RSTCTL_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_RSTCTL_IRQ_SW_MODE \
	EVENT_ID(GSE_RSTCTL_IRQ_BASE, GSE_RSTCTL_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_GSE_RSTCTL_IRQ_APB_GKP_ERR \
	EVENT_ID(GSE_RSTCTL_IRQ_BASE, GSE_RSTCTL_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_RSTCTL_IRQ_AXI_GKP_ERR \
	EVENT_ID(GSE_RSTCTL_IRQ_BASE, GSE_RSTCTL_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_RDMA_AXI_ERR_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_RDMA_AXI_ERR_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_RDMA_FBC_ERR_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_RDMA_FBC_ERR_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_COEF_RDMA_AXI_ERR_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                               \
		 GSE_FRAMECTRL_NS_AP_IRQ_COEF_RDMA_AXI_ERR_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_WDMA0_AXI_ERR_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                           \
		 GSE_FRAMECTRL_NS_AP_IRQ_WDMA0_AXI_ERR_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_WDMA1_AXI_ERR_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                           \
		 GSE_FRAMECTRL_NS_AP_IRQ_WDMA1_AXI_ERR_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_START_OF_BATCH_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                            \
		 GSE_FRAMECTRL_NS_AP_IRQ_START_OF_BATCH_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_END_OF_BATCH_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_END_OF_BATCH_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_START_OF_FRAME_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                            \
		 GSE_FRAMECTRL_NS_AP_IRQ_START_OF_FRAME_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_END_OF_FRAME_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_END_OF_FRAME_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_CSR_A2S_COPY_DONE_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                               \
		 GSE_FRAMECTRL_NS_AP_IRQ_CSR_A2S_COPY_DONE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_CSR_S2A_COPY_DONE_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                               \
		 GSE_FRAMECTRL_NS_AP_IRQ_CSR_S2A_COPY_DONE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                                        \
		 GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_A2S_COPY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                                        \
		 GSE_FRAMECTRL_NS_AP_IRQ_PRIMARY_APB_WR_IN_S2A_COPY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_A2S_COPY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                                          \
		 GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_S2A_COPY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE_IRQ \
	EVENT_ID(GSE_FRAMECTRL_NS_AP_IRQ_BASE,                                            \
		 GSE_FRAMECTRL_NS_AP_IRQ_SECONDARY_APB_WR_IN_MASK_CYCLE_IRQ)

#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_GSE_H_ */
