/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO GWE Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_GWE_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_GWE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define GWE_RSTCTL_IRQ_BASE (HW_EVENT_MASK + 0)

#define GWE_RSTCTL_IRQ_SW_RESET_DONE 0
#define GWE_RSTCTL_IRQ_INPUT_FLUSH_DONE 1
#define GWE_RSTCTL_IRQ_SW_MODE 2
#define GWE_RSTCTL_IRQ_APB_GKP_ERR 3
#define GWE_RSTCTL_IRQ_AXI_GKP_ERR 4

#define GWE_CORE_GTL_IRQ_BASE (HW_EVENT_MASK + 32)

#define GWE_CORE_GTL_IRQ_BATCH_END_I_R_Q 0
#define GWE_CORE_GTL_IRQ_BATCH_START_I_R_Q 1
#define GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_ENC_IRQ 2
#define GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_DEC_IRQ 3
#define GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_ENC_IRQ 4
#define GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_DEC_IRQ 5
#define GWE_CORE_GTL_IRQ_REG_FE_DW200_VAL_INTERVENE_IRQ 6
#define GWE_CORE_GTL_IRQ_AHB_VAL_WR_INTERVENE_IRQ 7
#define GWE_CORE_GTL_IRQ_FE_INTR_PERF_END_E_IRQ 8
#define GWE_CORE_GTL_IRQ_CORE1_BIG_BLOCK_FLAG_IRQ 9
#define GWE_CORE_GTL_IRQ_CORE0_BIG_BLOCK_FLAG_IRQ 10
#define GWE_CORE_GTL_IRQ_CORE1_ERR_START_EARLY_IRQ 11
#define GWE_CORE_GTL_IRQ_CORE0_ERR_START_EARLY_IRQ 12
#define GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_LINE_IRQ 13
#define GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_BLOCK_IRQ 14
#define GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_LINE_IRQ 15
#define GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_BLOCK_IRQ 16
#define GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT0_IRQ 17
#define GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT1_IRQ 18
#define GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT0_IRQ 19
#define GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT1_IRQ 20
#define GWE_CORE_GTL_IRQ_FRAME_END_IRQ 21
#define GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_END_IRQ 22
#define GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_END_IRQ 23
#define GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_START_IRQ 24
#define GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_START_IRQ 25
#define GWE_CORE_GTL_IRQ_FRAME_START_IRQ 26
#define GWE_CORE_GTL_IRQ_FE_STALL_WAIT_E_IRQ 27
#define GWE_CORE_GTL_IRQ_FE_FRAME_CFG_CMPL_E_IRQ 28

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_GWE_RSTCTL_IRQ_SW_RESET_DONE \
	EVENT_ID(GWE_RSTCTL_IRQ_BASE, \
		 GWE_RSTCTL_IRQ_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_GWE_RSTCTL_IRQ_INPUT_FLUSH_DONE \
	EVENT_ID(GWE_RSTCTL_IRQ_BASE, \
		 GWE_RSTCTL_IRQ_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_GWE_RSTCTL_IRQ_SW_MODE \
	EVENT_ID(GWE_RSTCTL_IRQ_BASE, \
		 GWE_RSTCTL_IRQ_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_GWE_RSTCTL_IRQ_APB_GKP_ERR \
	EVENT_ID(GWE_RSTCTL_IRQ_BASE, \
		 GWE_RSTCTL_IRQ_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_GWE_RSTCTL_IRQ_AXI_GKP_ERR \
	EVENT_ID(GWE_RSTCTL_IRQ_BASE, \
		 GWE_RSTCTL_IRQ_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_BATCH_END_I_R_Q \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_BATCH_END_I_R_Q)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_BATCH_START_I_R_Q \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_BATCH_START_I_R_Q)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_ENC_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_ENC_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_DEC_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_PVRIC_CORE_ERR_DEC_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_ENC_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_ENC_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_DEC_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_PVRIC_CORE_ERR_DEC_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_REG_FE_DW200_VAL_INTERVENE_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_REG_FE_DW200_VAL_INTERVENE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_AHB_VAL_WR_INTERVENE_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_AHB_VAL_WR_INTERVENE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_FE_INTR_PERF_END_E_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_FE_INTR_PERF_END_E_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_BIG_BLOCK_FLAG_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_BIG_BLOCK_FLAG_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_BIG_BLOCK_FLAG_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_BIG_BLOCK_FLAG_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_ERR_START_EARLY_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_ERR_START_EARLY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_ERR_START_EARLY_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_ERR_START_EARLY_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_LINE_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_LINE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_BLOCK_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_BUS_ERR_BLOCK_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_LINE_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_LINE_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_BLOCK_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_BUS_ERR_BLOCK_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT0_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT0_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT1_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_BUS_TIME_OUT1_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT0_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT0_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT1_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_BUS_TIME_OUT1_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_FRAME_END_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_FRAME_END_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_END_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_END_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_END_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_END_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_START_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE1_DP_FRAME_START_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_START_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_CORE0_DP_FRAME_START_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_FRAME_START_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_FRAME_START_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_FE_STALL_WAIT_E_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_FE_STALL_WAIT_E_IRQ)
#define LWIS_PLATFORM_EVENT_ID_GWE_CORE_GTL_IRQ_FE_FRAME_CFG_CMPL_E_IRQ \
	EVENT_ID(GWE_CORE_GTL_IRQ_BASE, \
		 GWE_CORE_GTL_IRQ_FE_FRAME_CFG_CMPL_E_IRQ)
#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_GWE_H_ */
