/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO SSWRP_ISPBE Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_ISPBE_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_ISPBE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_BASE (HW_EVENT_MASK + 4000)

#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_FRAMECTL 29
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_RSTCTL 30
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_YUV_FRAMECTL 31

#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE (HW_EVENT_MASK + 4032)

#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_YUV_RSTCTL 0
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_FRAMECTL 1
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_RSTCTL 2
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA0 3
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA1 4
#define SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA2 5

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_FRAMECTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_FRAMECTL)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_RSTCTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_MSA_RSTCTL)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_YUV_FRAMECTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_2_YUV_FRAMECTL)

#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_YUV_RSTCTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_YUV_RSTCTL)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_FRAMECTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_FRAMECTL)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_RSTCTL \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BTR_RSTCTL)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA0 \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA0)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA1 \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA1)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA2 \
	EVENT_ID(SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_BASE, \
		 SSWRP_ISPBE_NAC_NS_AP_GTL_IRQ_3_PDMA2)

#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_ISPBE_H_ */
