/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Google LWIS RDO SSWRP_GSW Interrupt And Event Defines
 *
 * Copyright (c) 2023 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_GSW_H_
#define DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_GSW_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define SSWRP_GSW_PG_ON_NAC_IRQ_BASE (HW_EVENT_MASK + 0)

#define SSWRP_GSW_PG_ON_NAC_IRQ_XBA0_ERR_IRQ 0
#define SSWRP_GSW_PG_ON_NAC_IRQ_XBA0_ERR_IRQ_OFFSET 4000
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ0 1
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ0_OFFSET 4001
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ1 2
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ1_OFFSET 4002
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ2 3
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ2_OFFSET 4003
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ3 4
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ3_OFFSET 4004
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ4 5
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ4_OFFSET 4005
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ5 6
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ5_OFFSET 4006
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ6 7
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ6_OFFSET 4007
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ7 8
#define SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ7_OFFSET 4008
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ0 9
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ0_OFFSET 4009
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ1 10
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ1_OFFSET 4010
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ0 11
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ0_OFFSET 4011
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ1 12
#define SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ1_OFFSET 4012
#define SSWRP_GSW_PG_ON_NAC_IRQ_GSE_FRAMECTL_IRQ 13
#define SSWRP_GSW_PG_ON_NAC_IRQ_GSE_FRAMECTL_IRQ_OFFSET 4013
#define SSWRP_GSW_PG_ON_NAC_IRQ_GSE_RSTCTL_IRQ 14
#define SSWRP_GSW_PG_ON_NAC_IRQ_GSE_RSTCTL_IRQ_OFFSET 4014
#define SSWRP_GSW_PG_ON_NAC_IRQ_GWE_FRAMECTL_IRQ 15
#define SSWRP_GSW_PG_ON_NAC_IRQ_GWE_FRAMECTL_IRQ_OFFSET 4015
#define SSWRP_GSW_PG_ON_NAC_IRQ_GWE_RSTCTL_IRQ 16
#define SSWRP_GSW_PG_ON_NAC_IRQ_GWE_RSTCTL_IRQ_OFFSET 4016
#define SSWRP_GSW_PG_ON_NAC_IRQ_PDMA0_IRQ 17
#define SSWRP_GSW_PG_ON_NAC_IRQ_PDMA0_IRQ_OFFSET 4017
#define SSWRP_GSW_PG_ON_NAC_IRQ_PDMA1_IRQ 18
#define SSWRP_GSW_PG_ON_NAC_IRQ_PDMA1_IRQ_OFFSET 4018

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_XBA0_ERR_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_XBA0_ERR_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ0 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ0_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ1 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ1_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ2 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ2_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ3 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ3_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ4 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ4_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ5 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ5_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ6 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ6_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ7 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GEM_IRQ7_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ0 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ0_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ1 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_ITA_UPDATE_IRQ1_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ0 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ0_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ1 \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_ITA_EXCEPTION_IRQ1_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GSE_FRAMECTL_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GSE_FRAMECTL_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GSE_RSTCTL_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GSE_RSTCTL_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GWE_FRAMECTL_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GWE_FRAMECTL_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_GWE_RSTCTL_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_GWE_RSTCTL_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_PDMA0_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_PDMA0_IRQ_OFFSET)
#define LWIS_PLATFORM_EVENT_ID_SSWRP_GSW_PG_ON_NAC_IRQ_PDMA1_IRQ \
	EVENT_ID(SSWRP_GSW_PG_ON_NAC_IRQ_BASE, \
		 SSWRP_GSW_PG_ON_NAC_IRQ_PDMA1_IRQ_OFFSET)
#endif /* DT_BINDINGS_LWIS_PLATFORM_RDO_SSWRP_GSW_H_ */
