/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright 2025 Google LLC
 */
#ifndef _UFS_REGS_GEN_H_
#define _UFS_REGS_GEN_H_

/**
 * Auto generated platform defines
 * DONOT modify this file manually
 */

/* Begin autogen region hc */
enum hc_offset {
	REG_IS = 0x20,
	REG_BUSTHRTL = 0xc0,
	REG_SECURITY = 0xcc,
	REG_UFSHC_VER_ID_REG = 0xd0,
	REG_UFSHC_VER_TYPE_REG = 0xd4,
	REG_VS_OOO_CONFIG = 0xd8,
	REG_VS_IAG = 0xdc,
	REG_VS_CQES = 0xe0,
	REG_HCLKDIV = 0xf8,
	REG_EXTND_VENDOR_REG_POINTER = 0xfc,
	REG_CCAP = 0x100,
	REG_CRYPTOCAP_0 = 0x104,
	REG_CRYPTOCAP_1 = 0x108,
	REG_UFS_SFTY_MECHANISM_MONITOR_EN_REG = 0x214,
	REG_CONFIG = 0x300,
	REG_MCQCONFIG = 0x380,
};

enum is_bitfields {
	UTRCS_OFFSET = 0x0U,
	UTRCS_MASK = 0x1U,
	UTRCS_DEFAULT = 0x0U,
	UDEPRI_OFFSET = 0x1U,
	UDEPRI_MASK = 0x2U,
	UDEPRI_DEFAULT = 0x0U,
	UE_OFFSET = 0x2U,
	UE_MASK = 0x4U,
	UE_DEFAULT = 0x0U,
	UTMS_OFFSET = 0x3U,
	UTMS_MASK = 0x8U,
	UTMS_DEFAULT = 0x0U,
	UPMS_OFFSET = 0x4U,
	UPMS_MASK = 0x10U,
	UPMS_DEFAULT = 0x0U,
	UHXS_OFFSET = 0x5U,
	UHXS_MASK = 0x20U,
	UHXS_DEFAULT = 0x0U,
	UHES_OFFSET = 0x6U,
	UHES_MASK = 0x40U,
	UHES_DEFAULT = 0x0U,
	ULLS_OFFSET = 0x7U,
	ULLS_MASK = 0x80U,
	ULLS_DEFAULT = 0x0U,
	ULSS_OFFSET = 0x8U,
	ULSS_MASK = 0x100U,
	ULSS_DEFAULT = 0x0U,
	UTMRCS_OFFSET = 0x9U,
	UTMRCS_MASK = 0x200U,
	UTMRCS_DEFAULT = 0x0U,
	UCCS_OFFSET = 0x10U,
	UCCS_MASK = 0x400U,
	UCCS_DEFAULT = 0x0U,
	DFES_OFFSET = 0x11U,
	DFES_MASK = 0x800U,
	DFES_DEFAULT = 0x0U,
	UTPES_OFFSET = 0x12U,
	UTPES_MASK = 0x1000U,
	UTPES_DEFAULT = 0x0U,
	IS_RSVD_15_13_OFFSET = 0x13U,
	IS_RSVD_15_13_MASK = 0xe000U,
	IS_RSVD_15_13_DEFAULT = 0x0U,
	HCFES_OFFSET = 0x16U,
	HCFES_MASK = 0x10000U,
	HCFES_DEFAULT = 0x0U,
	SBFES_OFFSET = 0x17U,
	SBFES_MASK = 0x20000U,
	SBFES_DEFAULT = 0x0U,
	CEFES_OFFSET = 0x18U,
	CEFES_MASK = 0x40000U,
	CEFES_DEFAULT = 0x0U,
	SQES_OFFSET = 0x19U,
	SQES_MASK = 0x80000U,
	SQES_DEFAULT = 0x0U,
	CQES_OFFSET = 0x20U,
	CQES_MASK = 0x100000U,
	CQES_DEFAULT = 0x0U,
	IAGES_OFFSET = 0x21U,
	IAGES_MASK = 0x200000U,
	IAGES_DEFAULT = 0x0U,
	IS_RSVD_28_22_OFFSET = 0x22U,
	IS_RSVD_28_22_MASK = 0x1fc00000U,
	IS_RSVD_28_22_DEFAULT = 0x0U,
	CIS_OFFSET = 0x29U,
	CIS_MASK = 0x20000000U,
	CIS_DEFAULT = 0x0U,
	CRS_OFFSET = 0x30U,
	CRS_MASK = 0x40000000U,
	CRS_DEFAULT = 0x0U,
	CTES_OFFSET = 0x31U,
	CTES_MASK = 0x80000000U,
	CTES_DEFAULT = 0x0U,
};

enum busthrtl_bitfields {
	BUSDLY_OFFSET = 0x0U,
	BUSDLY_MASK = 0xffU,
	BUSDLY_DEFAULT = 0x0U,
	CGE_OFFSET = 0x12U,
	CGE_MASK = 0x1000U,
	CGE_DEFAULT = 0x1U,
	MBL_OFFSET = 0x13U,
	MBL_MASK = 0xe000U,
	MBL_DEFAULT = 0x3U,
	LP_PGE_OFFSET = 0x16U,
	LP_PGE_MASK = 0x10000U,
	LP_PGE_DEFAULT = 0x1U,
	LP_AH8_PGE_OFFSET = 0x17U,
	LP_AH8_PGE_MASK = 0x20000U,
	LP_AH8_PGE_DEFAULT = 0x1U,
	MAXOBUSR_OFFSET = 0x18U,
	MAXOBUSR_MASK = 0xfc0000U,
	MAXOBUSR_DEFAULT = 0x1fU,
	BUSTHRTL_RSVD_27_24_OFFSET = 0x24U,
	BUSTHRTL_RSVD_27_24_MASK = 0xf000000U,
	BUSTHRTL_RSVD_27_24_DEFAULT = 0x0U,
	DME_CTRL_LOGIC_EN_OFFSET = 0x28U,
	DME_CTRL_LOGIC_EN_MASK = 0x10000000U,
	DME_CTRL_LOGIC_EN_DEFAULT = 0x1U,
	LP_NOCARD_PGE_OFFSET = 0x29U,
	LP_NOCARD_PGE_MASK = 0x20000000U,
	LP_NOCARD_PGE_DEFAULT = 0x0U,
	BUSTHRTL_RSVD_31_30_OFFSET = 0x30U,
	BUSTHRTL_RSVD_31_30_MASK = 0xc0000000U,
	BUSTHRTL_RSVD_31_30_DEFAULT = 0x0U,
};

enum security_bitfields {
	KEY_ACC_SEL_OFFSET = 0x0U,
	KEY_ACC_SEL_MASK = 0x1U,
	KEY_ACC_SEL_DEFAULT = 0x0U,
	SECURITY_RSVD_31_1_OFFSET = 0x1U,
	SECURITY_RSVD_31_1_MASK = 0xfffffffeU,
	SECURITY_RSVD_31_1_DEFAULT = 0x0U,
};

enum ufshc_ver_id_reg_bitfields {
	UFSHC_VER_ID_OFFSET = 0x0U,
	UFSHC_VER_ID_MASK = 0xffffffffU,
	UFSHC_VER_ID_DEFAULT = 0x3130312aU,
};

enum ufshc_ver_type_reg_bitfields {
	UFSHC_VER_TYPE_OFFSET = 0x0U,
	UFSHC_VER_TYPE_MASK = 0xffffffffU,
	UFSHC_VER_TYPE_DEFAULT = 0x6c633030U,
};

enum vs_ooo_config_bitfields {
	LBS_OFFSET = 0x0U,
	LBS_MASK = 0xfU,
	LBS_DEFAULT = 0x1U,
	VS_OOO_CONFIG_RSVD_31_4_OFFSET = 0x4U,
	VS_OOO_CONFIG_RSVD_31_4_MASK = 0xfffffff0U,
	VS_OOO_CONFIG_RSVD_31_4_DEFAULT = 0x0U,
};

enum vs_iag_bitfields {
	IAG_ID_OFFSET = 0x0U,
	IAG_ID_MASK = 0xffffU,
	IAG_ID_DEFAULT = 0x0U,
	VS_IAG_RSVD_OFFSET = 0x16U,
	VS_IAG_RSVD_MASK = 0xffff0000U,
	VS_IAG_RSVD_DEFAULT = 0x0U,
};

enum vs_cqes_bitfields {
	CQES_CQID_OFFSET = 0x0U,
	CQES_CQID_MASK = 0xffffU,
	CQES_CQID_DEFAULT = 0x0U,
	VS_CQES_RSVD_OFFSET = 0x16U,
	VS_CQES_RSVD_MASK = 0xffff0000U,
	VS_CQES_RSVD_DEFAULT = 0x0U,
};

enum hclkdiv_bitfields {
	HCLKDIV_OFFSET = 0x0U,
	HCLKDIV_MASK = 0xffffU,
	HCLKDIV_DEFAULT = 0x190U,
	HCLKDIV_RSVD_31_16_OFFSET = 0x16U,
	HCLKDIV_RSVD_31_16_MASK = 0xffff0000U,
	HCLKDIV_RSVD_31_16_DEFAULT = 0x0U,
};

enum extnd_vendor_reg_pointer_bitfields {
	SECTION_OFFSET_OFFSET = 0x0U,
	SECTION_OFFSET_MASK = 0xffffffffU,
	SECTION_OFFSET_DEFAULT = 0x200U,
};

enum ccap_bitfields {
	CC_OFFSET = 0x0U,
	CC_MASK = 0xffU,
	CC_DEFAULT = 0x2U,
	CFGC_OFFSET = 0x8U,
	CFGC_MASK = 0xff00U,
	CFGC_DEFAULT = 0x3fU,
	CCAP_RSVD_23_16_OFFSET = 0x16U,
	CCAP_RSVD_23_16_MASK = 0xff0000U,
	CCAP_RSVD_23_16_DEFAULT = 0x0U,
	CFGPTR_OFFSET = 0x24U,
	CFGPTR_MASK = 0xff000000U,
	CFGPTR_DEFAULT = 0x5U,
};

enum cryptocap_0_bitfields {
	CRYPTOCAP_0_ALGID_OFFSET = 0x0U,
	CRYPTOCAP_0_ALGID_MASK = 0xffU,
	CRYPTOCAP_0_ALGID_DEFAULT = 0x0U,
	CRYPTOCAP_0_SDUSB_OFFSET = 0x8U,
	CRYPTOCAP_0_SDUSB_MASK = 0xff00U,
	CRYPTOCAP_0_SDUSB_DEFAULT = 0x7fU,
	CRYPTOCAP_0_KS_OFFSET = 0x16U,
	CRYPTOCAP_0_KS_MASK = 0xff0000U,
	CRYPTOCAP_0_KS_DEFAULT = 0x3U,
	CRYPTOCAP_0_RSVD_31_24_OFFSET = 0x24U,
	CRYPTOCAP_0_RSVD_31_24_MASK = 0xff000000U,
	CRYPTOCAP_0_RSVD_31_24_DEFAULT = 0x0U,
};

enum cryptocap_1_bitfields {
	CRYPTOCAP_1_ALGID_OFFSET = 0x0U,
	CRYPTOCAP_1_ALGID_MASK = 0xffU,
	CRYPTOCAP_1_ALGID_DEFAULT = 0x0U,
	CRYPTOCAP_1_SDUSB_OFFSET = 0x8U,
	CRYPTOCAP_1_SDUSB_MASK = 0xff00U,
	CRYPTOCAP_1_SDUSB_DEFAULT = 0x7fU,
	CRYPTOCAP_1_KS_OFFSET = 0x16U,
	CRYPTOCAP_1_KS_MASK = 0xff0000U,
	CRYPTOCAP_1_KS_DEFAULT = 0x3U,
	CRYPTOCAP_1_RSVD_31_24_OFFSET = 0x24U,
	CRYPTOCAP_1_RSVD_31_24_MASK = 0xff000000U,
	CRYPTOCAP_1_RSVD_31_24_DEFAULT = 0x0U,
};

enum ufs_sfty_mechanism_monitor_en_reg_bitfields {
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_OFFSET = 0x0U,
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_MASK = 0xffffffffU,
	UFS_SFTY_MECHANISM_MONITOR_EN_REG_DEFAULT = 0x0U,
};

enum config_bitfields {
	QT_OFFSET = 0x0U,
	QT_MASK = 0x1U,
	QT_DEFAULT = 0x0U,
	ESIE_OFFSET = 0x1U,
	ESIE_MASK = 0x2U,
	ESIE_DEFAULT = 0x0U,
	DW2PRDTEN_OFFSET = 0x2U,
	DW2PRDTEN_MASK = 0x4U,
	DW2PRDTEN_DEFAULT = 0x0U,
	CONFIG_RSVD_31_3_OFFSET = 0x3U,
	CONFIG_RSVD_31_3_MASK = 0xfffffff8U,
	CONFIG_RSVD_31_3_DEFAULT = 0x0U,
};

enum mcqconfig_bitfields {
	AS_OFFSET = 0x0U,
	AS_MASK = 0x3U,
	AS_DEFAULT = 0x0U,
	MCQCONFIG_RSVD_7_2_OFFSET = 0x2U,
	MCQCONFIG_RSVD_7_2_MASK = 0xfcU,
	MCQCONFIG_RSVD_7_2_DEFAULT = 0x0U,
	MAC_OFFSET = 0x8U,
	MAC_MASK = 0x1ff00U,
	MAC_DEFAULT = 0x1fU,
	MCQCONFIG_RSVD_31_17_OFFSET = 0x17U,
	MCQCONFIG_RSVD_31_17_MASK = 0xfffe0000U,
	MCQCONFIG_RSVD_31_17_DEFAULT = 0x0U,
};

/* End autogen region hc */

/* Begin autogen region top */
enum top_offset {
	REG_HSIOS_UFS_VERSION = 0x0,
	REG_HSIOS_UFS_CARD_DET = 0x4,
	REG_HSIOS_UFS_ENC_STAT = 0x8,
	REG_HSIOS_UFS_MONITOR_1 = 0x10,
	REG_HSIOS_UFS_MONITOR_2 = 0x14,
	REG_HSIOS_UFS_MONITOR_3 = 0x18,
	REG_HSIOS_UFS_MONITOR_4 = 0x20,
	REG_HSIOS_UFS_UNIPRO_MON_1 = 0x24,
	REG_HSIOS_UFS_UNIPRO_MON_2 = 0x28,
	REG_HSIOS_UFS_UNIPRO_MON_3 = 0x30,
	REG_HSIOS_UFS_MPHY_DTB = 0x40,
	REG_HSIOS_UFS_PWR_CTRL = 0x100,
	REG_HSIOS_UFS_REXT_CTRL = 0x110,
	REG_HSIOS_UFS_AWUSER_VC = 0x200,
	REG_HSIOS_UFS_QOS = 0x204,
	REG_HSIOS_UFS_PHYCLK_SEL = 0x208,
	REG_HSIOS_UFS_CFG_CLKSEL = 0x210,
	REG_HSIOS_UFS_MPHY_CFG = 0x214,
	REG_HSIOS_UFS_SRAM_APB_MODE = 0x510,
};

enum hsios_ufs_version_bitfields {
	UFS_MAJOR_VERSION_OFFSET = 0x0U,
	UFS_MAJOR_VERSION_MASK = 0xffU,
	UFS_MAJOR_VERSION_DEFAULT = 0x1U,
	UFS_MINOR_VERSION_OFFSET = 0x8U,
	UFS_MINOR_VERSION_MASK = 0xff00U,
	UFS_MINOR_VERSION_DEFAULT = 0x1U,
};

enum hsios_ufs_card_det_bitfields {
	UFS_REG_CARD_DET_OFFSET = 0x0U,
	UFS_REG_CARD_DET_MASK = 0x1U,
	UFS_REG_CARD_DET_DEFAULT = 0x1U,
};

enum hsios_ufs_enc_stat_bitfields {
	CRYPTO_KAT_FAIL_STAT_OFFSET = 0x0U,
	CRYPTO_KAT_FAIL_STAT_MASK = 0xfU,
	CRYPTO_KAT_FAIL_STAT_DEFAULT = 0x0U,
	CRYPTO_KAT_STAT_OFFSET = 0x4U,
	CRYPTO_KAT_STAT_MASK = 0x10U,
	CRYPTO_KAT_STAT_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_1_bitfields {
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_1_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_2_bitfields {
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_2_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_3_bitfields {
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_3_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_monitor_4_bitfields {
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_OFFSET = 0x0U,
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_MASK = 0xffffffffU,
	HSIOS_UFS_MONITOR_4_UFS_MONITOR_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_1_bitfields {
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_MASK = 0xffffffffU,
	HSIOS_UFS_UNIPRO_MON_1_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_2_bitfields {
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_MASK = 0xffffffffU,
	HSIOS_UFS_UNIPRO_MON_2_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_unipro_mon_3_bitfields {
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_OFFSET = 0x0U,
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_MASK = 0xffffU,
	HSIOS_UFS_UNIPRO_MON_3_UFS_MONITORUP_DEFAULT = 0x0U,
};

enum hsios_ufs_mphy_dtb_bitfields {
	MPHY_DTB_OUT_OFFSET = 0x0U,
	MPHY_DTB_OUT_MASK = 0x3U,
	MPHY_DTB_OUT_DEFAULT = 0x0U,
};

enum hsios_ufs_pwr_ctrl_bitfields {
	UFS_RESET_N_OFFSET = 0x0U,
	UFS_RESET_N_MASK = 0x1U,
	UFS_RESET_N_DEFAULT = 0x0U,
	UFS_SEL_HIB_SW_CONTROL_OFFSET = 0x1U,
	UFS_SEL_HIB_SW_CONTROL_MASK = 0x2U,
	UFS_SEL_HIB_SW_CONTROL_DEFAULT = 0x0U,
	UFS_LP_RESET_N_OFFSET = 0x2U,
	UFS_LP_RESET_N_MASK = 0x4U,
	UFS_LP_RESET_N_DEFAULT = 0x1U,
	UFS_LP_ISOL_EN_OFFSET = 0x3U,
	UFS_LP_ISOL_EN_MASK = 0x8U,
	UFS_LP_ISOL_EN_DEFAULT = 0x0U,
	UFS_LP_PWR_READY_OFFSET = 0x4U,
	UFS_LP_PWR_READY_MASK = 0x10U,
	UFS_LP_PWR_READY_DEFAULT = 0x0U,
	UFS_LP_PWR_GATE_OFFSET = 0x5U,
	UFS_LP_PWR_GATE_MASK = 0x20U,
	UFS_LP_PWR_GATE_DEFAULT = 0x0U,
	MPHY_REF_CLK_EN_UNIPRO_OFFSET = 0x6U,
	MPHY_REF_CLK_EN_UNIPRO_MASK = 0x40U,
	MPHY_REF_CLK_EN_UNIPRO_DEFAULT = 0x0U,
	MPHY_REF_CLK_EN_APP_OFFSET = 0x7U,
	MPHY_REF_CLK_EN_APP_MASK = 0x80U,
	MPHY_REF_CLK_EN_APP_DEFAULT = 0x0U,
	MPHY_PHY_RESET_OFFSET = 0x8U,
	MPHY_PHY_RESET_MASK = 0x100U,
	MPHY_PHY_RESET_DEFAULT = 0x0U,
	MPHY_CFG_CLOCK_FREQ_OFFSET = 0x9U,
	MPHY_CFG_CLOCK_FREQ_MASK = 0x7e00U,
	MPHY_CFG_CLOCK_FREQ_DEFAULT = 0x26U,
	UFS_TX_MK2EXTENSIONEN_OFFSET = 0x15U,
	UFS_TX_MK2EXTENSIONEN_MASK = 0x8000U,
	UFS_TX_MK2EXTENSIONEN_DEFAULT = 0x0U,
	UFS_SRAM_BYPASS_OFFSET = 0x16U,
	UFS_SRAM_BYPASS_MASK = 0x30000U,
	UFS_SRAM_BYPASS_DEFAULT = 0x0U,
	UFS_SRAM_BOOTLOAD_BYPASS_OFFSET = 0x18U,
	UFS_SRAM_BOOTLOAD_BYPASS_MASK = 0xc0000U,
	UFS_SRAM_BOOTLOAD_BYPASS_DEFAULT = 0x0U,
	UFS_SRAM_EXT_LD_DONE_OFFSET = 0x20U,
	UFS_SRAM_EXT_LD_DONE_MASK = 0x100000U,
	UFS_SRAM_EXT_LD_DONE_DEFAULT = 0x0U,
	UFS_SRAM_INIT_DONE_OFFSET = 0x21U,
	UFS_SRAM_INIT_DONE_MASK = 0x200000U,
	UFS_SRAM_INIT_DONE_DEFAULT = 0x0U,
	UFS_CG_SYSCLKREQ_OFFSET = 0x22U,
	UFS_CG_SYSCLKREQ_MASK = 0x400000U,
	UFS_CG_SYSCLKREQ_DEFAULT = 0x0U,
	UFS_CG_CLKTREQ_OFFSET = 0x23U,
	UFS_CG_CLKTREQ_MASK = 0x800000U,
	UFS_CG_CLKTREQ_DEFAULT = 0x0U,
	UFS_CG_LP_CLK_TREQ_OFFSET = 0x24U,
	UFS_CG_LP_CLK_TREQ_MASK = 0x1000000U,
	UFS_CG_LP_CLK_TREQ_DEFAULT = 0x0U,
	MPHY_PCS_PWR_EN_OFFSET = 0x25U,
	MPHY_PCS_PWR_EN_MASK = 0x2000000U,
	MPHY_PCS_PWR_EN_DEFAULT = 0x0U,
	MPHY_PCS_PWR_STABLE_OFFSET = 0x26U,
	MPHY_PCS_PWR_STABLE_MASK = 0x4000000U,
	MPHY_PCS_PWR_STABLE_DEFAULT = 0x0U,
	UFS_SEL_ISO_SW_CONTROL_OFFSET = 0x27U,
	UFS_SEL_ISO_SW_CONTROL_MASK = 0x8000000U,
	UFS_SEL_ISO_SW_CONTROL_DEFAULT = 0x0U,
};

enum hsios_ufs_rext_ctrl_bitfields {
	UFS_REXT_CONTROL_OFFSET = 0x0U,
	UFS_REXT_CONTROL_MASK = 0x3fU,
	UFS_REXT_CONTROL_DEFAULT = 0x0U,
	UFS_REXT_EN_OFFSET = 0x6U,
	UFS_REXT_EN_MASK = 0x40U,
	UFS_REXT_EN_DEFAULT = 0x0U,
	UFS_PRE_VREG_BYPASS_OFFSET = 0x7U,
	UFS_PRE_VREG_BYPASS_MASK = 0x80U,
	UFS_PRE_VREG_BYPASS_DEFAULT = 0x0U,
};

enum hsios_ufs_awuser_vc_bitfields {
	UFS_AWUSERVC_OFFSET = 0x0U,
	UFS_AWUSERVC_MASK = 0x7U,
	UFS_AWUSERVC_DEFAULT = 0x0U,
	UFS_ARUSERVC_OFFSET = 0x8U,
	UFS_ARUSERVC_MASK = 0x700U,
	UFS_ARUSERVC_DEFAULT = 0x0U,
};

enum hsios_ufs_qos_bitfields {
	UFS_AW_QOS_OFFSET = 0x0U,
	UFS_AW_QOS_MASK = 0x3U,
	UFS_AW_QOS_DEFAULT = 0x0U,
	UFS_AR_QOS_OFFSET = 0x8U,
	UFS_AR_QOS_MASK = 0x300U,
	UFS_AR_QOS_DEFAULT = 0x0U,
};

enum hsios_ufs_phyclk_sel_bitfields {
	REF_CLK_SEL_OFFSET = 0x0U,
	REF_CLK_SEL_MASK = 0x7U,
	REF_CLK_SEL_DEFAULT = 0x2U,
};

enum hsios_ufs_cfg_clksel_bitfields {
	CFG_CLK_SEL_OFFSET = 0x0U,
	CFG_CLK_SEL_MASK = 0x7U,
	CFG_CLK_SEL_DEFAULT = 0x2U,
};

enum hsios_ufs_mphy_cfg_bitfields {
	UFS_MPHY_CFG_OFFSET = 0x0U,
	UFS_MPHY_CFG_MASK = 0x3U,
	UFS_MPHY_CFG_DEFAULT = 0x1U,
};

enum hsios_ufs_sram_apb_mode_bitfields {
	UFS_SRAM_APB_MODE_OFFSET = 0x0U,
	UFS_SRAM_APB_MODE_MASK = 0x1U,
	UFS_SRAM_APB_MODE_DEFAULT = 0x0U,
};

/* End autogen region top */

#endif /* _UFS_REGS_GEN_H_ */
