/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright 2025 Google LLC
 * Google's SoC-specific Glue Driver for the DWC DPTX
 */

enum dp_tune_rate {
	DP_TUNE_RBR = 0,
	DP_TUNE_HBR,
	DP_TUNE_HBR2,
	DP_TUNE_HBR3,
	DP_TUNE_NUM_RATES,
};

enum dp_tune_vs {
	DP_TUNE_VS_0 = 0,
	DP_TUNE_VS_1,
	DP_TUNE_VS_2,
	DP_TUNE_VS_3,
	DP_TUNE_NUM_VS,
};

enum dp_tune_pe {
	DP_TUNE_PE_0 = 0,
	DP_TUNE_PE_1,
	DP_TUNE_PE_2,
	DP_TUNE_PE_3,
	DP_TUNE_NUM_PE,
};

/*
 * eq_tune_rates used to iteratively construct dts property names and sysfs
 * directory names
 */
static const char *const eq_tune_rates[] = {
	[DP_TUNE_RBR] = "rbr",
	[DP_TUNE_HBR] = "hbr",
	[DP_TUNE_HBR2] = "hbr2",
	[DP_TUNE_HBR3] = "hbr3",
};

/* eq_tune_vs used to construct sysfs directory names */
static const char *const eq_tune_vs[] = {
	[DP_TUNE_VS_0] = "vs_0",
	[DP_TUNE_VS_1] = "vs_1",
	[DP_TUNE_VS_2] = "vs_2",
	[DP_TUNE_VS_3] = "vs_3",
};

/* eq_tune_pe used to construct sysfs directory names */
static const char *const eq_tune_pe[] = {
	[DP_TUNE_VS_0] = "pe_0",
	[DP_TUNE_VS_1] = "pe_1",
	[DP_TUNE_VS_2] = "pe_2",
	[DP_TUNE_VS_3] = "pe_3",
};

/*
 * dp_tune_attr_grps holds main/pre/post files generated by DP_TUNE_PE_GROUP so the phy driver
 * can access attribute groups programmatically instead of by name
 */
static struct attribute_group *dp_tune_attr_grps[DP_TUNE_NUM_RATES][DP_TUNE_NUM_VS][DP_TUNE_NUM_PE];

/*
 * dp_tune_coeff_type used in dp_tune_attribute so the correct gphy->dp_tune_<coeff> map is
 * selected
 */
enum dp_tune_coeff_type {
	DP_TUNE_MAIN,
	DP_TUNE_PRE,
	DP_TUNE_POST,
};

/*
 * dp_tune_kobj_data and derivatives for pe/vs/rate are used to generate sysfs files in the
 * correct hierarchy
 */
struct dp_tune_pe_kobj_data {
	struct kobject *kobj;
};

struct dp_tune_vs_kobj_data {
	struct kobject *kobj;
	struct dp_tune_pe_kobj_data pe[DP_TUNE_NUM_PE];
};

struct dp_tune_rate_kobj_data {
	struct kobject *kobj;
	struct dp_tune_vs_kobj_data vs[DP_TUNE_NUM_VS];
};

struct dp_tune_kobj_data {
	struct kobject *kobj;
	struct dp_tune_rate_kobj_data rates[DP_TUNE_NUM_RATES];
};

/*
 * dp_tune_attribute holds info necessary for reading/writing main/pre/post coefficients
 * from gphy->dp_tune_<coeff> in dp_tune_coeff_show/store functions without the need to
 * generate a new one for each sysfs attribute.
 */
struct dp_tune_attribute {
	struct kobj_attribute attr;
	enum dp_tune_coeff_type coeff;
	u8 rate;
	u8 vs;
	u8 pe;
};

static ssize_t dp_tune_coeff_store(struct kobject *kobj, struct kobj_attribute *attr,
	const char *buf, size_t count);

static ssize_t dp_tune_coeff_show(struct kobject *kobj, struct kobj_attribute *attr, char *buf);

/*
 * DP_TUNE_PE_GROUP macro generates sysfs kobj attributes for a rate/vs/pe combo's main/pre/post
 * coefficients, and then combines them into a common attribute group.
 */
#define DP_TUNE_PE_GROUP(_rate, _vs, _pe)							\
static struct dp_tune_attribute dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_main =		\
	{ __ATTR(main, 0644, dp_tune_coeff_show, dp_tune_coeff_store),				\
	 DP_TUNE_MAIN, _rate, _vs, _pe };							\
static struct dp_tune_attribute dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_pre =		\
	{ __ATTR(pre, 0644, dp_tune_coeff_show, dp_tune_coeff_store),				\
	 DP_TUNE_PRE, _rate, _vs, _pe };							\
static struct dp_tune_attribute dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_post =		\
	{ __ATTR(post, 0644, dp_tune_coeff_show, dp_tune_coeff_store),				\
	 DP_TUNE_POST, _rate, _vs, _pe };							\
												\
static struct attribute *dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_attrs[] = {		\
	&dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_main.attr.attr,				\
	&dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_pre.attr.attr,				\
	&dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_post.attr.attr,				\
	NULL											\
};												\
												\
static struct attribute_group dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_group = {		\
	.attrs = dp_tune_rate_##_rate##_vs_##_vs##_pe_##_pe##_attrs,				\
}

/* RBR */
DP_TUNE_PE_GROUP(0, 0, 0);
DP_TUNE_PE_GROUP(0, 0, 1);
DP_TUNE_PE_GROUP(0, 0, 2);
DP_TUNE_PE_GROUP(0, 0, 3);
DP_TUNE_PE_GROUP(0, 1, 0);
DP_TUNE_PE_GROUP(0, 1, 1);
DP_TUNE_PE_GROUP(0, 1, 2);
DP_TUNE_PE_GROUP(0, 2, 0);
DP_TUNE_PE_GROUP(0, 2, 1);
DP_TUNE_PE_GROUP(0, 3, 0);
/* HBR */
DP_TUNE_PE_GROUP(1, 0, 0);
DP_TUNE_PE_GROUP(1, 0, 1);
DP_TUNE_PE_GROUP(1, 0, 2);
DP_TUNE_PE_GROUP(1, 0, 3);
DP_TUNE_PE_GROUP(1, 1, 0);
DP_TUNE_PE_GROUP(1, 1, 1);
DP_TUNE_PE_GROUP(1, 1, 2);
DP_TUNE_PE_GROUP(1, 2, 0);
DP_TUNE_PE_GROUP(1, 2, 1);
DP_TUNE_PE_GROUP(1, 3, 0);
/* HBR2 */
DP_TUNE_PE_GROUP(2, 0, 0);
DP_TUNE_PE_GROUP(2, 0, 1);
DP_TUNE_PE_GROUP(2, 0, 2);
DP_TUNE_PE_GROUP(2, 0, 3);
DP_TUNE_PE_GROUP(2, 1, 0);
DP_TUNE_PE_GROUP(2, 1, 1);
DP_TUNE_PE_GROUP(2, 1, 2);
DP_TUNE_PE_GROUP(2, 2, 0);
DP_TUNE_PE_GROUP(2, 2, 1);
DP_TUNE_PE_GROUP(2, 3, 0);
/* HBR3 */
DP_TUNE_PE_GROUP(3, 0, 0);
DP_TUNE_PE_GROUP(3, 0, 1);
DP_TUNE_PE_GROUP(3, 0, 2);
DP_TUNE_PE_GROUP(3, 0, 3);
DP_TUNE_PE_GROUP(3, 1, 0);
DP_TUNE_PE_GROUP(3, 1, 1);
DP_TUNE_PE_GROUP(3, 1, 2);
DP_TUNE_PE_GROUP(3, 2, 0);
DP_TUNE_PE_GROUP(3, 2, 1);
DP_TUNE_PE_GROUP(3, 3, 0);

/*
 * generated attribute groups need to be assigned to dp_tune_attr_grps so driver can access using
 * rate/vs/pe instead of full attribute group name
 */
static void google_dpphy_sysfs_init_attr_groups(void)
{
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_0][DP_TUNE_PE_0] =
		&dp_tune_rate_0_vs_0_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_0][DP_TUNE_PE_1] =
		&dp_tune_rate_0_vs_0_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_0][DP_TUNE_PE_2] =
		&dp_tune_rate_0_vs_0_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_0][DP_TUNE_PE_3] =
		&dp_tune_rate_0_vs_0_pe_3_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_1][DP_TUNE_PE_0] =
		&dp_tune_rate_0_vs_1_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_1][DP_TUNE_PE_1] =
		&dp_tune_rate_0_vs_1_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_1][DP_TUNE_PE_2] =
		&dp_tune_rate_0_vs_1_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_2][DP_TUNE_PE_0] =
		&dp_tune_rate_0_vs_2_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_2][DP_TUNE_PE_1] =
		&dp_tune_rate_0_vs_2_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_RBR][DP_TUNE_VS_3][DP_TUNE_PE_0] =
		&dp_tune_rate_0_vs_3_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_0][DP_TUNE_PE_0] =
		&dp_tune_rate_1_vs_0_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_0][DP_TUNE_PE_1] =
		&dp_tune_rate_1_vs_0_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_0][DP_TUNE_PE_2] =
		&dp_tune_rate_1_vs_0_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_0][DP_TUNE_PE_3] =
		&dp_tune_rate_1_vs_0_pe_3_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_1][DP_TUNE_PE_0] =
		&dp_tune_rate_1_vs_1_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_1][DP_TUNE_PE_1] =
		&dp_tune_rate_1_vs_1_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_1][DP_TUNE_PE_2] =
		&dp_tune_rate_1_vs_1_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_2][DP_TUNE_PE_0] =
		&dp_tune_rate_1_vs_2_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_2][DP_TUNE_PE_1] =
		&dp_tune_rate_1_vs_2_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR][DP_TUNE_VS_3][DP_TUNE_PE_0] =
		&dp_tune_rate_1_vs_3_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_0][DP_TUNE_PE_0] =
		&dp_tune_rate_2_vs_0_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_0][DP_TUNE_PE_1] =
		&dp_tune_rate_2_vs_0_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_0][DP_TUNE_PE_2] =
		&dp_tune_rate_2_vs_0_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_0][DP_TUNE_PE_3] =
		&dp_tune_rate_2_vs_0_pe_3_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_1][DP_TUNE_PE_0] =
		&dp_tune_rate_2_vs_1_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_1][DP_TUNE_PE_1] =
		&dp_tune_rate_2_vs_1_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_1][DP_TUNE_PE_2] =
		&dp_tune_rate_2_vs_1_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_2][DP_TUNE_PE_0] =
		&dp_tune_rate_2_vs_2_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_2][DP_TUNE_PE_1] =
		&dp_tune_rate_2_vs_2_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR2][DP_TUNE_VS_3][DP_TUNE_PE_0] =
		&dp_tune_rate_2_vs_3_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_0][DP_TUNE_PE_0] =
		&dp_tune_rate_3_vs_0_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_0][DP_TUNE_PE_1] =
		&dp_tune_rate_3_vs_0_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_0][DP_TUNE_PE_2] =
		&dp_tune_rate_3_vs_0_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_0][DP_TUNE_PE_3] =
		&dp_tune_rate_3_vs_0_pe_3_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_1][DP_TUNE_PE_0] =
		&dp_tune_rate_3_vs_1_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_1][DP_TUNE_PE_1] =
		&dp_tune_rate_3_vs_1_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_1][DP_TUNE_PE_2] =
		&dp_tune_rate_3_vs_1_pe_2_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_2][DP_TUNE_PE_0] =
		&dp_tune_rate_3_vs_2_pe_0_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_2][DP_TUNE_PE_1] =
		&dp_tune_rate_3_vs_2_pe_1_group;
	dp_tune_attr_grps[DP_TUNE_HBR3][DP_TUNE_VS_3][DP_TUNE_PE_0] =
		&dp_tune_rate_3_vs_3_pe_0_group;
}

#define GOOGLE_USB_PHY_DEBUGFS_EQ_TUNE_ASIC_READ_LANE_N(_lane)					\
static int google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_main(void *data, u64 *val)	\
{												\
	struct google_usb_phy *gphy = data;							\
	mutex_lock(&gphy->lock);								\
	u16 reg, main;										\
												\
	if (gphy->phy_state != COMBO_PHY_TCA_READY) {						\
		*val = -EPERM;									\
		mutex_unlock(&gphy->lock);							\
		return 0;									\
	}											\
												\
	reg = readw(gphy->dptx_phy_regs_base + LANEN_DIG_ASIC_TX_ASIC_IN_1(_lane));		\
	main = ((reg & TX_MAIN_CURSOR_MASK) >> TX_MAIN_CURSOR_OFFSET) / 2;			\
	*val = main;										\
												\
	mutex_unlock(&gphy->lock);								\
	return 0;										\
}												\
												\
static int google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_pre(void *data, u64 *val)	\
{												\
	struct google_usb_phy *gphy = data;							\
	mutex_lock(&gphy->lock);								\
	u16 reg, pre;										\
												\
	if (gphy->phy_state != COMBO_PHY_TCA_READY) {						\
		*val = -EPERM;									\
		mutex_unlock(&gphy->lock);							\
		return 0;									\
	}											\
												\
	reg = readw(gphy->dptx_phy_regs_base + LANEN_DIG_ASIC_TX_ASIC_IN_2(_lane));		\
	pre = ((reg & TX_PRE_CURSOR_MASK) >> TX_PRE_CURSOR_OFFSET) / 2;				\
	*val = pre;										\
												\
	mutex_unlock(&gphy->lock);								\
	return 0;										\
}												\
												\
static int google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_post(void *data, u64 *val)	\
{												\
	struct google_usb_phy *gphy = data;							\
	mutex_lock(&gphy->lock);								\
	u16 reg, post;										\
												\
	if (gphy->phy_state != COMBO_PHY_TCA_READY) {						\
		*val = -EPERM;									\
		mutex_unlock(&gphy->lock);							\
		return 0;									\
	}											\
												\
	reg = readw(gphy->dptx_phy_regs_base + LANEN_DIG_ASIC_TX_ASIC_IN_2(_lane));		\
	post = ((reg & TX_POST_CURSOR_MASK) >> TX_POST_CURSOR_OFFSET) / 2;			\
	*val = post;										\
												\
	mutex_unlock(&gphy->lock);								\
	return 0;										\
}												\
DEFINE_DEBUGFS_ATTRIBUTE(google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_main_fops,	\
	google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_main, NULL, "%lld\n");		\
DEFINE_DEBUGFS_ATTRIBUTE(google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_pre_fops,	\
	google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_pre, NULL, "%lld\n");		\
DEFINE_DEBUGFS_ATTRIBUTE(google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_post_fops,	\
	google_usb_phy_debugfs_eq_tune_asic_read_lane_##_lane##_post, NULL, "%lld\n")
