// SPDX-License-Identifier: GPL-2.0-only
/*
 * Platform device driver to power on/off google soc power domains
 * Copyright (C) 2024 Google LLC.
 */

#include <dt-bindings/power/genpd_lga.h>
#include <mailbox/protocols/mba/cpm/common/lpb/lpb_service.h>

#include "cpm_mappings.h"

#define LPCM_GENPD_SSWRP_DPU 0
#define LPCM_GENPD_SSWRP_HSIO_S 1
#define LPCM_GENPD_SSWRP_HSIO_N 2
#define LPCM_GENPD_SSWRP_LSIO_S 3
#define LPCM_GENPD_SSWRP_LSIO_N 4
#define LPCM_GENPD_SSWRP_LSIO_E 5
#define LPCM_GENPD_SSWRP_G2D 6
#define LPCM_GENPD_SSWRP_GPDMA 7
#define LPCM_GENPD_SSWRP_ISPFE 8
#define LPCM_GENPD_SSWRP_AOC 9

static const u32 sswrp_id_cpm_lpb_mapping[GENPD_LGA_SSWRP_COUNT] = {
	[GENPD_LGA_SSWRP_AOC_ID] = LPB_SERVICE_AOC_ID,
	[GENPD_LGA_SSWRP_AURORA_ID] = LPB_SERVICE_AURORA_ID,
	[GENPD_LGA_SSWRP_CODEC_3P_ID] = LPB_SERVICE_CODEC_3P_ID,
	[GENPD_LGA_SSWRP_CPU_ID] = LPB_SERVICE_CPU_ID,
	[GENPD_LGA_SSWRP_CPUACC_ID] = LPB_SERVICE_CPUACC_ID,
	[GENPD_LGA_SSWRP_DPU_ID] = LPB_SERVICE_DPU_ID,
	[GENPD_LGA_SSWRP_EH_ID] = LPB_SERVICE_EH_ID,
	[GENPD_LGA_SSWRP_FABHBW_ID] = LPB_SERVICE_FABHBW_ID,
	[GENPD_LGA_SSWRP_FABMED_ID] = LPB_SERVICE_FABMED_ID,
	[GENPD_LGA_SSWRP_FABRT_ID] = LPB_SERVICE_FABRT_ID,
	[GENPD_LGA_SSWRP_FABSTBY_ID] = LPB_SERVICE_FABSTBY_ID,
	[GENPD_LGA_SSWRP_FABSYSS_ID] = LPB_SERVICE_FABSYSS_ID,
	[GENPD_LGA_SSWRP_G2D_ID] = LPB_SERVICE_G2D_ID,
	[GENPD_LGA_SSWRP_GMC0_ID] = LPB_SERVICE_GMC0_ID,
	[GENPD_LGA_SSWRP_GMC1_ID] = LPB_SERVICE_GMC1_ID,
	[GENPD_LGA_SSWRP_GMC2_ID] = LPB_SERVICE_GMC2_ID,
	[GENPD_LGA_SSWRP_GMC3_ID] = LPB_SERVICE_GMC3_ID,
	[GENPD_LGA_SSWRP_GPCA_ID] = LPB_SERVICE_GPCA_ID,
	[GENPD_LGA_SSWRP_GPCM_ID] = LPB_SERVICE_GPCM_ID,
	[GENPD_LGA_SSWRP_GPDMA_ID] = LPB_SERVICE_GPDMA_ID,
	[GENPD_LGA_SSWRP_GPU_ID] = LPB_SERVICE_GPU_ID,
	[GENPD_LGA_SSWRP_GSA_ID] = LPB_SERVICE_GSA_ID,
	[GENPD_LGA_SSWRP_GSW_ID] = LPB_SERVICE_GSW_ID,
	[GENPD_LGA_SSWRP_HSIO_N_ID] = LPB_SERVICE_HSIO_N_ID,
	[GENPD_LGA_SSWRP_HSIO_S_ID] = LPB_SERVICE_HSIO_S_ID,
	[GENPD_LGA_SSWRP_INF_TCU_ID] = LPB_SERVICE_INF_TCU_ID,
	[GENPD_LGA_SSWRP_ISPBE_ID] = LPB_SERVICE_ISPBE_ID,
	[GENPD_LGA_SSWRP_ISPFE_ID] = LPB_SERVICE_ISPFE_ID,
	[GENPD_LGA_SSWRP_LSIO_E_ID] = LPB_SERVICE_LSIO_E_ID,
	[GENPD_LGA_SSWRP_LSIO_N_ID] = LPB_SERVICE_LSIO_N_ID,
	[GENPD_LGA_SSWRP_LSIO_S_ID] = LPB_SERVICE_LSIO_S_ID,
	[GENPD_LGA_SSWRP_MEMSS_ID] = LPB_SERVICE_MEMSS_ID,
	[GENPD_LGA_SSWRP_TPU_ID] = LPB_SERVICE_TPU_ID,
	[GENPD_LGA_LSIO_E_CLI_GPIO_IRQ_SAFE_ID] = LPB_SERVICE_LSIO_E_ID,
	[GENPD_LGA_LSIO_S_CLI_GPIO_IRQ_SAFE_ID] = LPB_SERVICE_LSIO_S_ID,
	[GENPD_LGA_LSIO_N_CLI_GPIO_IRQ_SAFE_ID] = LPB_SERVICE_LSIO_N_ID,
};

static const u32 sswrp_id_cpm_lpcm_mapping[GENPD_LGA_SSWRP_COUNT] = {
	[GENPD_LGA_SSWRP_AOC_ID] = LPCM_GENPD_SSWRP_AOC,
	[GENPD_LGA_SSWRP_AURORA_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_CODEC_3P_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_CPU_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_CPUACC_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_DPU_ID] = LPCM_GENPD_SSWRP_DPU,
	[GENPD_LGA_SSWRP_EH_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_FABHBW_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_FABMED_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_FABRT_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_FABSTBY_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_FABSYSS_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_G2D_ID] = LPCM_GENPD_SSWRP_G2D,
	[GENPD_LGA_SSWRP_GMC0_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GMC1_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GMC2_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GMC3_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GPCA_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GPCM_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GPDMA_ID] = LPCM_GENPD_SSWRP_GPDMA,
	[GENPD_LGA_SSWRP_GPU_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GSA_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_GSW_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_HSIO_N_ID] = LPCM_GENPD_SSWRP_HSIO_N,
	[GENPD_LGA_SSWRP_HSIO_S_ID] = LPCM_GENPD_SSWRP_HSIO_S,
	[GENPD_LGA_SSWRP_INF_TCU_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_ISPBE_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_ISPFE_ID] = LPCM_GENPD_SSWRP_ISPFE,
	[GENPD_LGA_SSWRP_LSIO_E_ID] = LPCM_GENPD_SSWRP_LSIO_E,
	[GENPD_LGA_SSWRP_LSIO_N_ID] = LPCM_GENPD_SSWRP_LSIO_N,
	[GENPD_LGA_SSWRP_LSIO_S_ID] = LPCM_GENPD_SSWRP_LSIO_S,
	[GENPD_LGA_SSWRP_MEMSS_ID] = NOT_SUPPORTED,
	[GENPD_LGA_SSWRP_TPU_ID] = NOT_SUPPORTED,
	[GENPD_LGA_LSIO_S_CLI_GPIO_IRQ_SAFE_ID] = LPCM_GENPD_SSWRP_LSIO_S,
	[GENPD_LGA_LSIO_E_CLI_GPIO_IRQ_SAFE_ID] = LPCM_GENPD_SSWRP_LSIO_E,
	[GENPD_LGA_LSIO_N_CLI_GPIO_IRQ_SAFE_ID] = LPCM_GENPD_SSWRP_LSIO_N,
};

const struct cpm_mappings lga_cpm_mappings = {
	.lpb_sswrp_ids = sswrp_id_cpm_lpb_mapping,
	.lpcm_sswrp_ids = sswrp_id_cpm_lpcm_mapping,
	.num_sswrp_ids = LPB_SERVICE_NUM_SSWRPS,
};
