/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 Synopsys, Inc. and/or its affiliates.
 * Synopsys DesignWare Resource Manager
 */

#ifndef _DW_MIPI_DPHY_G301_H_
#define _DW_MIPI_DPHY_G301_H_

#include <linux/regmap.h>
#include "dw-mipi-cdphy.h"
#include "dw-mipi-cdphy-g301-clock-calc.h"

#define PHY_STATUS_TIMEOUT_US	10000

/* dwc_mipi_cdphy_tx_4l3t_ns */
#define PPI_STARTUP_RW_COMMON_DPHY_0			(0x0c00 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_1			(0x0c01 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_2			(0x0c02 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_3			(0x0c03 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_4			(0x0c04 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_5			(0x0c05 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_6			(0x0c06 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_7			(0x0c07 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_8			(0x0c08 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_9			(0x0c09 * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_A			(0x0c0a * 4)
#define PPI_STARTUP_RW_COMMON_DPHY_10			(0x0c10 * 4)
#define PPI_STARTUP_RW_COMMON_STARTUP_1_1		(0x0c11 * 4)
#define PPI_STARTUP_RW_COMMON_STARTUP_1_2		(0x0c12 * 4)

#define PPI_CALIBCTRL_RW_COMMON_CALIBCTRL_2_0		(0x0c20 * 4)
#define PPI_CALIBCTRL_R_COMMON_CALIBCTRL_2_1		(0x0c21 * 4)
#define PPI_CALIBCTRL_R_COMMON_CALIBCTRL_2_2		(0x0c22 * 4)
#define PPI_CALIBCTRL_R_COMMON_CALIBCTRL_2_3		(0x0c23 * 4)
#define PPI_CALIBCTRL_R_COMMON_CALIBCTRL_2_4		(0x0c24 * 4)
#define PPI_CALIBCTRL_R_COMMON_CALIBCTRL_2_5		(0x0c25 * 4)
#define PPI_CALIBCTRL_RW_COMMON_BG_0			(0x0c26 * 4)
#define PPI_CALIBCTRL_RW_COMMON_CALIBCTRL_2_7		(0x0c27 * 4)
#define PPI_CALIBCTRL_RW_ADC_CFG_0			(0x0c28 * 4)
#define PPI_CALIBCTRL_RW_ADC_CFG_1			(0x0c29 * 4)
#define PPI_CALIBCTRL_R_ADC_DEBUG			(0x0c2a * 4)

#define PPI_RW_LPDCOCAL_TOP_OVERRIDE			(0x0e00 * 4)
#define PPI_RW_LPDCOCAL_TIMEBASE			(0x0e01 * 4)
#define PPI_RW_LPDCOCAL_NREF				(0x0e02 * 4)
#define PPI_RW_LPDCOCAL_NREF_RANGE			(0x0e03 * 4)
#define PPI_RW_LPDCOCAL_NREF_TRIGGER_MAN		(0x0e04 * 4)
#define PPI_RW_LPDCOCAL_TWAIT_CONFIG			(0x0e05 * 4)
#define PPI_RW_LPDCOCAL_VT_CONFIG			(0x0e06 * 4)
#define PPI_R_LPDCOCAL_DEBUG_RB				(0x0e07 * 4)
#define PPI_RW_LPDCOCAL_COARSE_CFG			(0x0e08 * 4)
#define PPI_R_LPDCOCAL_DEBUG_COARSE_RB			(0x0e09 * 4)
#define PPI_R_LPDCOCAL_DEBUG_COARSE_MEAS_0_RB		(0x0e0a * 4)
#define PPI_R_LPDCOCAL_DEBUG_COARSE_MEAS_1_RB		(0x0e0b * 4)
#define PPI_R_LPDCOCAL_DEBUG_COARSE_FWORD_RB		(0x0e0c * 4)
#define PPI_R_LPDCOCAL_DEBUG_MEASURE_CURR_ERROR		(0x0e0d * 4)
#define PPI_R_LPDCOCAL_DEBUG_MEASURE_LAST_ERROR		(0x0e0e * 4)
#define PPI_R_LPDCOCAL_DEBUG_VT				(0x0e0f * 4)
#define PPI_RW_LB_TIMEBASE_CONFIG			(0x0e10 * 4)
#define PPI_RW_LB_STARTCMU_CONFIG			(0x0e11 * 4)
#define PPI_R_LBPULSE_COUNTER_RB			(0x0e12 * 4)
#define PPI_R_LB_START_CMU_RB				(0x0e13 * 4)
#define PPI_RW_LB_DPHY_BURST_START			(0x0e14 * 4)
#define PPI_RW_LB_CPHY_BURST_START			(0x0e15 * 4)

#define PPI_RW_DDLCAL_CFG_0				(0x0e20 * 4)
#define PPI_RW_DDLCAL_CFG_1				(0x0e21 * 4)
#define PPI_RW_DDLCAL_CFG_2				(0x0e22 * 4)
#define PPI_RW_DDLCAL_CFG_3				(0x0e23 * 4)
#define PPI_RW_DDLCAL_CFG_4				(0x0e24 * 4)
#define PPI_RW_DDLCAL_CFG_5				(0x0e25 * 4)
#define PPI_RW_DDLCAL_CFG_6				(0x0e26 * 4)
#define PPI_RW_DDLCAL_CFG_7				(0x0e27 * 4)
#define PPI_R_DDLCAL_DEBUG_0				(0x0e28 * 4)
#define PPI_R_DDLCAL_DEBUG_1				(0x0e29 * 4)
#define PPI_RW_PARITY_TEST				(0x0e30 * 4)
#define PPI_RW_STARTUP_OVR_0				(0x0e31 * 4)
#define PPI_RW_STARTUP_OVR_1				(0x0e32 * 4)
#define PPI_RW_DTB_SELECTOR				(0x0e33 * 4)
#define PPI_RW_HSTX_FIFO_CFG				(0x0e34 * 4)
#define PPI_RW_DPHY_CLK_SPARE				(0x0e35 * 4)
#define PPI_RW_COMMON_CFG				(0x0e36 * 4)
#define PPI_RW_CLK_DIV_FACTOR_CFG			(0x0e37 * 4)

#define PPI_RW_TERMCAL_CFG_0				(0x0e40 * 4)
#define PPI_R_TERMCAL_DEBUG_0				(0x0e41 * 4)
#define PPI_RW_TERMCAL_CTRL_0				(0x0e42 * 4)

#define PPI_RW_OFFSETCAL_CFG_0				(0x0e50 * 4)
#define PPI_R_OFFSETCAL_DEBUG_LANE0			(0x0e51 * 4)
#define PPI_R_OFFSETCAL_DEBUG_LANE1			(0x0e52 * 4)
#define PPI_R_OFFSETCAL_DEBUG_LANE2			(0x0e53 * 4)
#define PPI_R_OFFSETCAL_DEBUG_LANE3			(0x0e54 * 4)
#define PPI_R_OFFSETCAL_DEBUG_LANE4			(0x0e55 * 4)

#define PPI_RW_PLL_STARTUP_CFG_0			(0x0e60 * 4)
#define PPI_RW_PLL_STARTUP_CFG_1			(0x0e61 * 4)
#define PPI_RW_PLL_STARTUP_CFG_2			(0x0e62 * 4)
#define PPI_RW_PLL_STARTUP_CFG_3			(0x0e63 * 4)
#define PPI_RW_PLL_STARTUP_CFG_4			(0x0e64 * 4)
#define PPI_R_PLL_STARTUP_DEBUG				(0x0e65 * 4)

#define PPI_RW_TX_HIBERNATE_CFG_0			(0x0e70 * 4)

#define PPI_RW_HSDCOCAL_CFG_O				(0x0e80 * 4)
#define PPI_RW_HSDCOCAL_CFG_1				(0x0e81 * 4)
#define PPI_RW_HSDCOCAL_CFG_2				(0x0e82 * 4)
#define PPI_RW_HSDCOCAL_CFG_3				(0x0e83 * 4)
#define PPI_RW_HSDCOCAL_CFG_4				(0x0e84 * 4)
#define PPI_RW_HSDCOCAL_CFG_5				(0x0e85 * 4)
#define PPI_RW_HSDCOCAL_CFG_6				(0x0e86 * 4)
#define PPI_RW_HSDCOCAL_CFG_7				(0x0e87 * 4)
#define PPI_RW_HSDCOCAL_CFG_8				(0x0e88 * 4)
#define PPI_R_HSDCOCAL_DEBUG_RB				(0x0e89 * 4)

/* lane 0 */
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_0	(0x1000 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_1	(0x1001 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_2	(0x1002 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_3	(0x1003 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_4	(0x1004 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_5	(0x1005 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_6	(0x1006 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_7	(0x1007 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE0_OVR_0_8	(0x1008 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_9	(0x1009 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_10	(0x100a * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_11	(0x100b * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_12	(0x100c * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_13	(0x100d * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_14	(0x100e * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE0_OVR_0_15	(0x100f * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_0	(0x1010 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_1	(0x1011 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_2	(0x1012 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_3	(0x1013 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_4	(0x1014 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_5	(0x1015 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_6	(0x1016 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_7	(0x1017 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_8	(0x1018 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_1_9	(0x1019 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_10	(0x101a * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_11	(0x101b * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_12	(0x101c * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_13	(0x101d * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_14	(0x101e * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_1_15	(0x101f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_0		(0x1020 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_1		(0x1021 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_2		(0x1022 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_3		(0x1023 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_4		(0x1024 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_5		(0x1025 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_6		(0x1026 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_7		(0x1027 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_8		(0x1028 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_9		(0x1029 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_10		(0x102a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_11		(0x102b * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_12		(0x102c * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_13		(0x102d * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_14		(0x102e * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_2_15		(0x102f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_0		(0x1030 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_1		(0x1031 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_2		(0x1032 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_3		(0x1033 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_4		(0x1034 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_5		(0x1035 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_6		(0x1036 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE0_CTRL_3_7		(0x1037 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_8		(0x1038 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_9		(0x1039 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_10		(0x103a * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_11		(0x103b * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_12		(0x103c * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_13		(0x103d * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_14		(0x103e * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_3_15		(0x103f * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_4_0		(0x1040 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_4_1		(0x1041 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_4_2		(0x1042 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_4_3		(0x1043 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE0_CTRL_4_4		(0x1044 * 4)

#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_5_0	(0x1050 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE0_OVR_5_1	(0x1051 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_5_2	(0x1052 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_5_3	(0x1053 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE0_OVR_5_4	(0x1054 * 4)

#define CORE_DIG_RW_TRIO0_0				(0x1080 * 4)
#define CORE_DIG_RW_TRIO0_1				(0x1081 * 4)
#define CORE_DIG_RW_TRIO0_2				(0x1082 * 4)

/* lane 1 */
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_0	(0x1200 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_1	(0x1201 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_2	(0x1202 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_3	(0x1203 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_4	(0x1204 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_5	(0x1205 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_6	(0x1206 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_7	(0x1207 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE1_OVR_0_8	(0x1208 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_9	(0x1209 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_10	(0x120a * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_11	(0x120b * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_12	(0x120c * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_13	(0x120d * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_14	(0x120e * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE1_OVR_0_15	(0x120f * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_0	(0x1210 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_1	(0x1211 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_2	(0x1212 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_3	(0x1213 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_4	(0x1214 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_5	(0x1215 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_6	(0x1216 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_7	(0x1217 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_8	(0x1218 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_1_9	(0x1219 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_10	(0x121a * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_11	(0x121b * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_12	(0x121c * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_13	(0x121d * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_14	(0x121e * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_1_15	(0x121f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_0		(0x1220 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_1		(0x1221 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_2		(0x1222 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_3		(0x1223 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_4		(0x1224 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_5		(0x1225 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_6		(0x1226 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_7		(0x1227 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_8		(0x1228 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_9		(0x1229 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_10		(0x122a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_11		(0x122b * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_12		(0x122c * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_13		(0x122d * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_14		(0x122e * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_2_15		(0x122f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_0		(0x1230 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_1		(0x1231 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_2		(0x1232 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_3		(0x1233 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_4		(0x1234 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_5		(0x1235 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_6		(0x1236 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE1_CTRL_3_7		(0x1237 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_8		(0x1238 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_9		(0x1239 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_10		(0x123a * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_11		(0x123b * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_12		(0x123c * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_13		(0x123d * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_14		(0x123e * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_3_15		(0x123f * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_4_0		(0x1240 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_4_1		(0x1241 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_4_2		(0x1242 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_4_3		(0x1243 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE1_CTRL_4_4		(0x1244 * 4)

#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_5_0	(0x1250 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE1_OVR_5_1	(0x1251 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_5_2	(0x1252 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_5_3	(0x1253 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE1_OVR_5_4	(0x1254 * 4)

#define CORE_DIG_RW_TRIO1_0				(0x1280 * 4)
#define CORE_DIG_RW_TRIO1_1				(0x1281 * 4)
#define CORE_DIG_RW_TRIO1_2				(0x1282 * 4)

/* lane 2 */
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_0	(0x1400 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_1	(0x1401 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_2	(0x1402 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_3	(0x1403 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_4	(0x1404 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_5	(0x1405 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_6	(0x1406 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_7	(0x1407 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE2_OVR_0_8	(0x1408 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_9	(0x1409 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_10	(0x140a * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_11	(0x140b * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_12	(0x140c * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_13	(0x140d * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_14	(0x140e * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE2_OVR_0_15	(0x140f * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_0	(0x1410 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_1	(0x1411 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_2	(0x1412 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_3	(0x1413 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_4	(0x1414 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_5	(0x1415 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_6	(0x1416 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_7	(0x1417 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_8	(0x1418 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_1_9	(0x1419 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_10	(0x141a * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_11	(0x141b * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_12	(0x141c * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_13	(0x141d * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_14	(0x141e * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_1_15	(0x141f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_0		(0x1420 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_1		(0x1421 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_2		(0x1422 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_3		(0x1423 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_4		(0x1424 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_5		(0x1425 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_6		(0x1426 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_7		(0x1427 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_8		(0x1428 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_9		(0x1429 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_10		(0x142a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_11		(0x142b * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_12		(0x142c * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_13		(0x142d * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_14		(0x142e * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_2_15		(0x142f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_0		(0x1430 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_1		(0x1431 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_2		(0x1432 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_3		(0x1433 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_4		(0x1434 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_5		(0x1435 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_6		(0x1436 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE2_CTRL_3_7		(0x1437 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_8		(0x1438 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_9		(0x1439 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_10		(0x143a * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_11		(0x143b * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_12		(0x143c * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_13		(0x143d * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_14		(0x143e * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_3_15		(0x143f * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_4_0		(0x1440 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_4_1		(0x1441 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_4_2		(0x1442 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_4_3		(0x1443 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE2_CTRL_4_4		(0x1444 * 4)

#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_5_0	(0x1450 * 4)
#define CORE_DIG_IOCTRL_R_CPHY_PPI_LANE2_OVR_5_1	(0x1451 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_5_2	(0x1452 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_5_3	(0x1453 * 4)
#define CORE_DIG_IOCTRL_RW_CPHY_PPI_LANE2_OVR_5_4	(0x1454 * 4)

#define CORE_DIG_RW_TRIO2_0				(0x1480 * 4)
#define CORE_DIG_RW_TRIO2_1				(0x1481 * 4)
#define CORE_DIG_RW_TRIO2_2				(0x1482 * 4)

/* lane 3 */
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_0	(0x1600 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_1	(0x1601 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_2	(0x1602 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_3	(0x1603 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_4	(0x1604 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_5	(0x1605 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_6	(0x1606 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_7	(0x1607 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_LANE3_OVR_0_8	(0x1608 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_9	(0x1609 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_10	(0x160a * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_11	(0x160b * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_12	(0x160c * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_13	(0x160d * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_14	(0x160e * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_LANE3_OVR_0_15	(0x160f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_0		(0x1620 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_1		(0x1621 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_2		(0x1622 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_3		(0x1623 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_4		(0x1624 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_5		(0x1625 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_6		(0x1626 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_7		(0x1627 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_8		(0x1628 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_9		(0x1629 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_10		(0x162a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_11		(0x162b * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_12		(0x162c * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_13		(0x162d * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_14		(0x162e * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_2_15		(0x162f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_0		(0x1630 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_1		(0x1631 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_2		(0x1632 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_3		(0x1633 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_4		(0x1634 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_5		(0x1635 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_6		(0x1636 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE3_CTRL_3_7		(0x1637 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_8		(0x1638 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_9		(0x1639 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_10		(0x163a * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_11		(0x163b * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_12		(0x163c * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_13		(0x163d * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_14		(0x163e * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_3_15		(0x163f * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_4_0		(0x1640 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_4_1		(0x1641 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_4_2		(0x1642 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_4_3		(0x1643 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE3_CTRL_4_4		(0x1644 * 4)

/* lane 4 */
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_0		(0x1820 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_1		(0x1821 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_2		(0x1822 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_3		(0x1823 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_4		(0x1824 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_5		(0x1825 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_6		(0x1826 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_7		(0x1827 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_8		(0x1828 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_9		(0x1829 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_10		(0x182a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_11		(0x182b * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_12		(0x182c * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_13		(0x182d * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_14		(0x182e * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_2_15		(0x182f * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_0		(0x1830 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_1		(0x1831 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_2		(0x1832 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_3		(0x1833 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_4		(0x1834 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_5		(0x1835 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_6		(0x1836 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_LANE4_CTRL_3_7		(0x1837 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_8		(0x1838 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_9		(0x1839 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_10		(0x183a * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_11		(0x183b * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_12		(0x183c * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_13		(0x183d * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_14		(0x183e * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_3_15		(0x183f * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_4_0		(0x1840 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_4_1		(0x1841 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_4_2		(0x1842 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_4_3		(0x1843 * 4)
#define CORE_DIG_IOCTRL_R_AFE_LANE4_CTRL_4_4		(0x1844 * 4)

#define CORE_DIG_IOCTRL_RW_DPHY_PPI_CLK_OVR_0_0		(0x1a00 * 4)
#define CORE_DIG_IOCTRL_RW_DPHY_PPI_CLK_OVR_0_1		(0x1a01 * 4)
#define CORE_DIG_IOCTRL_R_DPHY_PPI_CLK_OVR_0_2		(0x1a02 * 4)

#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_0		(0x1c00 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_1		(0x1c01 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_2		(0x1c02 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_3		(0x1c03 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_4		(0x1c04 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_5		(0x1c05 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_6		(0x1c06 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_7		(0x1c07 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_8		(0x1c08 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_9		(0x1c09 * 4)
#define CORE_DIG_IOCTRL_RW_COMMON_PPI_OVR_0_10		(0x1c0a * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_0_11		(0x1c0b * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_0_12		(0x1c0c * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_0_13		(0x1c0d * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_0_14		(0x1c0e * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_0_15		(0x1c0f * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_1_0		(0x1c10 * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_1_1		(0x1c11 * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_1_2		(0x1c12 * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_1_3		(0x1c13 * 4)
#define CORE_DIG_IOCTRL_R_COMMON_PPI_OVR_1_4		(0x1c14 * 4)

#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_0		(0x1c20 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_1		(0x1c21 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_2		(0x1c22 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_3		(0x1c23 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_4		(0x1c24 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_5		(0x1c25 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_6		(0x1c26 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_7		(0x1c27 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_8		(0x1c28 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_9		(0x1c29 * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_10		(0x1c2a * 4)
#define CORE_DIG_IOCTRL_RW_AFE_CB_CTRL_2_11		(0x1c2b * 4)
#define CORE_DIG_IOCTRL_R_AFE_CB_CTRL_2_12		(0x1c2c * 4)
#define CORE_DIG_IOCTRL_R_AFE_CB_CTRL_2_13		(0x1c2d * 4)
#define CORE_DIG_IOCTRL_R_AFE_CB_CTRL_2_14		(0x1c2e * 4)
#define CORE_DIG_IOCTRL_R_AFE_CB_CTRL_2_15		(0x1c2f * 4)

#define CORE_DIG_IOCTRL_R_AFE_CB_CTRL_3_0		(0x1c30 * 4)

/* Telmo */
#define CORE_DIG_RW_COMMON_0				(0x1c40 * 4)
#define CORE_DIG_RW_COMMON_1				(0x1c41 * 4)
#define CORE_DIG_RW_COMMON_2				(0x1c42 * 4)
#define CORE_DIG_RW_COMMON_3				(0x1c43 * 4)
#define CORE_DIG_RW_COMMON_4				(0x1c44 * 4)
#define CORE_DIG_RW_COMMON_5				(0x1c45 * 4)
#define CORE_DIG_RW_COMMON_6				(0x1c46 * 4)
#define CORE_DIG_RW_COMMON_7				(0x1c47 * 4)
#define CORE_DIG_RW_COMMON_8				(0x1c48 * 4)
#define CORE_DIG_RW_COMMON_9				(0x1c49 * 4)
#define CORE_DIG_RW_COMMON_10				(0x1c4a * 4)
#define CORE_DIG_RW_COMMON_11				(0x1c4b * 4)
#define CORE_DIG_RW_COMMON_12				(0x1c4c * 4)
#define CORE_DIG_RW_COMMON_13				(0x1c4d * 4)
#define CORE_DIG_RW_COMMON_14				(0x1c4e * 4)
#define CORE_DIG_RW_COMMON_15				(0x1c4f * 4)

#define CORE_DIG_ANACTRL_RW_COMMON_ANACTRL_0		(0x1cf0 * 4)
#define CORE_DIG_ANACTRL_RW_COMMON_ANACTRL_1		(0x1cf1 * 4)
#define CORE_DIG_ANACTRL_RW_COMMON_ANACTRL_2		(0x1cf2 * 4)
#define CORE_DIG_ANACTRL_RW_COMMON_ANACTRL_3		(0x1cf3 * 4)

#define CORE_DIG_COMMON_RW_DESKEW_FINE_MEM		(0x1ff0 * 4)
#define CORE_DIG_COMMON_R_DESKEW_FINE_MEM		(0x1ff1 * 4)

/* lane 0 */
#define PPI_RW_DPHY_LANE0_LBERT_0			(0x2000 * 4)
#define PPI_RW_DPHY_LANE0_LBERT_1			(0x2001 * 4)
#define PPI_R_DPHY_LANE0_LBERT_0			(0x2002 * 4)
#define PPI_R_DPHY_LANE0_LBERT_1			(0x2003 * 4)
#define PPI_RW_DPHY_LANE0_SPARE				(0x2004 * 4)

/* lane 1 */
#define PPI_RW_DPHY_LANE1_LBERT_0			(0x2200 * 4)
#define PPI_RW_DPHY_LANE1_LBERT_1			(0x2201 * 4)
#define PPI_R_DPHY_LANE1_LBERT_0			(0x2202 * 4)
#define PPI_R_DPHY_LANE1_LBERT_1			(0x2203 * 4)
#define PPI_RW_DPHY_LANE1_SPARE				(0x2204 * 4)

/* lane 2 */
#define PPI_RW_DPHY_LANE2_LBERT_0			(0x2400 * 4)
#define PPI_RW_DPHY_LANE2_LBERT_1			(0x2401 * 4)
#define PPI_R_DPHY_LANE2_LBERT_0			(0x2402 * 4)
#define PPI_R_DPHY_LANE2_LBERT_1			(0x2403 * 4)
#define PPI_RW_DPHY_LANE2_SPARE				(0x2404 * 4)

/* lane 3 */
#define PPI_RW_DPHY_LANE3_LBERT_0			(0x2600 * 4)
#define PPI_RW_DPHY_LANE3_LBERT_1			(0x2601 * 4)
#define PPI_R_DPHY_LANE3_LBERT_0			(0x2602 * 4)
#define PPI_R_DPHY_LANE3_LBERT_1			(0x2603 * 4)
#define PPI_RW_DPHY_LANE3_SPARE				(0x2604 * 4)

/* lane 0 */
#define CORE_DIG_DLANE_0_RW_CFG_0			(0x3000 * 4)
#define CORE_DIG_DLANE_0_RW_CFG_1			(0x3001 * 4)
#define CORE_DIG_DLANE_0_RW_CFG_2			(0x3002 * 4)
#define CORE_DIG_DLANE_0_RW_LP_0			(0x3040 * 4)
#define CORE_DIG_DLANE_0_RW_LP_1			(0x3041 * 4)
#define CORE_DIG_DLANE_0_RW_LP_2			(0x3042 * 4)
#define CORE_DIG_DLANE_0_R_LP_0				(0x3050 * 4)
#define CORE_DIG_DLANE_0_R_LP_1				(0x3051 * 4)
#define CORE_DIG_DLANE_0_R_HS_TX_0			(0x3070 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_0			(0x3080 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_1			(0x3081 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_2			(0x3082 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_3			(0x3083 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_4			(0x3084 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_5			(0x3085 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_6			(0x3086 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_7			(0x3087 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_8			(0x3088 * 4)
#define CORE_DIG_DLANE_0_RW_HS_RX_9			(0x3089 * 4)
#define CORE_DIG_DLANE_0_R_HS_RX_0			(0x3090 * 4)
#define CORE_DIG_DLANE_0_R_HS_RX_1			(0x3091 * 4)
#define CORE_DIG_DLANE_0_R_HS_RX_2			(0x3092 * 4)
#define CORE_DIG_DLANE_0_R_HS_RX_3			(0x3093 * 4)
#define CORE_DIG_DLANE_0_R_HS_RX_4			(0x3094 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_0			(0x3100 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_1			(0x3101 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_2			(0x3102 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_3			(0x3103 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_4			(0x3104 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_5			(0x3105 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_6			(0x3106 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_7			(0x3107 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_8			(0x3108 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_9			(0x3109 * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_10			(0x310a * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_11			(0x310b * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_12			(0x310c * 4)
#define CORE_DIG_DLANE_0_RW_HS_TX_13			(0x310d * 4)

/* lane 1 */
#define CORE_DIG_DLANE_1_RW_CFG_0			(0x3200 * 4)
#define CORE_DIG_DLANE_1_RW_CFG_1			(0x3201 * 4)
#define CORE_DIG_DLANE_1_RW_CFG_2			(0x3202 * 4)
#define CORE_DIG_DLANE_1_RW_LP_0			(0x3240 * 4)
#define CORE_DIG_DLANE_1_RW_LP_1			(0x3241 * 4)
#define CORE_DIG_DLANE_1_RW_LP_2			(0x3242 * 4)
#define CORE_DIG_DLANE_1_R_LP_0				(0x3250 * 4)
#define CORE_DIG_DLANE_1_R_LP_1				(0x3251 * 4)
#define CORE_DIG_DLANE_1_R_HS_TX_0			(0x3270 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_0			(0x3280 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_1			(0x3281 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_2			(0x3282 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_3			(0x3283 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_4			(0x3284 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_5			(0x3285 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_6			(0x3286 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_7			(0x3287 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_8			(0x3288 * 4)
#define CORE_DIG_DLANE_1_RW_HS_RX_9			(0x3289 * 4)
#define CORE_DIG_DLANE_1_R_HS_RX_0			(0x3290 * 4)
#define CORE_DIG_DLANE_1_R_HS_RX_1			(0x3291 * 4)
#define CORE_DIG_DLANE_1_R_HS_RX_2			(0x3292 * 4)
#define CORE_DIG_DLANE_1_R_HS_RX_3			(0x3293 * 4)
#define CORE_DIG_DLANE_1_R_HS_RX_4			(0x3294 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_0			(0x3300 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_1			(0x3301 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_2			(0x3302 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_3			(0x3303 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_4			(0x3304 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_5			(0x3305 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_6			(0x3306 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_7			(0x3307 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_8			(0x3308 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_9			(0x3309 * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_10			(0x330a * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_11			(0x330b * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_12			(0x330c * 4)
#define CORE_DIG_DLANE_1_RW_HS_TX_13			(0x330d * 4)

/* lane 2 */
#define CORE_DIG_DLANE_2_RW_CFG_0			(0x3400 * 4)
#define CORE_DIG_DLANE_2_RW_CFG_1			(0x3401 * 4)
#define CORE_DIG_DLANE_2_RW_CFG_2			(0x3402 * 4)
#define CORE_DIG_DLANE_2_RW_LP_0			(0x3440 * 4)
#define CORE_DIG_DLANE_2_RW_LP_1			(0x3441 * 4)
#define CORE_DIG_DLANE_2_RW_LP_2			(0x3442 * 4)
#define CORE_DIG_DLANE_2_R_LP_0				(0x3450 * 4)
#define CORE_DIG_DLANE_2_R_LP_1				(0x3451 * 4)
#define CORE_DIG_DLANE_2_R_HS_TX_0			(0x3470 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_0			(0x3480 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_1			(0x3481 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_2			(0x3482 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_3			(0x3483 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_4			(0x3484 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_5			(0x3485 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_6			(0x3486 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_7			(0x3487 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_8			(0x3488 * 4)
#define CORE_DIG_DLANE_2_RW_HS_RX_9			(0x3489 * 4)
#define CORE_DIG_DLANE_2_R_HS_RX_0			(0x3490 * 4)
#define CORE_DIG_DLANE_2_R_HS_RX_1			(0x3491 * 4)
#define CORE_DIG_DLANE_2_R_HS_RX_2			(0x3492 * 4)
#define CORE_DIG_DLANE_2_R_HS_RX_3			(0x3493 * 4)
#define CORE_DIG_DLANE_2_R_HS_RX_4			(0x3494 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_0			(0x3500 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_1			(0x3501 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_2			(0x3502 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_3			(0x3503 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_4			(0x3504 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_5			(0x3505 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_6			(0x3506 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_7			(0x3507 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_8			(0x3508 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_9			(0x3509 * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_10			(0x350a * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_11			(0x350b * 4)
#define CORE_DIG_DLANE_2_RW_HS_TX_12			(0x350c * 4)

/* lane 3 */
#define CORE_DIG_DLANE_3_RW_CFG_0			(0x3600 * 4)
#define CORE_DIG_DLANE_3_RW_CFG_1			(0x3601 * 4)
#define CORE_DIG_DLANE_3_RW_CFG_2			(0x3602 * 4)
#define CORE_DIG_DLANE_3_RW_LP_0			(0x3640 * 4)
#define CORE_DIG_DLANE_3_RW_LP_1			(0x3641 * 4)
#define CORE_DIG_DLANE_3_RW_LP_2			(0x3642 * 4)
#define CORE_DIG_DLANE_3_R_LP_0				(0x3650 * 4)
#define CORE_DIG_DLANE_3_R_LP_1				(0x3651 * 4)
#define CORE_DIG_DLANE_3_R_HS_TX_0			(0x3670 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_0			(0x3680 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_1			(0x3681 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_2			(0x3682 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_3			(0x3683 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_4			(0x3684 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_5			(0x3685 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_6			(0x3686 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_7			(0x3687 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_8			(0x3688 * 4)
#define CORE_DIG_DLANE_3_RW_HS_RX_9			(0x3689 * 4)
#define CORE_DIG_DLANE_3_R_HS_RX_0			(0x3690 * 4)
#define CORE_DIG_DLANE_3_R_HS_RX_1			(0x3691 * 4)
#define CORE_DIG_DLANE_3_R_HS_RX_2			(0x3692 * 4)
#define CORE_DIG_DLANE_3_R_HS_RX_3			(0x3693 * 4)
#define CORE_DIG_DLANE_3_R_HS_RX_4			(0x3694 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_0			(0x3700 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_1			(0x3701 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_2			(0x3702 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_3			(0x3703 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_4			(0x3704 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_5			(0x3705 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_6			(0x3706 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_7			(0x3707 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_8			(0x3708 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_9			(0x3709 * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_10			(0x370a * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_11			(0x370b * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_12			(0x370c * 4)
#define CORE_DIG_DLANE_3_RW_HS_TX_13			(0x370d * 4)

#define CORE_DIG_DLANE_CLK_RW_CFG_0			(0x3800 * 4)
#define CORE_DIG_DLANE_CLK_RW_CFG_1			(0x3801 * 4)
#define CORE_DIG_DLANE_CLK_RW_CFG_2			(0x3802 * 4)

#define CORE_DIG_DLANE_CLK_RW_LP_0			(0x3840 * 4)
#define CORE_DIG_DLANE_CLK_RW_LP_1			(0x3841 * 4)
#define CORE_DIG_DLANE_CLK_RW_LP_2			(0x3842 * 4)
#define CORE_DIG_DLANE_CLK_R_LP_0			(0x3850 * 4)
#define CORE_DIG_DLANE_CLK_R_LP_1			(0x3851 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_TX_0			(0x3870 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_0			(0x3880 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_1			(0x3881 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_2			(0x3882 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_3			(0x3883 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_4			(0x3884 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_5			(0x3885 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_6			(0x3886 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_7			(0x3887 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_8			(0x3888 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_RX_9			(0x3889 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_RX_0			(0x3890 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_RX_1			(0x3891 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_RX_2			(0x3892 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_RX_3			(0x3893 * 4)
#define CORE_DIG_DLANE_CLK_R_HS_RX_4			(0x3894 * 4)

#define CORE_DIG_DLANE_CLK_RW_HS_TX_0			(0x3900 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_1			(0x3901 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_2			(0x3902 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_3			(0x3903 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_4			(0x3904 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_5			(0x3905 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_6			(0x3906 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_8			(0x3908 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_9			(0x3909 * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_10			(0x390a * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_12			(0x390c * 4)
#define CORE_DIG_DLANE_CLK_RW_HS_TX_13			(0x390d * 4)

/* trio0 */
#define PPI_RW_CPHY_TRIO0_LBERT_0			(0x4000 * 4)
#define PPI_RW_CPHY_TRIO0_LBERT_1			(0x4001 * 4)
#define PPI_R_CPHY_TRIO0_LBERT_0			(0x4002 * 4)
#define PPI_R_CPHY_TRIO0_LBERT_1			(0x4003 * 4)
#define PPI_RW_CPHY_TRIO0_SPARE				(0x4004 * 4)

/* trio1 */
#define PPI_RW_CPHY_TRIO1_LBERT_0			(0x4200 * 4)
#define PPI_RW_CPHY_TRIO1_LBERT_1			(0x4201 * 4)
#define PPI_R_CPHY_TRIO1_LBERT_0			(0x4202 * 4)
#define PPI_R_CPHY_TRIO1_LBERT_1			(0x4203 * 4)
#define PPI_RW_CPHY_TRIO1_SPARE				(0x4204 * 4)

/* trio2 */
#define PPI_RW_CPHY_TRIO2_LBERT_0			(0x4400 * 4)
#define PPI_RW_CPHY_TRIO2_LBERT_1			(0x4401 * 4)
#define PPI_R_CPHY_TRIO2_LBERT_0			(0x4402 * 4)
#define PPI_R_CPHY_TRIO2_LBERT_1			(0x4403 * 4)
#define PPI_RW_CPHY_TRIO2_SPARE				(0x4404 * 4)

/* clane0 */
#define CORE_DIG_CLANE_0_RW_CFG_0			(0x5000 * 4)
#define CORE_DIG_CLANE_0_RW_CFG_2			(0x5002 * 4)
#define CORE_DIG_CLANE_0_RW_LP_0			(0x5040 * 4)
#define CORE_DIG_CLANE_0_RW_LP_1			(0x5041 * 4)
#define CORE_DIG_CLANE_0_RW_LP_2			(0x5042 * 4)
#define CORE_DIG_CLANE_0_R_LP_0				(0x5050 * 4)
#define CORE_DIG_CLANE_0_R_LP_1				(0x5051 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_0			(0x5080 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_1			(0x5081 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_2			(0x5082 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_3			(0x5083 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_4			(0x5084 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_5			(0x5085 * 4)
#define CORE_DIG_CLANE_0_RW_HS_RX_6			(0x5086 * 4)
#define CORE_DIG_CLANE_0_R_RX_0				(0x5090 * 4)
#define CORE_DIG_CLANE_0_R_RX_1				(0x5091 * 4)
#define CORE_DIG_CLANE_0_R_TX_0				(0x5092 * 4)
#define CORE_DIG_CLANE_0_R_RX_2				(0x5093 * 4)
#define CORE_DIG_CLANE_0_R_RX_3				(0x5094 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_0			(0x5100 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_1			(0x5101 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_2			(0x5102 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_3			(0x5103 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_4			(0x5104 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_5			(0x5105 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_6			(0x5106 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_7			(0x5107 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_8			(0x5108 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_9			(0x5109 * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_10			(0x510a * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_11			(0x510b * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_12			(0x510c * 4)
#define CORE_DIG_CLANE_0_RW_HS_TX_13			(0x510d * 4)

/* clane1 */
#define CORE_DIG_CLANE_1_RW_CFG_0			(0x5200 * 4)
#define CORE_DIG_CLANE_1_RW_CFG_2			(0x5202 * 4)
#define CORE_DIG_CLANE_1_RW_LP_0			(0x5240 * 4)
#define CORE_DIG_CLANE_1_RW_LP_1			(0x5241 * 4)
#define CORE_DIG_CLANE_1_RW_LP_2			(0x5242 * 4)
#define CORE_DIG_CLANE_1_R_LP_0				(0x5250 * 4)
#define CORE_DIG_CLANE_1_R_LP_1				(0x5251 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_0			(0x5280 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_1			(0x5281 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_2			(0x5282 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_3			(0x5283 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_4			(0x5284 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_5			(0x5285 * 4)
#define CORE_DIG_CLANE_1_RW_HS_RX_6			(0x5286 * 4)
#define CORE_DIG_CLANE_1_R_RX_0				(0x5290 * 4)
#define CORE_DIG_CLANE_1_R_RX_1				(0x5291 * 4)
#define CORE_DIG_CLANE_1_R_TX_0				(0x5292 * 4)
#define CORE_DIG_CLANE_1_R_RX_2				(0x5293 * 4)
#define CORE_DIG_CLANE_1_R_RX_3				(0x5294 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_0			(0x5300 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_1			(0x5301 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_2			(0x5302 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_3			(0x5303 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_4			(0x5304 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_5			(0x5305 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_6			(0x5306 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_7			(0x5307 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_8			(0x5308 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_9			(0x5309 * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_10			(0x530a * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_11			(0x530b * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_12			(0x530c * 4)
#define CORE_DIG_CLANE_1_RW_HS_TX_13			(0x530d * 4)

/* clane2 */
#define CORE_DIG_CLANE_2_RW_CFG_0			(0x5400 * 4)
#define CORE_DIG_CLANE_2_RW_CFG_2			(0x5402 * 4)
#define CORE_DIG_CLANE_2_RW_LP_0			(0x5440 * 4)
#define CORE_DIG_CLANE_2_RW_LP_1			(0x5441 * 4)
#define CORE_DIG_CLANE_2_R_LP_0				(0x5450 * 4)
#define CORE_DIG_CLANE_2_R_LP_1				(0x5451 * 4)
#define CORE_DIG_CLANE_2_R_LP_2				(0x5452 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_0			(0x5480 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_1			(0x5481 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_2			(0x5482 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_3			(0x5483 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_4			(0x5484 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_5			(0x5485 * 4)
#define CORE_DIG_CLANE_2_RW_HS_RX_6			(0x5486 * 4)
#define CORE_DIG_CLANE_2_R_RX_0				(0x5490 * 4)
#define CORE_DIG_CLANE_2_R_RX_1				(0x5491 * 4)
#define CORE_DIG_CLANE_2_R_TX_0				(0x5492 * 4)
#define CORE_DIG_CLANE_2_R_RX_2				(0x5493 * 4)
#define CORE_DIG_CLANE_2_R_RX_3				(0x5494 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_0			(0x5500 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_1			(0x5501 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_2			(0x5502 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_3			(0x5503 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_4			(0x5504 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_5			(0x5505 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_6			(0x5506 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_7			(0x5507 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_8			(0x5508 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_9			(0x5509 * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_10			(0x550a * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_11			(0x550b * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_12			(0x550c * 4)
#define CORE_DIG_CLANE_2_RW_HS_TX_13			(0x550d * 4)

#define PLL_CFG0					0x0
#define PLL_CFG1					0x4
#define PLL_CFG2					0x8
#define PLL_CFG3					0xc
#define PLL_CFG4					0x10
#define PLL_CFG5					0x14
#define PLL_CFG6					0x18
#define PLL_CFG7					0x1c
#define PLL_CP						0x20
#define PHY_STS						0x24
#define PHY_CTRL0					0x28
#define PHY_EXTENDED_CTRL0				0x2c
#define PHY_EXTENDED_CTRL1				0x30
#define PHY_TEST_STS					0x34
#define PHY_TXALP_0					0x38
#define PHY_TXALP_1					0x40
#define PHY_TXALP_2					0x44
#define PHY_SYNCTYPE					0x48
#define PHY_ERROR_STS					0x4c

#define PHY_READY					BIT(0)
#define PLL_LOCK					BIT(1)

struct dw_cdphy_hs_configuration {
	u32 datarate; /* Mbps */

	/* data rate dependent register values */
	union {
		struct dphy_hs_regs dphy_regs;
		struct cphy_hs_regs cphy_regs;
	};
	struct pll_config pll_config;
};

#define INVALID_PRESET_VAL 0xFFFFFFFF
enum dw_cdphy_preset_apply_timing {
	DPHY_PRESET_APPLY_BEFORE_RST = 0,
	DPHY_PRESET_APPLY_AFTER_READY = 1,
};

struct dw_cdphy_preset_item {
	struct list_head list;
	const char *name;
	struct regmap_field *regmap_field;
	enum dw_cdphy_preset_apply_timing apply_timing;
	u32 val;
};

struct dw_mipi_cdphy_g301 {
	struct dw_mipi_cdphy *cdphy;

	void __iomem *base;
	struct regmap *base_regs;
	u32 tx_reg_size;

	void __iomem *u0_apb_regbank;
	struct regmap *u0_apb_regbank_regs;
	u32 u0_apb_reg_size;

	struct dw_cdphy_hs_configuration hs_config;
	struct list_head preset_list;

	/* dwc_mipi_cdphy_tx_4l3t_ns */
	struct regmap_field	*field_ppi_startup_rw_common_dphy_2_rcal_addr;
	struct regmap_field	*field_ppi_startup_rw_common_dphy_3_pll_start_addr;
	struct regmap_field	*field_ppi_startup_rw_common_dphy_6_lp_dco_cal_addr;
	struct regmap_field	*field_ppi_startup_rw_common_dphy_a_hibernate_addr;
	struct regmap_field	*field_ppi_startup_rw_common_dphy_10_phy_ready_addr;
	struct regmap_field	*field_ppi_startup_rw_common_startup_1_1_phy_ready_dly;
	struct regmap_field	*field_ppi_calibctrl_rw_common_bg_0_bg_max_counter;
	struct regmap_field	*field_ppi_rw_lpdcocal_timebase_lpcdcocal_timebase;
	struct regmap_field	*field_ppi_rw_lpdcocal_nref_lpcdcocal_nref;
	struct regmap_field	*field_ppi_rw_lpdcocal_nref_range_lpcdcocal_nref_range;
	struct regmap_field	*field_ppi_rw_lpdcocal_twait_config_lpcdcocal_twait_coarse;
	struct regmap_field	*field_ppi_rw_lpdcocal_twait_config_lpcdcocal_twait_pon;
	struct regmap_field	*field_ppi_rw_lpdcocal_vt_config_lpcdcocal_vt_tracking_en;
	struct regmap_field	*field_ppi_rw_lpdcocal_vt_config_lpcdcocal_use_ideal_nref;
	struct regmap_field	*field_ppi_rw_lpdcocal_vt_config_lpcdcocal_vt_nref_range;
	struct regmap_field	*field_ppi_rw_lpdcocal_vt_config_lpcdcocal_twait_fine;
	struct regmap_field	*field_ppi_rw_lpdcocal_coarse_cfg_ncoarse_start;
	struct regmap_field	*field_ppi_rw_common_cfg_cfg_clk_div_factor;
	struct regmap_field	*field_ppi_rw_termcal_cfg_0_termcal_timer;
	struct regmap_field	*field_ppi_rw_pll_startup_cfg_0_pll_rst_time;
	struct regmap_field	*field_ppi_rw_pll_startup_cfg_1_pll_gear_shift_time;
	struct regmap_field	*field_ppi_rw_pll_startup_cfg_2_pll_lock_det_time;
	struct regmap_field	*field_ppi_rw_tx_hibernate_cfg_0_hibernate_exit;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane0_ctrl_2_2_oa_lane0_sel_lane_cfg;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_sel_phase0;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_eqa;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_sel_clklb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane0_ctrl_2_4_oa_lane0_hstx_eqb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane1_ctrl_2_2_oa_lane1_sel_lane_cfg;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_sel_phase0;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_eqa;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_sel_clklb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane1_ctrl_2_4_oa_lane1_hstx_eqb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_2_oa_lane2_sel_lane_cfg;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_sel_phase0;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_eqa;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_sel_clklb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_4_oa_lane2_hstx_eqb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_7_oa_lane2_lprx_lp_pon_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_7_oa_lane2_lprx_cd_pon_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_8_oa_lane2_lprx_lp_pon_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane2_ctrl_2_8_oa_lane2_lprx_cd_pon_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane3_ctrl_2_2_oa_lane3_sel_lane_cfg;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_sel_phase0;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_eqa;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_sel_clklb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane3_ctrl_2_4_oa_lane3_hstx_eqb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane4_ctrl_2_2_oa_lane4_sel_lane_cfg;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_sel_phase0;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_eqa;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_sel_clklb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_lane4_ctrl_2_4_oa_lane4_hstx_eqb;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_0_oa_cb_hstxlb_dco_clk90_en_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_1_oa_cb_hstxlb_dco_clk0_en_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_2_oa_cb_pll_bustiez;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_3_oa_cb_hstxlb_dco_clk0_en_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_3_oa_cb_hstxlb_dco_clk90_en_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_4_oa_cb_sel_vcomm_prog;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_4_oa_cb_cal_sink_en_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_5_oa_cb_sel_45ohm_50ohm;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_5_oa_cb_cal_sink_en_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_pon_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_en_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_tune_clkdig_en_ovr_en;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_7_oa_cb_hstxlb_dco_en_ovr_val;
	struct regmap_field	*field_core_dig_ioctrl_rw_afe_cb_ctrl_2_7_oa_cb_hstxlb_dco_tune_clkdig_en_ovr_val;
	struct regmap_field	*field_core_dig_anactrl_rw_common_anactrl_0_cb_lp_dco_en_dly;
	struct regmap_field	*field_core_dig_anactrl_rw_common_anactrl_2_global_ulps_ovr_en;
	struct regmap_field	*field_core_dig_anactrl_rw_common_anactrl_2_global_ulps_ovr_val;
	struct regmap_field	*field_core_dig_dlane_clk_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_lp_2_lp_2_filter_input_sampling_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_cfg_0_cfg_0_lp_pin_swap_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_cfg_0_cfg_0_hs_pin_swap_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_3_hs_tx_3_pin_swap_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_lp_2_lp_2_filter_input_sampling_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_1_hs_tx_1_thszero_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_dlane_0_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_lp_2_lp_2_filter_input_sampling_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_1_hs_tx_1_thszero_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_dlane_1_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_lp_2_lp_2_filter_input_sampling_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_1_hs_tx_1_thszero_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_dlane_2_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_lp_2_lp_2_filter_input_sampling_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_1_hs_tx_1_thszero_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_dlane_3_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_1_hs_tx_1_thszero_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_2_hs_tx_2_tclkpre_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_8_hs_tx_8_tclkpost_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_dlane_clk_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_1_hs_tx_1_tpost_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_clane_0_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_cfg_0_cfg_0_lp_pin_swap_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_pin_swap_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_1_hs_tx_1_tpost_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_clane_1_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_lp_0_lp_0_ttago_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_lp_0_lp_0_itminrx_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_1_hs_tx_1_tpost_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	struct regmap_field	*field_core_dig_clane_2_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;

	struct regmap_field	*field_core_dig_ioctrl_r_common_ppi_ovr_0_12_phy_state;

	/* Telmo */
	struct regmap_field	*field_core_dig_rw_common_1_ocla_data_sel;
	struct regmap_field	*field_core_dig_rw_common_3_ocla_clk_sel;
	struct regmap_field *field_ppi_rw_hstx_fifo_cfg_txdatatransferenhs_sel;

	/* Unexpected LP data transmission on lane 2 fix */
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane1_ovr_0_3_i_txrequestesc_d1_ovr_val;
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane1_ovr_0_4_i_txrequestesc_d1_ovr_en;
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane2_ovr_0_3_i_txrequestesc_d2_ovr_val;
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane2_ovr_0_4_i_txrequestesc_d2_ovr_en;
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane3_ovr_0_3_i_txrequestesc_d3_ovr_val;
	struct regmap_field *field_core_dig_ioctrl_rw_dphy_ppi_lane3_ovr_0_4_i_txrequestesc_d3_ovr_en;

	/* ds_ss_dsi2host_abp_regbank */
	struct regmap_field	*field_pll_cfg0_rw_pll_atb_sense_sel;
	struct regmap_field	*field_pll_cfg0_rw_pll_clksel;
	struct regmap_field	*field_pll_cfg0_rw_pll_gp_clk_en;
	struct regmap_field	*field_pll_cfg0_rw_pll_opmode;
	struct regmap_field	*field_pll_cfg0_rw_pll_meas_iv;
	struct regmap_field	*field_pll_cfg0_rw_pll_clkouten_left;

	struct regmap_field	*field_pll_cfg1_rw_pll_prg_31_0;

	struct regmap_field	*field_pll_cfg2_rw_pll_prg_32;
	struct regmap_field	*field_pll_cfg2_rw_pll_th1;
	struct regmap_field	*field_pll_cfg2_rw_pll_th2;
	struct regmap_field	*field_pll_cfg2_rw_pll_th3;

	struct regmap_field	*field_pll_cfg3_rw_pll_mint;
	struct regmap_field	*field_pll_cfg3_rw_pll_m;
	struct regmap_field	*field_pll_cfg3_rw_pll_n;
	struct regmap_field	*field_pll_cfg3_rw_pll_fracn_cfg_update_en;
	struct regmap_field	*field_pll_cfg3_rw_pll_fracn_en;

	struct regmap_field	*field_pll_cfg4_rw_pll_frac_den;
	struct regmap_field	*field_pll_cfg5_rw_pll_stepsize;

	struct regmap_field	*field_pll_cfg6_rw_pll_ssc_en;
	struct regmap_field	*field_pll_cfg6_rw_pll_spread_type;
	struct regmap_field	*field_pll_cfg6_rw_pll_ssc_peak;

	struct regmap_field	*field_pll_cfg7_rw_pll_frac_quot;
	struct regmap_field	*field_pll_cfg7_rw_pll_frac_rem;

	struct regmap_field	*field_pll_cp_rw_pll_vco_cntrl_0_2;
	struct regmap_field	*field_pll_cp_rw_pll_vco_cntrl_3_5;
	struct regmap_field	*field_pll_cp_rw_pll_prop_cntrl;
	struct regmap_field	*field_pll_cp_rw_pll_int_cntrl;
	struct regmap_field	*field_pll_cp_rw_pll_gmp_cntrl;
	struct regmap_field	*field_pll_cp_rw_pll_cpbias_cntrl;

	struct regmap_field	*field_phy_sts_r_phy_ready;
	struct regmap_field	*field_phy_sts_r_pll_lock;
	struct regmap_field	*field_phy_sts_r_pll_vpl_det;

	struct regmap_field	*field_phy_ctrl0_rw_phy_rst_n;
	struct regmap_field	*field_phy_ctrl0_rw_shutdown_n;
	struct regmap_field	*field_phy_ctrl0_rw_phy_mode;
	struct regmap_field	*field_phy_ctrl0_rw_test_stop_clk_en;
	struct regmap_field	*field_phy_ctrl0_rw_bist_en;

	struct regmap_field	*field_phy_extended_ctr0_rw_forcerxmode_dck;
	struct regmap_field	*field_phy_extended_ctr0_rw_forcerxmode_0;
	struct regmap_field	*field_phy_extended_ctr0_rw_forcerxmode_1;
	struct regmap_field	*field_phy_extended_ctr0_rw_forcerxmode_2;
	struct regmap_field	*field_phy_extended_ctr0_rw_forcerxmode_3;
	struct regmap_field	*field_phy_extended_ctr0_rw_turndisable_0;
	struct regmap_field	*field_phy_extended_ctr0_rw_turndisable_1;
	struct regmap_field	*field_phy_extended_ctr0_rw_turndisable_2;
	struct regmap_field	*field_phy_extended_ctr0_rw_turndisable_3;

	struct regmap_field	*field_phy_extended_ctr1_rw_enable0;
	struct regmap_field	*field_phy_extended_ctr1_rw_enable1;
	struct regmap_field	*field_phy_extended_ctr1_rw_enable2;
	struct regmap_field	*field_phy_extended_ctr1_rw_enable3;
	struct regmap_field	*field_phy_extended_ctr1_rw_enable_dck;
	struct regmap_field	*field_phy_extended_ctr1_rw_enable_ov_en;
	struct regmap_field	*field_phy_extended_ctr1_rw_forcetxstopmode_dck;
	struct regmap_field	*field_phy_extended_ctr1_rw_forcetxstopmode_0;
	struct regmap_field	*field_phy_extended_ctr1_rw_forcetxstopmode_1;
	struct regmap_field	*field_phy_extended_ctr1_rw_forcetxstopmode_2;
	struct regmap_field	*field_phy_extended_ctr1_rw_forcetxstopmode_3;
	struct regmap_field	*field_phy_extended_ctr1_rw_txdatawidthhs_0;
	struct regmap_field	*field_phy_extended_ctr1_rw_txdatawidthhs_1;
	struct regmap_field	*field_phy_extended_ctr1_rw_txdatawidthhs_2;
	struct regmap_field	*field_phy_extended_ctr1_rw_txdatawidthhs_3;
	struct regmap_field	*field_phy_extended_ctr1_rw_cont_en;
	struct regmap_field	*field_phy_extended_ctr1_rw_cont_en_ov_en;

	struct regmap_field	*field_phy_common9_reg;
	struct regmap_field	*field_phy_startup_cfg3_reg;
};

struct dw_mipi_phy_g301_variant {
	/* dwc_mipi_cdphy_tx_4l3t_ns */
	const struct reg_field	cfg_ppi_startup_rw_common_dphy_2_rcal_addr;
	const struct reg_field	cfg_ppi_startup_rw_common_dphy_3_pll_start_addr;
	const struct reg_field	cfg_ppi_startup_rw_common_dphy_6_lp_dco_cal_addr;
	const struct reg_field	cfg_ppi_startup_rw_common_dphy_a_hibernate_addr;
	const struct reg_field	cfg_ppi_startup_rw_common_dphy_10_phy_ready_addr;
	const struct reg_field	cfg_ppi_startup_rw_common_startup_1_1_phy_ready_dly;
	const struct reg_field	cfg_ppi_calibctrl_rw_common_bg_0_bg_max_counter;
	const struct reg_field	cfg_ppi_rw_lpdcocal_timebase_lpcdcocal_timebase;
	const struct reg_field	cfg_ppi_rw_lpdcocal_nref_lpcdcocal_nref;
	const struct reg_field	cfg_ppi_rw_lpdcocal_nref_range_lpcdcocal_nref_range;
	const struct reg_field	cfg_ppi_rw_lpdcocal_twait_config_lpcdcocal_twait_coarse;
	const struct reg_field	cfg_ppi_rw_lpdcocal_twait_config_lpcdcocal_twait_pon;
	const struct reg_field	cfg_ppi_rw_lpdcocal_vt_config_lpcdcocal_vt_tracking_en;
	const struct reg_field	cfg_ppi_rw_lpdcocal_vt_config_lpcdcocal_use_ideal_nref;
	const struct reg_field	cfg_ppi_rw_lpdcocal_vt_config_lpcdcocal_vt_nref_range;
	const struct reg_field	cfg_ppi_rw_lpdcocal_vt_config_lpcdcocal_twait_fine;
	const struct reg_field	cfg_ppi_rw_lpdcocal_coarse_cfg_ncoarse_start;
	const struct reg_field	cfg_ppi_rw_common_cfg_cfg_clk_div_factor;
	const struct reg_field	cfg_ppi_rw_termcal_cfg_0_termcal_timer;
	const struct reg_field	cfg_ppi_rw_pll_startup_cfg_0_pll_rst_time;
	const struct reg_field	cfg_ppi_rw_pll_startup_cfg_1_pll_gear_shift_time;
	const struct reg_field	cfg_ppi_rw_pll_startup_cfg_2_pll_lock_det_time;
	const struct reg_field	cfg_ppi_rw_tx_hibernate_cfg_0_hibernate_exit;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane0_ctrl_2_2_oa_lane0_sel_lane_cfg;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_sel_phase0;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_eqa;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane0_ctrl_2_3_oa_lane0_hstx_sel_clklb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane0_ctrl_2_4_oa_lane0_hstx_eqb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane1_ctrl_2_2_oa_lane1_sel_lane_cfg;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_sel_phase0;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_eqa;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane1_ctrl_2_3_oa_lane1_hstx_sel_clklb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane1_ctrl_2_4_oa_lane1_hstx_eqb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_2_oa_lane2_sel_lane_cfg;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_sel_phase0;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_eqa;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_3_oa_lane2_hstx_sel_clklb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_4_oa_lane2_hstx_eqb;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_7_oa_lane2_lprx_lp_pon_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_7_oa_lane2_lprx_cd_pon_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_8_oa_lane2_lprx_lp_pon_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_lane2_ctrl_2_8_oa_lane2_lprx_cd_pon_ovr_val;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane3_ctrl_2_2_oa_lane3_sel_lane_cfg;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_sel_phase0;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_eqa;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane3_ctrl_2_3_oa_lane3_hstx_sel_clklb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane3_ctrl_2_4_oa_lane3_hstx_eqb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane4_ctrl_2_2_oa_lane4_sel_lane_cfg;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_eqa;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_sel_phase0;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane4_ctrl_2_4_oa_lane4_hstx_eqb;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_lane4_ctrl_2_3_oa_lane4_hstx_sel_clklb;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_0_oa_cb_hstxlb_dco_clk90_en_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_1_oa_cb_hstxlb_dco_clk0_en_ovr_val;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_2_oa_cb_pll_bustiez;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_3_oa_cb_hstxlb_dco_clk0_en_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_3_oa_cb_hstxlb_dco_clk90_en_ovr_en;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_4_oa_cb_sel_vcomm_prog;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_4_oa_cb_cal_sink_en_ovr_val;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_5_oa_cb_sel_45ohm_50ohm;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_5_oa_cb_cal_sink_en_ovr_en;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_pon_ovr_en;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_en_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_6_oa_cb_hstxlb_dco_tune_clkdig_en_ovr_en;
	const struct reg_field	cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_7_oa_cb_hstxlb_dco_en_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_afe_cb_ctrl_2_7_oa_cb_hstxlb_dco_tune_clkdig_en_ovr_val;
	const struct reg_field	cfg_core_dig_anactrl_rw_common_anactrl_0_cb_lp_dco_en_dly;
	const struct reg_field	cfg_core_dig_anactrl_rw_common_anactrl_2_global_ulps_ovr_en;
	const struct reg_field	cfg_core_dig_anactrl_rw_common_anactrl_2_global_ulps_ovr_val;
	const struct reg_field	cfg_core_dig_dlane_0_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_lp_2_lp_2_filter_input_sampling_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_lp_2_lp_2_filter_input_sampling_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_cfg_0_cfg_0_lp_pin_swap_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_cfg_0_cfg_0_hs_pin_swap_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_3_hs_tx_3_pin_swap_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_1_hs_tx_1_thszero_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_0_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_lp_2_lp_2_filter_input_sampling_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_1_hs_tx_1_thszero_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_1_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_lp_2_lp_2_filter_input_sampling_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_1_hs_tx_1_thszero_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_2_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_lp_2_lp_2_filter_input_sampling_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_1_hs_tx_1_thszero_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_3_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_0_hs_tx_0_thstrail_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_1_hs_tx_1_thszero_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_2_hs_tx_2_tclkpre_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_3_hs_tx_3_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_4_hs_tx_4_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_5_hs_tx_5_thstrail_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_6_hs_tx_6_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_8_hs_tx_8_tclkpost_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_9_hs_tx_9_thsprpr_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_10_hs_tx_10_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_dlane_clk_rw_hs_tx_12_hs_tx_12_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_1_hs_tx_1_tpost_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_clane_0_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_cfg_0_cfg_0_lp_pin_swap_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_pin_swap_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_1_hs_tx_1_tpost_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_clane_1_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_lp_0_lp_0_ttago_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_lp_0_lp_0_itminrx_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_0_hs_tx_0_thsexit_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_1_hs_tx_1_tpost_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_2_hs_tx_2_tcalpreamble_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_3_hs_tx_3_burst_type_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb0_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb1_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb2_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb3_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_4_hs_tx_4_progseqsymb4_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb5_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb6_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb7_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb8_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_5_hs_tx_5_progseqsymb9_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb10_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb11_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb12_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_6_hs_tx_6_progseqsymb13_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_7_hs_tx_7_t3prpr_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_8_hs_tx_8_tlp11end_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_9_hs_tx_9_t3post_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_10_hs_tx_10_tprebegin_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_11_hs_tx_11_tlpx_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_12_hs_tx_12_tlp11init_dco_reg;
	const struct reg_field	cfg_core_dig_clane_2_rw_hs_tx_13_hs_tx_13_tlptxoverlap_reg;

	const struct reg_field	cfg_core_dig_ioctrl_r_common_ppi_ovr_0_12_phy_state;

	/* Telmo */
	const struct reg_field	cfg_core_dig_rw_common_1_ocla_data_sel;
	const struct reg_field	cfg_core_dig_rw_common_3_ocla_clk_sel;
	const struct reg_field cfg_ppi_rw_hstx_fifo_cfg_txdatatransferenhs_sel;

	/* Unexpected LP data transmission on lane 2 fix */
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane1_ovr_0_3_i_txrequestesc_d1_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane1_ovr_0_4_i_txrequestesc_d1_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane2_ovr_0_3_i_txrequestesc_d2_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane2_ovr_0_4_i_txrequestesc_d2_ovr_en;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane3_ovr_0_3_i_txrequestesc_d3_ovr_val;
	const struct reg_field
		cfg_core_dig_ioctrl_rw_dphy_ppi_lane3_ovr_0_4_i_txrequestesc_d3_ovr_en;

	/* ds_ss_dsi2host_abp_regbank */
	const struct reg_field	cfg_pll_cfg0_rw_pll_atb_sense_sel;
	const struct reg_field	cfg_pll_cfg0_rw_pll_clksel;
	const struct reg_field	cfg_pll_cfg0_rw_pll_gp_clk_en;
	const struct reg_field	cfg_pll_cfg0_rw_pll_opmode;
	const struct reg_field	cfg_pll_cfg0_rw_pll_meas_iv;
	const struct reg_field	cfg_pll_cfg0_rw_pll_clkouten_left;

	const struct reg_field	cfg_pll_cfg1_rw_pll_prg_31_0;

	const struct reg_field	cfg_pll_cfg2_rw_pll_prg_32;
	const struct reg_field	cfg_pll_cfg2_rw_pll_th1;
	const struct reg_field	cfg_pll_cfg2_rw_pll_th2;
	const struct reg_field	cfg_pll_cfg2_rw_pll_th3;

	const struct reg_field	cfg_pll_cfg3_rw_pll_mint;
	const struct reg_field	cfg_pll_cfg3_rw_pll_m;
	const struct reg_field	cfg_pll_cfg3_rw_pll_n;
	const struct reg_field	cfg_pll_cfg3_rw_pll_fracn_cfg_update_en;
	const struct reg_field	cfg_pll_cfg3_rw_pll_fracn_en;

	const struct reg_field	cfg_pll_cfg4_rw_pll_frac_den;
	const struct reg_field	cfg_pll_cfg5_rw_pll_stepsize;

	const struct reg_field	cfg_pll_cfg6_rw_pll_ssc_en;
	const struct reg_field	cfg_pll_cfg6_rw_pll_spread_type;
	const struct reg_field	cfg_pll_cfg6_rw_pll_ssc_peak;

	const struct reg_field	cfg_pll_cfg7_rw_pll_frac_quot;
	const struct reg_field	cfg_pll_cfg7_rw_pll_frac_rem;

	const struct reg_field	cfg_pll_cp_rw_pll_vco_cntrl_0_2;
	const struct reg_field	cfg_pll_cp_rw_pll_vco_cntrl_3_5;
	const struct reg_field	cfg_pll_cp_rw_pll_prop_cntrl;
	const struct reg_field	cfg_pll_cp_rw_pll_int_cntrl;
	const struct reg_field	cfg_pll_cp_rw_pll_gmp_cntrl;
	const struct reg_field	cfg_pll_cp_rw_pll_cpbias_cntrl;

	const struct reg_field	cfg_phy_sts_r_phy_ready;
	const struct reg_field	cfg_phy_sts_r_pll_lock;
	const struct reg_field	cfg_phy_sts_r_pll_vpl_det;

	const struct reg_field	cfg_phy_ctrl0_rw_phy_rst_n;
	const struct reg_field	cfg_phy_ctrl0_rw_shutdown_n;
	const struct reg_field	cfg_phy_ctrl0_rw_phy_mode;
	const struct reg_field	cfg_phy_ctrl0_rw_test_stop_clk_en;
	const struct reg_field	cfg_phy_ctrl0_rw_bist_en;

	const struct reg_field	cfg_phy_extended_ctr0_rw_forcerxmode_dck;
	const struct reg_field	cfg_phy_extended_ctr0_rw_forcerxmode_0;
	const struct reg_field	cfg_phy_extended_ctr0_rw_forcerxmode_1;
	const struct reg_field	cfg_phy_extended_ctr0_rw_forcerxmode_2;
	const struct reg_field	cfg_phy_extended_ctr0_rw_forcerxmode_3;
	const struct reg_field	cfg_phy_extended_ctr0_rw_turndisable_0;
	const struct reg_field	cfg_phy_extended_ctr0_rw_turndisable_1;
	const struct reg_field	cfg_phy_extended_ctr0_rw_turndisable_2;
	const struct reg_field	cfg_phy_extended_ctr0_rw_turndisable_3;

	const struct reg_field	cfg_phy_extended_ctr1_rw_enable0;
	const struct reg_field	cfg_phy_extended_ctr1_rw_enable1;
	const struct reg_field	cfg_phy_extended_ctr1_rw_enable2;
	const struct reg_field	cfg_phy_extended_ctr1_rw_enable3;
	const struct reg_field	cfg_phy_extended_ctr1_rw_enable_dck;
	const struct reg_field	cfg_phy_extended_ctr1_rw_enable_ov_en;
	const struct reg_field	cfg_phy_extended_ctr1_rw_forcetxstopmode_dck;
	const struct reg_field	cfg_phy_extended_ctr1_rw_forcetxstopmode_0;
	const struct reg_field	cfg_phy_extended_ctr1_rw_forcetxstopmode_1;
	const struct reg_field	cfg_phy_extended_ctr1_rw_forcetxstopmode_2;
	const struct reg_field	cfg_phy_extended_ctr1_rw_forcetxstopmode_3;
	const struct reg_field	cfg_phy_extended_ctr1_rw_txdatawidthhs_0;
	const struct reg_field	cfg_phy_extended_ctr1_rw_txdatawidthhs_1;
	const struct reg_field	cfg_phy_extended_ctr1_rw_txdatawidthhs_2;
	const struct reg_field	cfg_phy_extended_ctr1_rw_txdatawidthhs_3;
	const struct reg_field	cfg_phy_extended_ctr1_rw_cont_en;
	const struct reg_field	cfg_phy_extended_ctr1_rw_cont_en_ov_en;

	const struct reg_field	cfg_phy_common9_reg;
	const struct reg_field	cfg_phy_startup_cfg3_reg;
};

int cdphy_init_g301(struct dw_mipi_cdphy *cdphy);
int cdphy_remove_g301(struct dw_mipi_cdphy *cdphy);

#endif /* _DW_MIPI_DPHY_G301_H_ */
