/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _INTERCONNECT_RDO_H
#define _INTERCONNECT_RDO_H

enum {
	/* GMC */
	RDO_GMC = 0,
	RDO_SSWRP_CPU,
	RDO_SSWRP_DPU,
	RDO_SSWRP_PCIE_0,
	RDO_SSWRP_PCIE_1,
	RDO_SSWRP_UFS,
	RDO_SSWRP_USB,
	RDO_SSWRP_ISP_SET_0,
	RDO_SSWRP_ISP_SET_1,
	RDO_SSWRP_EH,
	RDO_SSWRP_GPCA,
	RDO_SSWRP_GPU,
	RDO_SSWRP_CODEC_3P,
	RDO_SSWRP_G2D,
	RDO_SSWRP_GSW,
	RDO_SSWRP_GSA,
	/* GSLC */
	RDO_GSLC,
	RDO_SSWRP_CPU_GSLC,
	RDO_SSWRP_DPU_GSLC,
	RDO_SSWRP_PCIE_0_GSLC,
	RDO_SSWRP_PCIE_1_GSLC,
	RDO_SSWRP_UFS_GSLC,
	RDO_SSWRP_USB_GSLC,
	RDO_SSWRP_ISP_SET_0_GSLC,
	RDO_SSWRP_ISP_SET_1_GSLC,
	RDO_SSWRP_EH_GSLC,
	RDO_SSWRP_GPCA_GSLC,
	RDO_SSWRP_GPU_GSLC,
	RDO_SSWRP_CODEC_3P_GSLC,
	RDO_SSWRP_G2D_GSLC,
	RDO_SSWRP_GSW_GSLC,
	RDO_SSWRP_GSA_GSLC,
	/* ISPFE */
	RDO_ISPFE,
	/* ISPFE - GSLC */
	RDO_ISPFE_GSLC,
	/* ISPBE */
	RDO_ISPBE_TNR_ALIGN,
	RDO_ISPBE_BE_BAYER_TNR,
	RDO_ISPBE_BE_YUV,
	/* ISPBE - GSLC */
	RDO_ISPBE_TNR_ALIGN_GSLC,
	RDO_ISPBE_BE_BAYER_TNR_GSLC,
	RDO_ISPBE_BE_YUV_GSLC,
	/* GSW */
	RDO_GSW_GSE,
	RDO_GSW_GWE,
	/* GSW - GSLC */
	RDO_GSW_GSE_GSLC,
	RDO_GSW_GWE_GSLC,
};

#endif /* _INTERCONNECT_RDO_H */
