# SPDX-License-Identifier: GPL-2.0-only
#
# The configs of the Linux checkpatch script
#
# Copyright (c) 2025 Google LLC

# The MAINTAINERS file patterns are not used in current gerrit
--ignore FILE_PATH_CHANGES
