/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */

#ifndef __DT_BINDINGS_MEM_QOS_GOOGLE_MEM_QOS_H
#define __DT_BINDINGS_MEM_QOS_GOOGLE_MEM_QOS_H

#define MEM_QOS_SCENARIO_DEFAULT				0
#define MEM_QOS_SCENARIO_DECODE_PERFORMANCE		1
#define MEM_QOS_SCENARIO_CAMERA_DEFAULT			2
#define MEM_QOS_SCENARIO_DPU_DEFAULT			3
#define NUM_MEM_QOS_SCENARIO					4

#endif /* __DT_BINDINGS_MEM_QOS_GOOGLE_MEM_QOS_H */
