# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_I2C_DW_GOOGLE_CORE)			+= i2c-designware-core.o
i2c-designware-core-y					:= i2c-designware-common.o
i2c-designware-core-y					+= i2c-designware-master.o

obj-$(CONFIG_I2C_DW_GOOGLE_QUIRKS) += i2c-designware-platform.o
i2c-designware-platform-y := i2c-designware-platdrv.o
