/* SPDX-License-Identifier: GPL-2.0-only */
// Copyright 2022, Google LLC

#ifndef _MAILBOX_GOOGLE_PROTOCOLS_MBA_APC_COMMON_SERVICE_IDS_H
#define _MAILBOX_GOOGLE_PROTOCOLS_MBA_APC_COMMON_SERVICE_IDS_H

enum apc_common_mba_service_id {
	APC_COMMON_SERVICE_FIRST = 0x0,
	APC_COMMON_SERVICE_ID_RESERVED = 0x0,
	APC_COMMON_SERVICE_ID_PING = 0x1,
	APC_COMMON_SERVICE_ID_CPMLOG = 0x2,
	APC_COMMON_SERVICE_ID_GMC = 0x3,
	APC_COMMON_SERVICE_ID_GSLC = 0x4,
	APC_COMMON_SERVICE_ID_CPM_TRACEPOINT = 0x5,
	APC_COMMON_SERVICE_ID_PF_STATE_CPM = 0x6,
	APC_COMMON_SERVICE_ID_POWER_CONTROLLER = 0x7,
	APC_COMMON_SERVICE_ID_MIPM = 0x8,
	APC_COMMON_SERVICE_LAST = 0x37,
};

#endif
