/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2022 VeriSilicon Holdings Co., Ltd.
 */
#include "drm/vs_drm_fourcc.h"
#include <drm/vs_drm.h>
#include "vs_dc_info.h"

#define FRAC_16_16(mult, div) (((mult) << 16) / (div))

/*
 * RGB to YUV2020 in limited range conversion parameters(10 bit pipeline)
 * RGB2YUV[0] - [8] : C0 - C8;
 * RGB2YUV[9] - [11]: Pre Coefficient D0 - D2;
 * RGB2YUV[12] - [14]: Post Coefficient D0 - D2;
 */

static const u32 plane_format0[] = {
	DRM_FORMAT_XRGB4444,	DRM_FORMAT_XBGR4444,	  DRM_FORMAT_RGBX4444,
	DRM_FORMAT_BGRX4444,	DRM_FORMAT_ARGB4444,	  DRM_FORMAT_ABGR4444,
	DRM_FORMAT_RGBA4444,	DRM_FORMAT_BGRA4444,	  DRM_FORMAT_XRGB1555,
	DRM_FORMAT_XBGR1555,	DRM_FORMAT_RGBX5551,	  DRM_FORMAT_BGRX5551,
	DRM_FORMAT_ARGB1555,	DRM_FORMAT_ABGR1555,	  DRM_FORMAT_RGBA5551,
	DRM_FORMAT_BGRA5551,	DRM_FORMAT_RGB565,	  DRM_FORMAT_BGR565,
	DRM_FORMAT_XRGB8888,	DRM_FORMAT_XBGR8888,	  DRM_FORMAT_RGBX8888,
	DRM_FORMAT_BGRX8888,	DRM_FORMAT_ARGB8888,	  DRM_FORMAT_ABGR8888,
	DRM_FORMAT_RGBA8888,	DRM_FORMAT_BGRA8888,	  DRM_FORMAT_ARGB2101010,
	DRM_FORMAT_ABGR2101010, DRM_FORMAT_RGBA1010102,	  DRM_FORMAT_BGRA1010102,
	DRM_FORMAT_XRGB2101010, DRM_FORMAT_XBGR2101010,	  DRM_FORMAT_RGBX1010102,
	DRM_FORMAT_BGRX1010102, DRM_FORMAT_ARGB16161616F, DRM_FORMAT_ABGR16161616F,
	DRM_FORMAT_YVU420,	DRM_FORMAT_YUV420,	  DRM_FORMAT_NV12,
	DRM_FORMAT_NV21,	DRM_FORMAT_NV16,	  DRM_FORMAT_NV61,
	DRM_FORMAT_P010,	DRM_FORMAT_P210,
};

static const u32 plane_format1[] = {
	DRM_FORMAT_XRGB4444,	  DRM_FORMAT_XBGR4444,	    DRM_FORMAT_RGBX4444,
	DRM_FORMAT_BGRX4444,	  DRM_FORMAT_ARGB4444,	    DRM_FORMAT_ABGR4444,
	DRM_FORMAT_RGBA4444,	  DRM_FORMAT_BGRA4444,	    DRM_FORMAT_XRGB1555,
	DRM_FORMAT_XBGR1555,	  DRM_FORMAT_RGBX5551,	    DRM_FORMAT_BGRX5551,
	DRM_FORMAT_ARGB1555,	  DRM_FORMAT_ABGR1555,	    DRM_FORMAT_RGBA5551,
	DRM_FORMAT_BGRA5551,	  DRM_FORMAT_RGB565,	    DRM_FORMAT_BGR565,
	DRM_FORMAT_XRGB8888,	  DRM_FORMAT_XBGR8888,	    DRM_FORMAT_RGBX8888,
	DRM_FORMAT_BGRX8888,	  DRM_FORMAT_ARGB8888,	    DRM_FORMAT_ABGR8888,
	DRM_FORMAT_RGBA8888,	  DRM_FORMAT_BGRA8888,	    DRM_FORMAT_ARGB2101010,
	DRM_FORMAT_ABGR2101010,	  DRM_FORMAT_RGBA1010102,   DRM_FORMAT_BGRA1010102,
	DRM_FORMAT_ARGB16161616F, DRM_FORMAT_ABGR16161616F,
};

static const u32 wb_format0[] = {
	DRM_FORMAT_XRGB8888,
	/*
	 * Use DRM_FORMAT_XRGB16161616F to represent
	 * the writeback of DP output, as HW will write-back
	 * at 64bits/pixel in this case.
	 */
	DRM_FORMAT_XRGB16161616F,
};

static const u32 wb_format2[] = {
	DRM_FORMAT_ARGB8888, DRM_FORMAT_ARGB2101010, DRM_FORMAT_YVU420, DRM_FORMAT_YUV420,
	DRM_FORMAT_NV12,     DRM_FORMAT_NV21,	     DRM_FORMAT_NV16,	DRM_FORMAT_NV61,
	DRM_FORMAT_P010,     DRM_FORMAT_P210,
};

static const u64 format_modifier[] = {
	DRM_FORMAT_MOD_LINEAR,
	fourcc_mod_vs_norm_code(DRM_FORMAT_MOD_VS_LINEAR),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_8X8, DRM_FORMAT_MOD_VS_DEC_LOSSLESS),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_8X8, DRM_FORMAT_MOD_VS_DEC_LOSSY),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_16X4, DRM_FORMAT_MOD_VS_DEC_LOSSLESS),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_16X4, DRM_FORMAT_MOD_VS_DEC_LOSSY),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_32X2, DRM_FORMAT_MOD_VS_DEC_LOSSLESS),
	fourcc_mod_vs_pvric_code(DRM_FORMAT_MOD_VS_DEC_TILE_32X2, DRM_FORMAT_MOD_VS_DEC_LOSSY),
	DRM_FORMAT_MOD_INVALID,
};

static const u64 wb_modifier[] = {
	DRM_FORMAT_MOD_LINEAR,
	fourcc_mod_vs_norm_code(DRM_FORMAT_MOD_VS_LINEAR),
	DRM_FORMAT_MOD_INVALID,
};

static const struct vs_dc_urgent_cmd_config urgent_cmd_config = {
	.h_margin_pct = 90,
	.v_margin_pct = 100,
	.delay_counter_usec = 200,
	.urgent_value = 3,
	.enable = true,
};

static const struct vs_dc_urgent_vid_config urgent_vid_config = {
	.qos_thresh_0 = 1946,
	.qos_thresh_1 = 1638,
	.qos_thresh_2 = 1229,
	.urgent_thresh_0 = 1946,
	.urgent_thresh_1 = 1638,
	.urgent_thresh_2 = 1229,
	.urgent_low_thresh = 1638,
	.urgent_high_thresh = 1946,
	.healthy_thresh = 2048,
	.enable = true,
};

static const struct vs_plane_info plane_fe0_info[] = {
	/* DC_REV_0 */
	{
		.name = "Layer0",
		.id = HW_PLANE_0,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format0),
		.formats = plane_format0,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0 | DRM_MODE_ROTATE_90 | DRM_MODE_ROTATE_180 |
			    DRM_MODE_ROTATE_270 | DRM_MODE_REFLECT_X | DRM_MODE_REFLECT_Y,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.color_encoding = BIT(DRM_COLOR_YCBCR_BT601) | BIT(DRM_COLOR_YCBCR_BT709) |
				  BIT(DRM_COLOR_YCBCR_BT2020),
		.color_range = BIT(DRM_COLOR_YCBCR_LIMITED_RANGE) | BIT(DRM_COLOR_YCBCR_FULL_RANGE),
		.min_scale = FRAC_16_16(1, 8), /* src << 16 / dst, mean up scale max 8 times */
		.max_scale = FRAC_16_16(4, 1), /* src << 16 / dst, meas down scale max 4 times */
		.zpos = 0,
		.axi_id = 0,
		.max_uv_phase = 16,
		.color_mgmt = 1,
		.program_csc = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer1",
		.id = HW_PLANE_1,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format0),
		.formats = plane_format0,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0 | DRM_MODE_ROTATE_90 | DRM_MODE_ROTATE_180 |
			    DRM_MODE_ROTATE_270 | DRM_MODE_REFLECT_X | DRM_MODE_REFLECT_Y,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.color_encoding = BIT(DRM_COLOR_YCBCR_BT601) | BIT(DRM_COLOR_YCBCR_BT709) |
				  BIT(DRM_COLOR_YCBCR_BT2020),
		.color_range = BIT(DRM_COLOR_YCBCR_LIMITED_RANGE) | BIT(DRM_COLOR_YCBCR_FULL_RANGE),
		.min_scale = FRAC_16_16(1, 8), /* src << 16 / dst, mean up scale max 8 times */
		.max_scale = FRAC_16_16(4, 1), /* src << 16 / dst, meas down scale max 4 times */
		.zpos = 1,
		.axi_id = 1,
		.max_uv_phase = 16,
		.color_mgmt = 1,
		.program_csc = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer2",
		.id = HW_PLANE_2,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 2,
		.axi_id = 0,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer3",
		.id = HW_PLANE_3,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_PRIMARY,
		.crtc_id = 0x0,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 3,
		.axi_id = 1,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer4",
		.id = HW_PLANE_4,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_PRIMARY,
		.crtc_id = 0x1,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 4,
		.axi_id = 0,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer5",
		.id = HW_PLANE_5,
		.fe_id = VS_FE_0,
		.type = DRM_PLANE_TYPE_PRIMARY,
		.crtc_id = 0x2,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 5,
		.axi_id = 1,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
};

static const struct vs_plane_info plane_fe1_info[] = {
	{
		.name = "Layer8",
		.id = HW_PLANE_8,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format0),
		.formats = plane_format0,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0 | DRM_MODE_ROTATE_90 | DRM_MODE_ROTATE_180 |
			    DRM_MODE_ROTATE_270 | DRM_MODE_REFLECT_X | DRM_MODE_REFLECT_Y,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.color_encoding = BIT(DRM_COLOR_YCBCR_BT601) | BIT(DRM_COLOR_YCBCR_BT709) |
				  BIT(DRM_COLOR_YCBCR_BT2020),
		.color_range = BIT(DRM_COLOR_YCBCR_LIMITED_RANGE) | BIT(DRM_COLOR_YCBCR_FULL_RANGE),
		.min_scale = FRAC_16_16(1, 8), /* src << 16 / dst, mean up scale max 8 times */
		.max_scale = FRAC_16_16(4, 1), /* src << 16 / dst, meas down scale max 4 times */
		.zpos = 6,
		.axi_id = 1,
		.max_uv_phase = 16,
		.color_mgmt = 1,
		.program_csc = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer9",
		.id = HW_PLANE_9,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format0),
		.formats = plane_format0,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0 | DRM_MODE_ROTATE_90 | DRM_MODE_ROTATE_180 |
			    DRM_MODE_ROTATE_270 | DRM_MODE_REFLECT_X | DRM_MODE_REFLECT_Y,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.color_encoding = BIT(DRM_COLOR_YCBCR_BT601) | BIT(DRM_COLOR_YCBCR_BT709) |
				  BIT(DRM_COLOR_YCBCR_BT2020),
		.color_range = BIT(DRM_COLOR_YCBCR_LIMITED_RANGE) | BIT(DRM_COLOR_YCBCR_FULL_RANGE),
		.min_scale = FRAC_16_16(1, 8), /* src << 16 / dst, mean up scale max 8 times */
		.max_scale = FRAC_16_16(4, 1), /* src << 16 / dst, meas down scale max 4 times */
		.zpos = 7,
		.axi_id = 0,
		.max_uv_phase = 16,
		.color_mgmt = 1,
		.program_csc = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer10",
		.id = HW_PLANE_10,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 8,
		.axi_id = 1,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer11",
		.id = HW_PLANE_11,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_PRIMARY,
		.crtc_id = 0x3,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 9,
		.axi_id = 0,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer12",
		.id = HW_PLANE_12,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_PRIMARY,
		.crtc_id = 0x4,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 10,
		.axi_id = 1,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
	{
		.name = "Layer13",
		.id = HW_PLANE_13,
		.fe_id = VS_FE_1,
		.type = DRM_PLANE_TYPE_OVERLAY,
		.num_formats = ARRAY_SIZE(plane_format1),
		.formats = plane_format1,
		.num_modifiers = ARRAY_SIZE(format_modifier),
		.modifiers = format_modifier,
		.min_width = 8,
		.min_height = 8,
		.max_width = 8192,
		.max_yuv_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.blend_mode = BIT(DRM_MODE_BLEND_PREMULTI) | BIT(DRM_MODE_BLEND_COVERAGE) |
			      BIT(DRM_MODE_BLEND_PIXEL_NONE),
		.min_scale = VS_PLANE_NO_SCALING,
		.max_scale = VS_PLANE_NO_SCALING,
		.zpos = 11,
		.axi_id = 0,
		.color_mgmt = 1,
		.roi = 1,
		.roi_two = 1,
		.roi_skip = 0,
		.layer_ext = 1,
		.layer_ext_ex = 1,
		.alpha_ext = 1,
		.demultiply = 1,
		.hdr = 1,
		.tone_map = 1,
		.blend_config = 1,
		.crc = 1,
		.test_pattern = 1,
		.compressed = 1,
	},
};

static const struct vs_display_info crtc_be_info[] = {
	/* DC_REV_0 */
	{
		.name = "Out_ctrl0",
		.id = HW_DISPLAY_0,
		.color_formats = DRM_COLOR_FORMAT_RGB444,
		.max_width = 3840,
		.max_height = 2160,
		.min_scale = FRAC_16_16(1, 4), /* src << 16 / dst, means up scale max 4 times */
		.max_scale = FRAC_16_16(1, 1),
		.background = 1,
		.bld_oetf = 1,
		.bld_dth = 1,
		.gamma_dth = 1,
		.panel_dth = 1,
		.llv_dth = 1,
		/* TODO (b/293348411): temporarily remove ltm to reduce drm property count */
		.ltm = 0,
		.sharpness = 1,
		.brightness = 1,
		.degamma = 1,
		.gamma = 1,
		.ccm_non_linear = 1,
		.ccm_linear = 1,
		.cgm_lut = 1,
		.lut_roi = 1,
		.blur = 1,
		.sec_roi = 1,
		.data_mode = 1,
		.histogram = 1,
		.rgb_hist = 1,
		.crc = 1,
		.test_pattern = 1,
		.disp_in_wb = 1,
		.disp_cc_wb = 1,
		.disp_out_wb = 1,
		.ofifo_in_wb = 1,
		.ofifo_out_wb = 1,
		.decompress = 1,
		.dsc = 1,
		.vdc = 1,
	},
	{
		.name = "Out_ctrl1",
		.id = HW_DISPLAY_1,
		.color_formats = DRM_COLOR_FORMAT_RGB444,
		.max_width = 3840,
		.max_height = 2160,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.background = 1,
		.bld_oetf = 1,
		.bld_dth = 1,
		.gamma_dth = 1,
		.panel_dth = 1,
		.llv_dth = 1,
		.gtm = 1,
		.sharpness = 1,
		.brightness = 1,
		.degamma = 1,
		.gamma = 1,
		.ccm_non_linear = 1,
		.ccm_linear = 1,
		.cgm_lut = 1,
		.lut_roi = 0,
		.blur = 0,
		.sec_roi = 1,
		.data_mode = 1,
		.histogram = 1,
		.crc = 1,
		.test_pattern = 1,
		.disp_in_wb = 1,
		.disp_cc_wb = 1,
		.disp_out_wb = 1,
		.ofifo_in_wb = 1,
		.ofifo_out_wb = 1,
		.decompress = 1,
		.dsc = 1,
		.vdc = 1,
	},
	{
		.name = "Out_ctrl2",
		.id = HW_DISPLAY_2,
		.color_formats = DRM_COLOR_FORMAT_RGB444 | DRM_COLOR_FORMAT_YCBCR444 |
				 DRM_COLOR_FORMAT_YCBCR422, /* TBD */
		.max_width = 7680,
		.max_height = 4320,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.background = 1,
		.bld_cgm = 1,
		.bld_oetf = 1,
		.bld_dth = 1,
		.panel_dth = 1,
		.crc = 1,
		.test_pattern = 1,
		.disp_in_wb = 1,
		.disp_out_wb = 1,
		.ofifo_in_wb = 1,
		.ofifo_out_wb = 1,
		.decompress = 0,
		.dsc = 1,
	},
	{
		.name = "Out_ctrl3",
		.id = HW_DISPLAY_3,
		.color_formats = DRM_COLOR_FORMAT_RGB444 | DRM_COLOR_FORMAT_YCBCR444 |
				 DRM_COLOR_FORMAT_YCBCR422, /* TBD */
		.max_width = 7680,
		.max_height = 4320,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.background = 1,
		.bld_cgm = 1,
		.bld_oetf = 1,
		.bld_dth = 1,
		.panel_dth = 1,
		.crc = 1,
		.test_pattern = 1,
		.disp_in_wb = 1,
		.disp_out_wb = 1,
		.ofifo_in_wb = 1,
		.ofifo_out_wb = 1,
		.decompress = 0,
	},
	{
		.name = "Out_ctrl4",
		.id = HW_DISPLAY_4,
		.color_formats = DRM_COLOR_FORMAT_RGB444 | DRM_COLOR_FORMAT_YCBCR422 |
				 DRM_COLOR_FORMAT_YCBCR420,
		.max_width = 7680,
		.max_height = 4320,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.background = 1,
		.bld_oetf = 1,
		.bld_dth = 1,
		.panel_dth = 1,
		.crc = 1,
		.test_pattern = 1,
		.disp_out_wb = 1,
		.decompress = 0,
	},
};

const struct vs_wb_info crtc_wb_info[] = {
	/* DC_REV_0 */
	{
		.name = "Post_write_back0",
		.id = HW_WB_0,
		.num_formats = ARRAY_SIZE(wb_format0),
		.formats = wb_format0,
		.modifiers = wb_modifier,
		.max_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.src_mask = 0xF,
		.program_point = 1,
		.crc = 1,
		.compressed = 1,
		.spliter = 0,
		.wb_stall = 0,
	},
	{
		.name = "Post_write_back1",
		.id = HW_WB_1,
		.num_formats = ARRAY_SIZE(wb_format0),
		.formats = wb_format0,
		.modifiers = wb_modifier,
		.max_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.src_mask = 0xF,
		.program_point = 1,
		.crc = 1,
		.compressed = 1,
		.spliter = 0,
		.wb_stall = 0,
	},
	{
		.name = "Blend_write_back",
		.id = HW_BLEND_WB,
		.num_formats = ARRAY_SIZE(wb_format2),
		.formats = wb_format2,
		.modifiers = wb_modifier,
		.max_width = 7680,
		.max_height = 4320,
		.rotation = DRM_MODE_ROTATE_0,
		.min_scale = FRAC_16_16(1, 1),
		.max_scale = FRAC_16_16(1, 1),
		.src_mask = 0x10,
		.program_point = 0,
		.crc = 1,
		.spliter = 0,
		.wb_stall = 0,
	},
};

const struct vs_dc_info dc_info_9400_316 = {
	/* DC_REV_0 */
	.name = "DC9400",
	.chip_id = VS_CHIP_ID_9400,
	.revision = 0x7000,
	.pid = 0x02094000,
	.cid = 0x316,
	.plane_fe0_num = ARRAY_SIZE(plane_fe0_info),
	.plane_fe1_num = ARRAY_SIZE(plane_fe1_info),
	.plane_num = ARRAY_SIZE(plane_fe0_info) + ARRAY_SIZE(plane_fe1_info),
	.planes_fe0 = plane_fe0_info,
	.planes_fe1 = plane_fe1_info,
	.layer_fe0_num = ARRAY_SIZE(plane_fe0_info),
	.layer_fe1_num = ARRAY_SIZE(plane_fe1_info),
	.layer_num = ARRAY_SIZE(plane_fe0_info) + ARRAY_SIZE(plane_fe1_info),
	.display_num = ARRAY_SIZE(crtc_be_info),
	.displays = crtc_be_info,
	.wb_num = ARRAY_SIZE(crtc_wb_info),
	.write_back = crtc_wb_info,
	.max_bpc = 24,
	.pitch_alignment = 64,
	.addr_alignment = 256,
	.fe0_dma_sram_size = 512,
	.fe1_dma_sram_size = 512,
	.fe0_scl_sram_size = 144,
	.fe1_scl_sram_size = 144,
	.max_blend_layer = 14,
	.max_ext_layer = 14,
	.max_seg_num = 10,
	.urgent_cmd_config = &urgent_cmd_config,
	.urgent_vid_config = &urgent_vid_config,
	.max_eotf_size = 129,
	.max_tonemap_size = 33,
	.max_oetf_size = 65,
	.max_degamma_size = 129,
	.cgm_lut_size = 4913,
	.cgm_ex_lut_size = 729,
	.max_gamma_size = 257,
	.pre_eotf_bits = 12,
	.hdr_bits = 24,
	.oetf_bits = 24,
	.bld_cgm_bits = 24,
	.pre_degamma_bits = 10,
	.degamma_bits = 14,
	.cgm_lut_bits = 14,
	.gamma_bits = 14,
	.blur_coef_bits = 6,
	.std_color_lut = false,
	.multi_roi = 1,
	.cap_dec = (1 << DRM_FORMAT_MOD_VS_TYPE_PVRIC),
	.roi_y_gap = 0,
	.vrr = 1,
	.crc_roi = 0,
	.dma_sram_alignment = 1024,
	.dma_sram_extra_buffer = 1,
	.dma_sram_unit_size = SRAM_UNIT_SIZE_64KB,
	.linear_yuv_rotation = 1,
	.ppc = 2,
	.vblank_margin_pct = 10,
	.h_bubble_pct = 5,
	.rotation_prefetch_line = 32,
	.rotation_pipeline_delay_us = 50,
	.rotation_pipeline_latency_us = 160,
	.rotation_nominal_cycle_num = 32000,
	.rotation_nominal_cycle_denom = 1440,
	.axi_bus_bit_width = 256,
	.axi_bus_util_pct = 70,
	.max_nv12_uncomp_rot_width = 1920,
	.max_nv12_uncomp_rot_height = 1080,
	.fe_axqos_threshold_mbps = 5401,
	.fe_axqos_high = 0x03030303,
	.fe_axqos_low = 0,
};
