/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */

#ifndef __DT_BINDINGS_INTERCONNECT_GOOGLE_ICC_H
#define __DT_BINDINGS_INTERCONNECT_GOOGLE_ICC_H

#define GOOGLE_ICC_UPDATE_ASYNC			(1U << 0)
#define GOOGLE_ICC_UPDATE_SYNC			(1U << 1)

#endif // __DT_BINDINGS_INTERCONNECT_GOOGLE_ICC_H
