/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!!!! THIS IS A GENERATED FILE, DO NOT EDIT !!!!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * This header provides constants for interrupts on LGA.
 * Generate using scripts/interrupt-controller/gen-gic-intr-header.py
 *
 * Copyright 2023-2024 Google LLC
 *
 */
#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_LGA_H
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_LGA_H

#include <dt-bindings/interrupt-controller/arm-gic.h>

#define SSWRP_AOC_MBOX_APC_0_0                                     0
#define SSWRP_AOC_MBOX_APC_1_1                                     1
#define SSWRP_AOC_MBOX_APC_2_2                                     2
#define SSWRP_AOC_MBOX_APC_3_3                                     3
#define SSWRP_AOC_MBOX_APC_4_4                                     4
#define SSWRP_AOC_MBOX_APC_5_5                                     5
#define SSWRP_AOC_MBOX_APC_6_6                                     6
#define SSWRP_AOC_MBOX_APC_7_7                                     7
#define SSWRP_AOC_MBOX_APC_8_8                                     8
#define SSWRP_AOC_MBOX_APC_9_9                                     9
#define SSWRP_AOC_MBOX_APC_10_10                                   10
#define SSWRP_AOC_MBOX_APC_11_11                                   11
#define SSWRP_AOC_MBOX_APC_12_12                                   12
#define SSWRP_AOC_MBOX_APC_13_13                                   13
#define SSWRP_AOC_MBOX_APC_14_14                                   14
#define SSWRP_AOC_MBOX_APC_15_15                                   15
#define SSWRP_AOC_MBOX_APC_16_16                                   16
#define SSWRP_AOC_MBOX_APC_17_17                                   17
#define SSWRP_AOC_MBOX_APC_18_18                                   18
#define SSWRP_AOC_MBOX_APC_19_19                                   19
#define SSWRP_AOC_AOC_AP_NS_AGGR_INTR                              20
#define SSWRP_AOC_AOC_AP_S_AGGR_INTR                               21
#define SSWRP_APC_NCOREFAULTIRQ                                    39
#define SSWRP_APC_NCOREFAULTIRQ_0                                  40
#define SSWRP_APC_NCOREFAULTIRQ_1                                  41
#define SSWRP_APC_NCOREFAULTIRQ_2                                  42
#define SSWRP_APC_NCOREFAULTIRQ_3                                  43
#define SSWRP_APC_NCOREFAULTIRQ_4                                  44
#define SSWRP_APC_NCOREFAULTIRQ_5                                  45
#define SSWRP_APC_NCOREFAULTIRQ_6                                  46
#define SSWRP_APC_NCOREERRIRQ                                      47
#define SSWRP_APC_NCOREERRIRQ_0                                    48
#define SSWRP_APC_NCOREERRIRQ_1                                    49
#define SSWRP_APC_NCOREERRIRQ_2                                    50
#define SSWRP_APC_NCOREERRIRQ_3                                    51
#define SSWRP_APC_NCOREERRIRQ_4                                    52
#define SSWRP_APC_NCOREERRIRQ_5                                    53
#define SSWRP_APC_NCOREERRIRQ_6                                    54
#define SSWRP_APC_COREPPUIRQ_0                                     55
#define SSWRP_APC_COREPPUIRQ_1                                     56
#define SSWRP_APC_COREPPUIRQ_2                                     57
#define SSWRP_APC_COREPPUIRQ_3                                     58
#define SSWRP_APC_COREPPUIRQ_4                                     59
#define SSWRP_APC_COREPPUIRQ_5                                     60
#define SSWRP_APC_COREPPUIRQ_6                                     61
#define SSWRP_APC_NCOMPLEXFAULTIRQ                                 62
#define SSWRP_APC_NCOMPLEXERRIRQ                                   63
#define SSWRP_APC_CLUSTERPPUIRQ                                    64
#define SSWRP_APC_NCLUSTERPMUIRQ                                   65
#define SSWRP_APC_NCLUSTERFAULTIRQ                                 66
#define SSWRP_APC_NCLUSTERERRIRQ                                   67
#define SSWRP_APC_NMPAMSIRQ                                        68
#define SSWRP_APC_NMPAMNSIRQ                                       69
#define SSWRP_APC_NCLUSTERCRITIRQ                                  70
#define SSWRP_APC_INTREQERRNS_NID20                                71
#define SSWRP_APC_INTREQERRS_NID20                                 72
#define SSWRP_APC_INTREQFAULTNS_NID20                              73
#define SSWRP_APC_INTREQFAULTS_NID20                               74
#define SSWRP_APC_COREPPUIRQ                                       75
#define SSWRP_APC_INTREQMPAMERRS_NID20                             76
#define SSWRP_APC_INTREQPMU_NID20                                  77
#define SSWRP_APC_INTREQPPU_NID20                                  78
#define SSWRP_APC_INTREQMPAMERRNS_NID20                            87
#define SSWRP_APC_M0_TZ_IRQ                                        88
#define SSWRP_APC_CPU_AP_S_INTR                                    89
#define SSWRP_APC_GEM_DSU_0                                        91
#define SSWRP_APC_GEM_DSU_1                                        92
#define SSWRP_APC_GEM_DSU_2                                        93
#define SSWRP_APC_GEM_DSU_3                                        94
#define SSWRP_APC_GEM_EH                                           95
#define SSWRP_APC_MFW_NS                                           97
#define SSWRP_APC_MFW_TZ                                           98
#define SSWRP_APC_CTIIRQ_7                                         99
#define SSWRP_APC_RFW_NS                                           100
#define SSWRP_APC_RFW_TZ                                           101
#define SSWRP_APC_TIMER0_INTR                                      102
#define SSWRP_APC_TIMER1_INTR                                      103
#define SSWRP_APC_WDT_TOP0_WDT_AP_INTR                             104
#define SSWRP_APC_WDT_TOP1_WDT_AP_INTR                             105
#define SSWRP_APC_M0_NON_TZ_IRQ                                    106
#define SSWRP_APC_CPU_AP_NS_INTR                                   107
#define SSWRP_GPU_GPU_IRQ_0_130                                    130
#define SSWRP_GPU_GPU_IRQ_1_131                                    131
#define SSWRP_GPU_GPU_IRQ_2_132                                    132
#define SSWRP_GPU_GPU_IRQ_3_133                                    133
#define SSWRP_GPU_GPU_IRQ_4_134                                    134
#define SSWRP_GPU_GPU_IRQ_5_135                                    135
#define SSWRP_GPU_GPU_IRQ_6_136                                    136
#define SSWRP_GPU_GPU_IRQ_7_137                                    137
#define SSWRP_GPU_GPU_WDT_IRQ                                      138
#define SSWRP_GPU_INTR_OUT_AP_NS_AGGR                              139
#define SSWRP_GPU_INTR_OUT_AP_S_AGGR                               140
#define SSWRP_CPUACC_CPUACC_AP_NS_INTR                             151
#define SSWRP_CPUACC_CPUACC_AP_S_INTR                              152
#define SSWRP_INF_TCU_INF_TCU_AP_NS_AGGR_INTR                      156
#define SSWRP_INF_TCU_INF_TCU_AP_S_AGGR_INTR                       157
#define SSWRP_TPU_SSWRP_TPU_AP_NS_AGGR_IRQ                         160
#define SSWRP_TPU_SSWRP_TPU_AP_TZ_AGGR_IRQ                         161
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_0_169                    169
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_1_170                    170
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_2_171                    171
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_3_172                    172
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_4_173                    173
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_5_174                    174
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_6_175                    175
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_7_176                    176
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_8_177                    177
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_9_178                    178
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_10_179                   179
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_11_180                   180
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_12_181                   181
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_13_182                   182
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_14_183                   183
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_15_184                   184
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_16_185                   185
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_17_186                   186
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_18_187                   187
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_19_188                   188
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_20_189                   189
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_21_190                   190
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_22_191                   191
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_23_192                   192
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_24_193                   193
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_25_194                   194
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_26_195                   195
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_27_196                   196
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_28_197                   197
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_29_198                   198
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_30_199                   199
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_31_200                   200
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_32_201                   201
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_33_202                   202
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_34_203                   203
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_35_204                   204
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_36_205                   205
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_37_206                   206
#define SSWRP_TPU_SSWRP_TPU_AP_NS_MBA_IRQ_38_207                   207
#define SSWRP_TPU_SSWRP_TPU_AP_TZ_MBA_IRQ_0_208                    208
#define SSWRP_TPU_SSWRP_TPU_AP_TZ_MBA_IRQ_1_209                    209
#define SSWRP_TPU_SSWRP_TPU_AP_TZ_MBA_IRQ_2_210                    210
#define SSWRP_TPU_SSWRP_TPU_AP_TZ_MBA_IRQ_3_211                    211
#define SSWRP_TPU_SSWRP_TPU_AP_EL2_S_IRQ                           212
#define SSWRP_TPU_SSWRP_TPU_AP_EL2_NS_IRQ                          213
#define SSWRP_TPU_SSWRP_TPU_AP_WDT_IRQ_0_214                       214
#define SSWRP_TPU_SSWRP_TPU_AP_WDT_IRQ_1_215                       215
#define SSWRP_EH_INTR_EH_AP_S_AGGR                                 220
#define SSWRP_EH_INTR_EH_AP_NS_P2P_0_221                           221
#define SSWRP_EH_INTR_EH_AP_NS_P2P_1_222                           222
#define SSWRP_EH_INTR_EH_AP_NS_P2P_2_223                           223
#define SSWRP_EH_INTR_EH_AP_NS_P2P_3_224                           224
#define SSWRP_EH_INTR_EH_AP_NS_P2P_4_225                           225
#define SSWRP_EH_INTR_EH_AP_NS_P2P_5_226                           226
#define SSWRP_EH_INTR_EH_AP_NS_P2P_6_227                           227
#define SSWRP_EH_INTR_EH_AP_NS_P2P_7_228                           228
#define SSWRP_EH_INTR_EH_AP_NS_P2P_8_229                           229
#define SSWRP_EH_INTR_EH_AP_NS_P2P_9_230                           230
#define SSWRP_EH_INTR_EH_AP_NS_P2P_10_231                          231
#define SSWRP_EH_INTR_EH_AP_NS_P2P_11_232                          232
#define SSWRP_EH_INTR_EH_AP_NS_P2P_12_233                          233
#define SSWRP_EH_INTR_EH_AP_NS_P2P_13_234                          234
#define SSWRP_EH_INTR_EH_AP_NS_P2P_14_235                          235
#define SSWRP_EH_INTR_EH_AP_NS_P2P_15_236                          236
#define SSWRP_EH_INTR_EH_AP_NS_P2P_16_237                          237
#define SSWRP_EH_INTR_EH_AP_NS_P2P_17_238                          238
#define SSWRP_EH_INTR_EH_AP_NS_P2P_18_239                          239
#define SSWRP_EH_INTR_EH_AP_NS_AGGR                                240
#define SSWRP_CPM_CPM_AP_NS_REQ_INT                                250
#define SSWRP_CPM_CPM_AP_NS_RESP_INT                               251
#define SSWRP_CPM_CPM_AP_S_REQ_INT                                 252
#define SSWRP_CPM_CPM_AP_S_RESP_INT                                253
#define SSWRP_CPM_CPM_CPU0_PRE_UVLO                                254
#define SSWRP_CPM_CPM_CPU0_VDROOP1                                 255
#define SSWRP_CPM_CPM_CPU0_VDROOP2                                 256
#define SSWRP_CPM_CPM_CPU0_PRE_OCP                                 257
#define SSWRP_CPM_CPM_CPU0_SOFT_PRE_OCP                            258
#define SSWRP_CPM_CPM_CPU0_THROTTLE                                259
#define SSWRP_CPM_CPM_CPU1_PRE_UVLO                                260
#define SSWRP_CPM_CPM_CPU1_VDROOP1                                 261
#define SSWRP_CPM_CPM_CPU1_VDROOP2                                 262
#define SSWRP_CPM_CPM_CPU1_PRE_OCP                                 263
#define SSWRP_CPM_CPM_CPU1_SOFT_PRE_OCP                            264
#define SSWRP_CPM_CPM_CPU1_THROTTLE                                265
#define SSWRP_CPM_CPM_CPU2_PRE_UVLO                                266
#define SSWRP_CPM_CPM_CPU2_VDROOP1                                 267
#define SSWRP_CPM_CPM_CPU2_VDROOP2                                 268
#define SSWRP_CPM_CPM_CPU2_PRE_OCP                                 269
#define SSWRP_CPM_CPM_CPU2_SOFT_PRE_OCP                            270
#define SSWRP_CPM_CPM_CPU2_THROTTLE                                271
#define SSWRP_CPM_CPM_AP_HYP_REQ_INT                               272
#define SSWRP_CPM_CPM_AP_HYP_RESP_INT                              273
#define SSWRP_CPM_CPM_AP_KERNEL_REQ_INT                            274
#define SSWRP_CPM_CPM_AP_KERNEL_RESP_INT                           275
#define SSWRP_CPM_CPM_AP_VM1_REQ_INT                               276
#define SSWRP_CPM_CPM_AP_VM1_RESP_INT                              277
#define SSWRP_CPM_CPM_AP_VM2_REQ_INT                               278
#define SSWRP_CPM_CPM_AP_VM2_RESP_INT                              279
#define SSWRP_CPM_CPM_AP_VM3_REQ_INT                               280
#define SSWRP_CPM_CPM_AP_VM3_RESP_INT                              281
#define SSWRP_CPM_CPM_AP_VM4_REQ_INT                               282
#define SSWRP_CPM_CPM_AP_VM4_RESP_INT                              283
#define SSWRP_CPM_CPM_APC_AC_OWNER_NS_INT                          284
#define SSWRP_CPM_CPM_APC_AC_OWNER_TZ_INT                          285
#define SSWRP_CPM_CPM_APC_OTP_AGGR_NS_INT                          287
#define SSWRP_CPM_CPM_APC_OTP_AGGR_TZ_INT                          288
#define SSWRP_CPM_CPM_APC_SSWRP_NS_INT                             290
#define SSWRP_CPM_CPM_APC_SSWRP_TZ_INT                             291
#define SSWRP_CPM_CPM_APC_WDT_INT                                  292
#define SSWRP_CPM_CPM_APC_QOS_INT_0_296                            296
#define SSWRP_CPM_CPM_APC_QOS_INT_1_297                            297
#define SSWRP_DTA_GDMC_APC_SEC_REQ_MB_IRQ                          300
#define SSWRP_DTA_GDMC_APC_SEC_RESP_MB_IRQ                         301
#define SSWRP_DTA_GDMC_APC_NONSEC_REQ_MB_IRQ                       302
#define SSWRP_DTA_GDMC_APC_NONSEC_RESP_MB_IRQ                      303
#define SSWRP_DTA_GDMC_APC_CRITICAL_REQ_MB_IRQ                     304
#define SSWRP_DTA_GDMC_APC_CRITICAL_RESP_MB_IRQ                    305
#define SSWRP_DTA_GDMC_APC_AP1_REQ_MB_IRQ                          306
#define SSWRP_DTA_GDMC_APC_AP1_RESP_MB_IRQ                         307
#define SSWRP_DTA_GDMC_APC_AP2_REQ_MB_IRQ                          308
#define SSWRP_DTA_GDMC_APC_AP2_RESP_MB_IRQ                         309
#define SSWRP_DTA_GDMC_APC_AP3_REQ_MB_IRQ                          310
#define SSWRP_DTA_GDMC_APC_AP3_RESP_MB_IRQ                         311
#define SSWRP_DTA_GDMC_AP_AGGR_IRQ                                 312
#define SSWRP_DTA_GDMC_AP_SEC_AGGR_IRQ                             313
#define SSWRP_DTA_GDMC_WDOG_IRQ                                    315
#define SSWRP_DTA_SPARE_OUT_IRQ_0_316                              316
#define SSWRP_DTA_SPARE_OUT_IRQ_1_317                              317
#define SSWRP_DTA_SPARE_OUT_IRQ_2_318                              318
#define SSWRP_DTA_SPARE_OUT_IRQ_3_319                              319
#define SSWRP_DTA_SPARE_OUT_IRQ_4_320                              320
#define SSWRP_DTA_SPARE_OUT_IRQ_5_321                              321
#define SSWRP_DTA_SPARE_OUT_IRQ_6_322                              322
#define SSWRP_DTA_SPARE_OUT_IRQ_7_323                              323
#define SSWRP_DTA_SPARE_OUT_IRQ_8_324                              324
#define SSWRP_DTA_SPARE_OUT_IRQ_9_325                              325
#define SSWRP_DTA_SPARE_OUT_IRQ_10_326                             326
#define SSWRP_DTA_SPARE_OUT_IRQ_11_327                             327
#define SSWRP_DTA_SPARE_OUT_IRQ_12_328                             328
#define SSWRP_DTA_SPARE_OUT_IRQ_13_329                             329
#define SSWRP_GMC0_GMC0_APC_NS_IRQ                                 330
#define SSWRP_GMC0_GMC0_APC_S_IRQ                                  331
#define SSWRP_GMC0_GMC0_APC_S_RT_IRQ                               332
#define SSWRP_GMC0_GMC0_ACS_NS_APC_IRQ                             334
#define SSWRP_GMC0_GMC0_ACS_S_APC_IRQ                              335
#define SSWRP_GMC0_GMC0_IME_APC_S_IRQ                              336
#define SSWRP_GMC0_GMC0_APC_NS_RT_IRQ_0_339                        339
#define SSWRP_GMC0_GMC0_APC_NS_RT_IRQ_1_340                        340
#define SSWRP_GMC1_GMC1_APC_NS_IRQ                                 350
#define SSWRP_GMC1_GMC1_APC_S_IRQ                                  351
#define SSWRP_GMC1_GMC1_APC_S_RT_IRQ                               352
#define SSWRP_GMC1_GMC1_ACS_NS_APC_IRQ                             354
#define SSWRP_GMC1_GMC1_ACS_S_APC_IRQ                              355
#define SSWRP_GMC1_GMC1_IME_APC_S_IRQ                              356
#define SSWRP_GMC1_GMC1_APC_NS_RT_IRQ_0_359                        359
#define SSWRP_GMC1_GMC1_APC_NS_RT_IRQ_1_360                        360
#define SSWRP_GMC2_GMC2_APC_NS_IRQ                                 370
#define SSWRP_GMC2_GMC2_APC_S_IRQ                                  371
#define SSWRP_GMC2_GMC2_APC_S_RT_IRQ                               372
#define SSWRP_GMC2_GMC2_ACS_NS_APC_IRQ                             374
#define SSWRP_GMC2_GMC2_ACS_S_APC_IRQ                              375
#define SSWRP_GMC2_GMC2_IME_APC_S_IRQ                              376
#define SSWRP_GMC2_GMC2_APC_NS_RT_IRQ_0_379                        379
#define SSWRP_GMC2_GMC2_APC_NS_RT_IRQ_1_380                        380
#define SSWRP_GMC3_GMC3_APC_NS_IRQ                                 390
#define SSWRP_GMC3_GMC3_APC_S_IRQ                                  391
#define SSWRP_GMC3_GMC3_APC_S_RT_IRQ                               392
#define SSWRP_GMC3_GMC3_ACS_NS_APC_IRQ                             394
#define SSWRP_GMC3_GMC3_ACS_S_APC_IRQ                              395
#define SSWRP_GMC3_GMC3_IME_APC_S_IRQ                              396
#define SSWRP_GMC3_GMC3_APC_NS_RT_IRQ_0_399                        399
#define SSWRP_GMC3_GMC3_APC_NS_RT_IRQ_1_400                        400
#define SSWRP_MEMSS_SLC_APC_S_IRQ_0_410                            410
#define SSWRP_MEMSS_SLC_APC_S_IRQ_1_411                            411
#define SSWRP_MEMSS_SLC_APC_S_IRQ_2_412                            412
#define SSWRP_MEMSS_SLC_APC_S_IRQ_3_413                            413
#define SSWRP_MEMSS_SLC_APC_NS_IRQ_0_414                           414
#define SSWRP_MEMSS_SLC_APC_NS_IRQ_1_415                           415
#define SSWRP_MEMSS_SLC_APC_NS_IRQ_2_416                           416
#define SSWRP_MEMSS_SLC_APC_NS_IRQ_3_417                           417
#define SSWRP_MEMSS_FLOS_FMC_TO_AP_INT                             422
#define SSWRP_MEMSS_FAB_IRQ_TO_AP_NS                               423
#define SSWRP_MEMSS_MEMSS_DVFSMON_IRQ_TO_AP_NS                     424
#define SSWRP_MEMSS_MFW_PPMFW_NS_TO_AP_NS_IRQ                      426
#define SSWRP_MEMSS_MFW_PPMFW_TZ_TO_AP_S_IRQ                       427
#define SSWRP_MEMSS_IRQ_AGG_ICD_DSCGT_IRQ_TO_AP_NS                 428
#define SSWRP_MEMSS_RFW_NS_TO_AP_NS_IRQ                            429
#define SSWRP_MEMSS_RFW_TZ_TO_AP_S_IRQ                             430
#define SSWRP_ISPFE_ISPFE_AP_IRQ                                   460
#define SSWRP_ISPFE_ISPFE_AP_NS_IRQ                                461
#define SSWRP_ISPFE_ISPFE_AP_TZ_IRQ                                462
#define SSWRP_GSW_IRQ_NS                                           520
#define SSWRP_GSW_IRQ_TZ                                           521
#define SSWRP_HSIO_S_HSIOS_PULSE_AGGR_5_INTR_AP_S                  522
#define SSWRP_HSIO_S_HSIOS_PULSE_AGGR_6_INTR_AP_S                  523
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_1                     524
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_2                     525
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_3                     526
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_4                     527
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_5                     528
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_6                     529
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_7                     530
#define SSWRP_HSIO_S_SSWRP_HSIO_S_SPARE0_OUT_8                     531
#define SSWRP_G2D_G2D_APNS_IRQ                                     540
#define SSWRP_G2D_G2D_TZ_IRQ                                       541
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_0_542              542
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_1_543              543
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_2_544              544
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_3_545              545
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_4_546              546
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_5_547              547
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_6_548              548
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_7_549              549
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_8_550              550
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_9_551              551
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_10_552             552
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_11_553             553
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_12_554             554
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_13_555             555
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_14_556             556
#define SSWRP_HSIO_S_HSIOS_UFSHC_CQ_INTR_AP_UFS_15_557             557
#define SSWRP_HSIO_S_HSIOS_PULSE_AGGR_3_INTR_AP_NS                 558
#define SSWRP_HSIO_S_HSIOS_PULSE_AGGR_4_INTR_AP_NS                 559
#define SSWRP_CODEC_3P_C3P_TZ_IRQ                                  560
#define SSWRP_CODEC_3P_C3P_NS_IRQ                                  561
#define SSWRP_CODEC_3P_C3P_VM0_IRQ                                 562
#define SSWRP_CODEC_3P_C3P_VM1_IRQ                                 563
#define SSWRP_CODEC_3P_C3P_VM2_IRQ                                 564
#define SSWRP_CODEC_3P_C3P_VM3_IRQ                                 565
#define SSWRP_HSIO_N_HSION_U2PHY_LINESTATE_CHANGE_P_INTR_AGG_EBU   566
#define SSWRP_HSIO_N_HSION_U2PHY_LINESTATE_CHANGE_M_INTR_AGG_EBU   567
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_0                            568
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_1                            569
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_2                            570
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_3                            571
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_4                            572
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_5                            573
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_6                            574
#define SSWRP_HSIO_N_HSIO_N_SPARE_OUT_7                            575
#define SSWRP_HSIO_N_HSION_USBDRD_INTERRUPT_AGG_EBU_0_580          580
#define SSWRP_HSIO_N_HSION_USBDRD_INTERRUPT_AGG_EBU_1_581          581
#define SSWRP_HSIO_N_HSION_AP_GPIO_INTR                            582
#define SSWRP_HSIO_N_HSION_AP_PCIE_DMA_INTR                        583
#define SSWRP_HSIO_N_HSION_AP_PCIE_INTX_INTR                       584
#define SSWRP_HSIO_N_HSION_AP_PCIE_LINK_INTR                       585
#define SSWRP_HSIO_N_HSION_AP_PCIE_MSI_INTR                        586
#define SSWRP_HSIO_N_HSION_AP_S_INTR_2                             587
#define SSWRP_HSIO_N_HSION_AP_S_INTR_3                             588
#define SSWRP_HSIO_N_HSION_DP_I2S0_INTR_AGG                        589
#define SSWRP_HSIO_N_HSION_DP_I2S1_INTR_AGG                        590
#define SSWRP_HSIO_N_HSION_DP_SDP0_INTR_AGG                        591
#define SSWRP_HSIO_N_HSION_DP_SDP1_INTR_AGG                        592
#define SSWRP_HSIO_N_HSION_EBU_WD_INT_AGG                          593
#define SSWRP_HSIO_N_HSION_USBDP_TCA_INT_AGG                       594
#define SSWRP_HSIO_N_HSION_USBDRD_HOST_SYSTEM_ERR_AGG              595
#define SSWRP_HSIO_N_HSION_USBDRD_PME_GEN_INTR_AGG                 596
#define SSWRP_HSIO_N_HSION_USBDRD_PME_GEN_U2P_INTR_AGG             597
#define SSWRP_HSIO_N_HSION_USBDRD_PME_GEN_U3P_INTR_AGG             598
#define SSWRP_HSIO_N_HSION_USBDRD_PS_CHANGE_INTR_AGG               599
#define SSWRP_CPM_CPM_APC_GPIO_INT_0_600                           600
#define SSWRP_CPM_CPM_APC_GPIO_INT_1_601                           601
#define SSWRP_CPM_CPM_APC_GPIO_INT_2_602                           602
#define SSWRP_CPM_CPM_APC_GPIO_INT_3_603                           603
#define SSWRP_CPM_CPM_APC_GPIO_INT_4_604                           604
#define SSWRP_CPM_CPM_APC_GPIO_INT_5_605                           605
#define SSWRP_CPM_CPM_APC_GPIO_INT_6_606                           606
#define SSWRP_CPM_CPM_APC_GPIO_INT_7_607                           607
#define SSWRP_CPM_CPM_APC_GPIO_INT_8_608                           608
#define SSWRP_CPM_CPM_APC_GPIO_INT_9_609                           609
#define SSWRP_CPM_CPM_APC_GPIO_INT_10_610                          610
#define SSWRP_CPM_CPM_APC_GPIO_INT_11_611                          611
#define SSWRP_CPM_CPM_APC_GPIO_INT_12_612                          612
#define SSWRP_CPM_CPM_APC_GPIO_INT_13_613                          613
#define SSWRP_CPM_CPM_APC_GPIO_INT_14_614                          614
#define SSWRP_CPM_CPM_APC_GPIO_INT_15_615                          615
#define SSWRP_CPM_CPM_APC_GPIO_INT_16_616                          616
#define SSWRP_CPM_CPM_APC_GPIO_INT_17_617                          617
#define SSWRP_CPM_CPM_APC_GPIO_INT_18_618                          618
#define SSWRP_CPM_CPM_APC_GPIO_INT_19_619                          619
#define SSWRP_CPM_CPM_APC_GPIO_INT_20_620                          620
#define SSWRP_CPM_CPM_APC_GPIO_INT_21_621                          621
#define SSWRP_CPM_CPM_APC_GPIO_INT_22_622                          622
#define SSWRP_CPM_CPM_APC_GPIO_INT_23_623                          623
#define SSWRP_CPM_CPM_APC_GPIO_INT_24_624                          624
#define SSWRP_CPM_CPM_APC_GPIO_INT_25_625                          625
#define SSWRP_CPM_CPM_APC_GPIO_INT_26_626                          626
#define SSWRP_CPM_CPM_APC_GPIO_INT_27_627                          627
#define SSWRP_CPM_CPM_APC_GPIO_INT_28_628                          628
#define SSWRP_CPM_CPM_APC_GPIO_INT_29_629                          629
#define SSWRP_CPM_CPM_APC_GPIO_INT_30_630                          630
#define SSWRP_CPM_CPM_APC_GPIO_INT_31_631                          631
#define SSWRP_CPM_CPM_APC_GPIO_INT_32_632                          632
#define SSWRP_CPM_CPM_APC_GPIO_INT_33_633                          633
#define SSWRP_CPM_CPM_APC_GPIO_INT_34_634                          634
#define SSWRP_CPM_CPM_APC_GPIO_INT_35_635                          635
#define SSWRP_CPM_CPM_APC_GPIO_INT_36_636                          636
#define SSWRP_CPM_CPM_APC_GPIO_INT_37_637                          637
#define SSWRP_CPM_CPM_APC_GPIO_INT_38_638                          638
#define SSWRP_CPM_CPM_APC_GPIO_INT_39_639                          639
#define SSWRP_CPM_CPM_APC_GPIO_INT_40_640                          640
#define SSWRP_CPM_CPM_APC_GPIO_INT_41_641                          641
#define SSWRP_CPM_CPM_APC_GPIO_INT_42_642                          642
#define SSWRP_CPM_CPM_APC_GPIO_INT_43_643                          643
#define SSWRP_CPM_CPM_APC_GPIO_INT_44_644                          644
#define SSWRP_CPM_CPM_APC_GPIO_INT_45_645                          645
#define SSWRP_CPM_CPM_APC_GPIO_INT_46_646                          646
#define SSWRP_CPM_CPM_APC_GPIO_INT_47_647                          647
#define SSWRP_CPM_CPM_APC_GPIO_INT_48_648                          648
#define SSWRP_CPM_CPM_APC_GPIO_INT_49_649                          649
#define SSWRP_CPM_CPM_APC_GPIO_INT_50_650                          650
#define SSWRP_CPM_CPM_APC_GPIO_INT_51_651                          651
#define SSWRP_CPM_CPM_APC_GPIO_INT_52_652                          652
#define SSWRP_CPM_CPM_APC_GPIO_INT_53_653                          653
#define SSWRP_CPM_CPM_APC_GPIO_INT_54_654                          654
#define SSWRP_CPM_CPM_APC_GPIO_INT_55_655                          655
#define SSWRP_CPM_CPM_APC_GPIO_INT_56_656                          656
#define SSWRP_CPM_CPM_APC_GPIO_INT_57_657                          657
#define SSWRP_CPM_CPM_APC_GPIO_INT_58_658                          658
#define SSWRP_CPM_CPM_APC_GPIO_INT_59_659                          659
#define SSWRP_CPM_CPM_APC_GPIO_INT_60_660                          660
#define SSWRP_CPM_CPM_APC_GPIO_INT_61_661                          661
#define SSWRP_CPM_CPM_APC_GPIO_INT_62_662                          662
#define SSWRP_HSIO_N_HSION_AP_S_INTR_0                             663
#define SSWRP_HSIO_N_HSION_AP_S_INTR_1                             664
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_5_INTR_AP_NS             668
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_6_INTR_AP_NS             669
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_7_INTR_AP_NS             670
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_8_INTR_AP_S              671
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_9_INTR_AP_S              672
#define SSWRP_HSIO_S_HSIOS_MULTICAST_AGGR_10_INTR_AP_S             673
#define SSWRP_LSION_LSION_AP_GPIOA_INTR                            680
#define SSWRP_LSION_LSION_AP_GPIOB_INTR                            681
#define SSWRP_LSION_LSION_AP_GPIOC_INTR                            682
#define SSWRP_LSION_LSION_AP_GPIOD_INTR                            683
#define SSWRP_LSION_LSION_AP_OTHER_INTR                            684
#define SSWRP_LSION_LSION_AP_SSWRP_NS_INTR                         685
#define SSWRP_LSION_LSION_AP_SSWRP_TZ_INTR                         686
#define SSWRP_LSION_LSION_AP_GPIOA_TZ_INTR                         687
#define SSWRP_LSION_LSION_CLI16_INTR                               688
#define SSWRP_LSION_LSION_AP_OTHER_TZ_INTR                         689
#define SSWRP_LSIOS_LSIOS_AP_GPIOA_INTR                            690
#define SSWRP_LSIOS_LSIOS_AP_GPIOB_INTR                            691
#define SSWRP_LSIOS_LSIOS_AP_GPIOC_INTR                            692
#define SSWRP_LSIOS_LSIOS_AP_GPIOD_INTR                            693
#define SSWRP_LSIOS_LSIOS_AP_OTHER_INTR                            694
#define SSWRP_LSIOS_LSIOS_AP_SSWRP_NS_INTR                         695
#define SSWRP_LSIOS_LSIOS_AP_SSWRP_TZ_INTR                         696
#define SSWRP_LSIOS_LSIOS_AP_GPIOA_TZ_INTR                         697
#define SSWRP_LSIOS_LSIOS_AP_OTHER_TZ_INTR                         698
#define SSWRP_LSIOE_LSIOE_AP_GPIOA_INTR                            700
#define SSWRP_LSIOE_LSIOE_AP_GPIOB_INTR                            701
#define SSWRP_LSIOE_LSIOE_AP_GPIOC_INTR                            702
#define SSWRP_LSIOE_LSIOE_AP_GPIOD_INTR                            703
#define SSWRP_LSIOE_LSIOE_AP_OTHER_INTR                            704
#define SSWRP_LSIOE_LSIOE_AP_SSWRP_NS_INTR                         705
#define SSWRP_LSIOE_LSIOE_AP_SSWRP_TZ_INTR                         706
#define SSWRP_LSIOE_LSIOE_AP_GPIOA_TZ_INTR                         707
#define SSWRP_LSIOE_LSIOE_AP_OTHER_TZ_INTR                         708
#define SSWRP_GPDMA_GPDMA_AP_DMA0_INTR                             720
#define SSWRP_GPDMA_GPDMA_AP_DMA1_INTR                             721
#define SSWRP_GPDMA_GPDMA_AP_DMA2_INTR                             722
#define SSWRP_GPDMA_GPDMA_AP_DMA3_INTR                             723
#define SSWRP_GPDMA_GPDMA_AP_SSWRP_NS_INTR                         724
#define SSWRP_GPDMA_GPDMA_AP_SSWRP_TZ_INTR                         726
#define SSWRP_GPDMA_GPDMA_AP_DMA3_TZ_INTR                          727
#define SSWRP_GPDMA_GPDMA_AP_DMA2_TZ_INTR                          728
#define SSWRP_GPDMA_GPDMA_AP_DMA1_TZ_INTR                          729
#define SSWRP_GPDMA_GPDMA_AP_DMA0_TZ_INTR                          730
#define SSWRP_BMSM_BMSM_SDM_S_DEBUG_STATE_IRQ                      740
#define SSWRP_BMSM_BMSM_SDM_NS_DEBUG_STATE_IRQ                     741
#define SSWRP_BMSM_BMSM_GROOT_RFW_NS_IRQ                           742
#define SSWRP_BMSM_BMSM_GROOT_RFW_S_IRQ                            743
#define SSWRP_BMSM_BMSM_GROOT_MBA_CLIENT_CPUIRQ                    744
#define SSWRP_BMSM_BMSM_OTP_AP_NS_IRQ                              745
#define SSWRP_BMSM_BMSM_OTP_AP_S_IRQ                               746
#define SSWRP_GPCA_GPCA_AP_NS_IRQ                                  768
#define SSWRP_GPCA_GPCA_AP_S_IRQ                                   769
#define SSWRP_GPCA_GPCA_PD0_IRQ                                    770
#define SSWRP_GPCA_GPCA_PD1_IRQ                                    771
#define SSWRP_GPCA_GPCA_PD2_IRQ                                    772
#define SSWRP_GPCA_GPCA_PD3_IRQ                                    773
#define SSWRP_GPCM_RFW_NS_IRQ                                      782
#define SSWRP_GPCM_RFW_TZ_IRQ                                      783
#define SSWRP_GPCM_PLL_BKP_LOCK_HANG_IRQ                           790
#define SSWRP_DPU_DPU_APNS_IRQ                                     820
#define SSWRP_DPU_DPU_TZ_IRQ                                       821
#define SSWRP_AURORA_AURORA_AP_MCU_FS_NS_1_MBA_IRQ_0_103           823
#define SSWRP_AURORA_AURORA_AP_MCU_FS_NS_1_MBA_IRQ_1_104           824
#define SSWRP_AURORA_AURORA_AP_MCU_FS_NS_1_MBA_IRQ_2_105           825
#define SSWRP_AURORA_AURORA_AP_MCU_FS_NS_1_MBA_IRQ_3_106           826
#define SSWRP_AURORA_AURORA_AP_AGGR_NS_IRQ                         830
#define SSWRP_AURORA_AURORA_AP_AGGR_TZ_IRQ                         831
#define SSWRP_AURORA_AURORA_AP_CORE_0_MBA_IRQ_0_112                832
#define SSWRP_AURORA_AURORA_AP_CORE_0_MBA_IRQ_1_113                833
#define SSWRP_AURORA_AURORA_AP_CORE_1_MBA_IRQ_0_114                834
#define SSWRP_AURORA_AURORA_AP_CORE_1_MBA_IRQ_1_115                835
#define SSWRP_AURORA_AURORA_AP_CORE_2_MBA_IRQ_0_116                836
#define SSWRP_AURORA_AURORA_AP_CORE_2_MBA_IRQ_1_117                837
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_0_118                 838
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_1_119                 839
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_2_120                 840
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_3_121                 841
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_4_122                 842
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_5_123                 843
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_6_124                 844
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_7_125                 845
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_8_126                 846
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_9_127                 847
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_10_128                848
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_11_129                849
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_12_130                850
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_13_131                851
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_14_132                852
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_15_133                853
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_16_134                854
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_17_135                855
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_18_136                856
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_19_137                857
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_20_138                858
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_21_139                859
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_22_140                860
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_23_141                861
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_24_142                862
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_25_143                863
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_26_144                864
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_27_145                865
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_28_146                866
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_29_147                867
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_30_148                868
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_31_149                869
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_32_150                870
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_33_151                871
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_34_152                872
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_35_153                873
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_36_154                874
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_37_155                875
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_38_156                876
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_39_157                877
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_40_158                878
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_41_159                879
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_42_160                880
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_43_161                881
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_44_162                882
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_45_163                883
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_46_164                884
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_47_165                885
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_48_166                886
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_49_167                887
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_50_168                888
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_51_169                889
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_52_170                890
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_53_171                891
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_54_172                892
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_55_173                893
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_56_174                894
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_57_175                895
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_58_176                896
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_59_177                897
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_60_178                898
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_61_179                899
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_62_180                900
#define SSWRP_AURORA_AURORA_AP_MCU_0_MBA_IRQ_63_181                901
#define SSWRP_AURORA_AURORA_AP_MCU_1_MBA_IRQ_0_182                 902
#define SSWRP_AURORA_AURORA_AP_MCU_1_MBA_IRQ_1_183                 903
#define SSWRP_AURORA_AURORA_AP_MCU_1_MBA_IRQ_2_184                 904
#define SSWRP_AURORA_AURORA_AP_MCU_1_MBA_IRQ_3_185                 905
#define SSWRP_AURORA_AURORA_AP_WDOG_BITE_IRQ                       906
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_0_188                 908
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_1_189                 909
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_2_190                 910
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_3_191                 911
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_4_192                 912
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_5_193                 913
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_6_194                 914
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_7_195                 915
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_8_196                 916
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_9_197                 917
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_10_198                918
#define SSWRP_AURORA_AURORA_IDMA_TRIGOUT_IRQ_11_199                919
#define SSWRP_FABHBW_FABHBW_NS_IRQ                                 921
#define SSWRP_FABHBW_FABHBW_S_IRQ                                  922
#define SSWRP_AURORA_AURORA_AP_MCU_FS_TZ_1_MBA_IRQ_0_203           923
#define SSWRP_AURORA_AURORA_AP_MCU_FS_TZ_1_MBA_IRQ_1_204           924
#define SSWRP_AURORA_AURORA_AP_MCU_FS_TZ_1_MBA_IRQ_2_205           925
#define SSWRP_AURORA_AURORA_AP_MCU_FS_TZ_1_MBA_IRQ_3_206           926
#define SSWRP_FABMED_FABMED_NS_IRQ                                 931
#define SSWRP_FABMED_FABMED_S_IRQ                                  932
#define SSWRP_FABRT_FABRT_NS_IRQ                                   934
#define SSWRP_FABRT_FABRT_S_IRQ                                    935
#define SSWRP_FABSTBY_FABSTBY_NS_IRQ                               937
#define SSWRP_FABSTBY_FABSTBY_S_IRQ                                938
#define SSWRP_FABSYSS_FABSYSS_NS_IRQ                               940
#define SSWRP_FABSYSS_FABSYSS_S_IRQ                                941
#define SSWRP_ISPBE_IRQ_NS_AP                                      943
#define SSWRP_ISPBE_IRQ_TZ_AP                                      944
#define SSWRP_GSA_AP_0_CLIENT_MBA_IRQ                              950
#define SSWRP_GSA_AP_1_CLIENT_MBA_IRQ                              951
#define SSWRP_GSA_AP_2_CLIENT_MBA_IRQ                              952
#define SSWRP_GSA_AP_3_CLIENT_MBA_IRQ                              953
#define SSWRP_GSA_GSA_AP_NS_IRQ                                    954
#define SSWRP_GSA_GSA_AP_S_IRQ                                     955
#define SSWRP_GSA_SPARE_IRQ                                        956

#endif  /* _DT_BINDINGS_INTERRUPT_CONTROLLER_LGA_H */
