/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_BINDINGS_POWER_GENPD_H
#define __DT_BINDINGS_POWER_GENPD_H

#define GENPD_LGA_SSWRP_AOC_ID 0
#define GENPD_LGA_SSWRP_AURORA_ID 1
#define GENPD_LGA_SSWRP_CODEC_3P_ID 2
#define GENPD_LGA_SSWRP_CPU_ID 3
#define GENPD_LGA_SSWRP_CPUACC_ID 4
#define GENPD_LGA_SSWRP_DPU_ID 5
#define GENPD_LGA_SSWRP_EH_ID 6
#define GENPD_LGA_SSWRP_FABHBW_ID 7
#define GENPD_LGA_SSWRP_FABMED_ID 8
#define GENPD_LGA_SSWRP_FABRT_ID 9
#define GENPD_LGA_SSWRP_FABSTBY_ID 10
#define GENPD_LGA_SSWRP_FABSYSS_ID 11
#define GENPD_LGA_SSWRP_G2D_ID 12
#define GENPD_LGA_SSWRP_GMC0_ID 13
#define GENPD_LGA_SSWRP_GMC1_ID 14
#define GENPD_LGA_SSWRP_GMC2_ID 15
#define GENPD_LGA_SSWRP_GMC3_ID 16
#define GENPD_LGA_SSWRP_GPCA_ID 17
#define GENPD_LGA_SSWRP_GPCM_ID 18
#define GENPD_LGA_SSWRP_GPDMA_ID 19
#define GENPD_LGA_SSWRP_GPU_ID 20
#define GENPD_LGA_SSWRP_GSA_ID 21
#define GENPD_LGA_SSWRP_GSW_ID 22
#define GENPD_LGA_SSWRP_HSIO_N_ID 23
#define GENPD_LGA_SSWRP_HSIO_S_ID 24
#define GENPD_LGA_SSWRP_INF_TCU_ID 25
#define GENPD_LGA_SSWRP_ISPBE_ID 26
#define GENPD_LGA_SSWRP_ISPFE_ID 27
#define GENPD_LGA_SSWRP_LSIO_E_ID 28
#define GENPD_LGA_SSWRP_LSIO_N_ID 29
#define GENPD_LGA_SSWRP_LSIO_S_ID 30
#define GENPD_LGA_SSWRP_MEMSS_ID 31
#define GENPD_LGA_SSWRP_TPU_ID 32
#define GENPD_LGA_LSIO_S_CLI_GPIO_IRQ_SAFE_ID 33
#define GENPD_LGA_LSIO_E_CLI_GPIO_IRQ_SAFE_ID 34
#define GENPD_LGA_LSIO_N_CLI_GPIO_IRQ_SAFE_ID 35
#define GENPD_LGA_SSWRP_COUNT 36

#define GENPD_LGA_GPU_CORE_LOGIC_ID 0
#define GENPD_LGA_GPU_SUBDOMAIN_COUNT 1

#define GENPD_LGA_HSIO_N_USB_ID 0
#define GENPD_LGA_HSIO_N_PCIE_ID 1
#define GENPD_LGA_HSIO_N_EBU_ID 2
#define GENPD_LGA_HSIO_N_EBU_CORE_ID 3
#define GENPD_LGA_HSIO_N_DP_ID 4
#define GENPD_LGA_HSIO_N_USB_PSW_ID 5
#define GENPD_LGA_HSIO_N_SUBDOMAIN_COUNT 6

#define GENPD_LGA_HSIO_S_UFS_ID 0
#define GENPD_LGA_HSIO_S_PCIE_ID 1
#define GENPD_LGA_HSIO_S_SD_ID 2
#define GENPD_HSIO_S_UFS_PREP_ID 3
#define GENPD_LGA_HSIO_S_SUBDOMAIN_COUNT 4

#define GENPD_LGA_LSIO_CLI_GPIO_ID 0
#define GENPD_LGA_LSIO_CLI_SUBDOMAIN_COUNT 1

#define GENPD_LGA_DPU_FE0_ID 0
#define GENPD_LGA_DPU_FE1_ID 1
#define GENPD_LGA_DPU_DSI0_ID 2
#define GENPD_LGA_DPU_DSI1_ID 3
#define GENPD_LGA_DPU_DP_ID 4
#define GENPD_LGA_DPU_SUBDOMAIN_COUNT 5

#define GENPD_LGA_ISPFE_TOP_ID 0
#define GENPD_LGA_ISPFE_PIPE_ID 1
#define GENPD_LGA_ISPFE_CSIS_ID 2
#define GENPD_LGA_ISPFE_SUBDOMAIN_COUNT 3

#define GENPD_LGA_ISPBE_TOP_ID 0
#define GENPD_LGA_ISPBE_SUBDOMAIN_COUNT 1

#define GENPD_LGA_GSW_MAIN_ID 0
#define GENPD_LGA_GSW_SUBDOMAIN_COUNT 1

#define GENPD_LGA_G2D_CORE_ID 0
#define GENPD_LGA_G2D_SUBDOMAIN_COUNT

#define GENPD_LGA_C3P_CORE_ID 0
#define GENPD_LGA_C3P_SUBDOMAIN_COUNT 1

#define GENPD_LGA_GPDMA_ID 0
#define GENPD_LGA_GPDMA_SUBDOMAIN_COUNT 1

#define GENPD_LGA_INF_TCU_ID 0
#define GENPD_LGA_INF_SUBDOMAIN_COUNT 1

#define GENPD_LGA_AOC_CORE_ID 0
#define GENPD_LGA_AOC_SUBDOMAIN_COUNT 1

#endif /* __DT_BINDINGS_POWER_GENPD_H */
