/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2024 Google LLC
 */
#ifndef _MAILBOX_GOOGLE_PROTOCOLS_MBA_CPM_COMMON_BCL_SERVICE_H
#define _MAILBOX_GOOGLE_PROTOCOLS_MBA_CPM_COMMON_BCL_SERVICE_H

/* Contains all definitions needed to use the BCL mailbox service */

/* SERVICE_ID: CPM_COMMON_BCL_SERVICE
 *
 * Word 0: Queue mode header
 * Word 1: Command, check enum for supported cmds
 *  bit [ 31 - 28 | 27 - 24 | 23 - 16 | 15 - 0 ]
 *      | Command | ZONE    | CONFIG  | VALUE ]
 * Word 2: Data 1
 *  bit [ 31 - 0 ]
 *      | Data 1 |
 *
 * Response msg:
 * Word 0: Queue mode header
 * Word 1: Status: Defined in enum bcl_mb_rsp_status
 *  bit [ 31 - 24 | 23 - 0 ]
 *      | Status  | unused |
 * Word 2: Data 1
 *  bit [ 31 - 0 ]
 *      | Data 1 |
 *
 * SERVICE_ID: CPM_COMMON_BCL_SERVICE
 */

/* Supported BCL mailbox COMMANDS */
enum bcl_mb_commands {
	MB_BCL_CMD_INIT,
	MB_BCL_CMD_GET_CONFIG,
	MB_BCL_CMD_SET_CONFIG,
	MB_BCL_CMD_GET_COUNT,
	MB_BCL_CMD_GET_CLK_RATIO,
	MB_BCL_CMD_GET_SYS_EVT,
	MB_BCL_CMD_GET_SCRATCH,
	MB_BCL_CMD_SET_SCRATCH,
	MB_BCL_CMD_GET_PRE_EVT_COUNT,
	MB_BCL_CMD_GET_MAIN_PWRWARN_COUNT,
	MB_BCL_CMD_GET_SUB_PWRWARN_COUNT,
	MB_BCL_CMD_GET_CACHED_SYS_EVT,
};

/* Supported BCL Config parameter */
enum bcl_mb_parameter {
	MB_ZONE_CONFIG_DEBOUNCE = 1,
	MB_ZONE_CONFIG_RXDATA_TRIGGER,
	MB_ZONE_CONFIG_RXGATE_FUNC,
	MB_ZONE_CONFIG_IER,
	MB_ZONE_CONFIG_IMR,
	MB_ZONE_CONFIG_ITR,
	MB_ZONE_CONFIG_ISR,
	MB_ZONE_CONFIG_MITIGATION_RESPONSE_EN,
	MB_ZONE_CONFIG_MITIGATION_RESPONSE_TYPE,
	MB_ZONE_CONFIG_MITIGATION_RESPONSE_HYST,
	MB_ZONE_CONFIG_DIV_2_CTRL_MODE,
	MB_ZONE_CONFIG_DIV_2_DIV_RATIO,
	MB_ZONE_CONFIG_DIV_2_DIV_STATUS,
	MB_ZONE_CONFIG_DIV_4_CTRL_MODE,
	MB_ZONE_CONFIG_DIV_4_DIV_RATIO,
	MB_ZONE_CONFIG_DIV_4_DIV_STATUS,
	MB_BCL_CONFIG_IFPMIC,
	MB_BCL_CONFIG_OCP_BATFET_TIMEOUT,
	MB_BCL_CONFIG_OCP_BATFET_TIMEOUT_ENABLE,
	MB_BCL_CONFIG_OCP_BATFET_TIMER_CANCEL,
	MB_BCL_CONFIG_OCP_BATFET_TIMER_SET,
};

/* Operation status used in response */
enum bcl_mb_rsp_status {
	MB_BCL_RSP_STS_OK,
	MB_BCL_RSP_STS_INVALID_CMD,
	MB_BCL_RSP_STS_INVALID_CONFIG,
	MB_BCL_RSP_STS_INVALID_VALUE,
	MB_BCL_RSP_STS_NOT_PERMITTED,
	MB_BCL_RSP_STS_OP_TIMEOUT_OR_FAIL,
};

#define MB_QUEUE_BCL_CMD_WORD_OFFSET 1
#define MB_QUEUE_BCL_CMD_MASK GENMASK(31, 28)

#define MB_QUEUE_BCL_CMD_ZONE_WORD_OFFSET 1
#define MB_QUEUE_BCL_CMD_ZONE_MASK GENMASK(27, 24)

#define MB_QUEUE_BCL_CMD_CONFIG_WORD_OFFSET 1
#define MB_QUEUE_BCL_CMD_CONFIG_MASK GENMASK(23, 16)

#define MB_QUEUE_BCL_CMD_VALUE_WORD_OFFSET 1
#define MB_QUEUE_BCL_CMD_VALUE_MASK GENMASK(15, 0)

#define MB_QUEUE_BCL_CMD_DATA1_WORD_OFFSET 2
#define MB_QUEUE_BCL_CMD_DATA1_MASK GENMASK(31, 0)

#define MB_QUEUE_BCL_RSP_STATUS_WORD_OFFSET 1
#define MB_QUEUE_BCL_RSP_STATUS_MASK GENMASK(31, 24)

#define MB_QUEUE_BCL_RSP_DATA1_WORD_OFFSET 2
#define MB_QUEUE_BCL_RSP_DATA1_MASK GENMASK(31, 0)

#endif
