/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2023 Google LLC
 */
#ifndef _MAILBOX_GOOGLE_PROTOCOLS_MBA_CPM_COMMON_PMIC_PMIC_SERVICE_H
#define _MAILBOX_GOOGLE_PROTOCOLS_MBA_CPM_COMMON_PMIC_PMIC_SERVICE_H

// Contains all definitions needed to use the PMIC mailbox service

/* SERVICE_ID: CPM_COMMON_PMIC_SERVICE
 *
 * Entire service is enabled for production.
 * Handles the following Target IDs for different PMIC capabilities:
 * 0) PMIC Register Access: go/rdo-pmic-mailbox#heading=h.l6p43g8u3yc3
 * Provide the ability to read / write the PMIC register at a given address.
 * This should be a debug only feature and disabled in production.
 * 1) PMIC Regulator driver: go/rdo-pmic-regulator-driver
 * Let Linux drivers to monitor or control the PMIC regulator.
 * E.g. The camera module's driver can turn ON/OFF its own power rail depends
 * on whether the camera is in use or not.
 *
 * Custom mailbox messages are defined in: go/rdo-pmic-mailbox
 * Only support "queue mode", as the operation is not as urgent.
 * Request msg:
 * Word 0: Queue mode header
 * Word 1: Command & Device ID / Addr, check enum for supported cmds
 *  bit [ 31 - 24 | 23 - 16 | 15 - 0           ]
 *      | Target  | Command | Device ID / Addr |
 * Word 2: Data 1
 *  bit [ 31 - 0 ]
 *      | Data 1 |
 * Word 3: Data 2
 *  bit [ 31 - 0 ]
 *      | Data 2 |
 *
 * Response msg:
 * Word 0: Queue mode header
 * Word 1: Status: Defined in enum pmic_mb_rsp_status
 *  bit [ 31 - 24 | 23 - 0 ]
 *      | Status  | unused |
 * Word 2: Data 1
 *  bit [ 31 - 0 ]
 *      | Data 1 |
 * Word 3: Data 2
 *  bit [ 31 - 0 ]
 *      | Data 2 |
 *
 * SERVICE_ID: CPM_COMMON_PMIC_SERVICE
 */

// Supported PMIC mailbox targets
enum pmic_mb_targets {
	MB_PMIC_TARGET_REGISTER = 0,
	MB_PMIC_TARGET_REGULATOR = 1,
	MB_PMIC_TARGET_RTC = 2,
	MB_PMIC_TARGET_GPIO = 3,
};

// Supported PMIC register access commands
enum pmic_mb_register_access_cmds {
	MB_REG_CMD_GET_PMIC_REG_BURST = 1,
	MB_REG_CMD_SET_PMIC_REG_SINGLE,
};

// Supported PMIC regulator control commands
enum pmic_mb_regulator_cmds {
	MB_REG_CMD_GET_IS_ENABLED = 1,
	MB_REG_CMD_SET_ENABLE_DISABLE,
	MB_REG_CMD_GET_VOLTAGE_SEL,
	MB_REG_CMD_SET_VOLTAGE_SEL,
	MB_REG_CMD_GET_MODE,
	MB_REG_CMD_SET_MODE,
	MB_REG_CMD_GET_BYPASS,
	MB_REG_CMD_SET_BYPASS,
	MB_REG_CMD_GET_VOLTAGE,
	MB_REG_CMD_SET_VOLTAGE,
};

// Supported PMIC RTC control commands
enum pmic_mb_rtc_cmds {
	MB_RTC_CMD_GET_NONCE_VALID = 1,
	MB_RTC_CMD_SET_NONCE_VALID,
	MB_RTC_CMD_GET_RTC_TIME,
	MB_RTC_CMD_SET_RTC_TIME,
	MB_RTC_CMD_SET_ALARM_ENABLE_DISABLE,
	MB_RTC_CMD_GET_ALARM,
	MB_RTC_CMD_SET_ALARM,
	MB_RTC_CMD_SET_RTC_SCRATCH,
};

// Supported PMIC GPIO control commands
enum pmic_mb_gpio_cmds {
	MB_GPIO_CMD_GET_DIRECTION = 1,
	MB_GPIO_CMD_SET_DIRECTION,
	MB_GPIO_CMD_GET_VALUE,
	MB_GPIO_CMD_SET_VALUE,
	MB_GPIO_CMD_GET_OUTPUT_DRIVE,
	MB_GPIO_CMD_SET_OUTPUT_DRIVE,
	MB_GPIO_CMD_GET_MODE,
	MB_GPIO_CMD_GET_DRIVE_STRENGTH,
	MB_GPIO_CMD_SET_DRIVE_STRENGTH,
	MB_GPIO_CMD_GET_PULL_CONFIG,
	MB_GPIO_CMD_SET_PULL_CONFIG,
};

// Operation status used in response
enum pmic_mb_rsp_status {
	MB_RSP_STS_OK = 0,
	MB_RSP_STS_INVALID_TARGET,
	MB_RSP_STS_INVALID_CMD,
	MB_RSP_STS_INVALID_ID,
	MB_RSP_STS_INVALID_VALUE,
	MB_RSP_STS_NOT_PERMITTED,
	MB_RSP_STS_OP_TIMEOUT_OR_FAIL,
};

enum pmic_mb_morro_regulator_id {
	/* 10 BUCKs in M */
	MB_PMIC_MORRO_REG_ID_BUCK_1M = 0,
	MB_PMIC_MORRO_REG_ID_BUCK_2M,
	MB_PMIC_MORRO_REG_ID_BUCK_3M,
	MB_PMIC_MORRO_REG_ID_BUCK_4M,
	MB_PMIC_MORRO_REG_ID_BUCK_5M,
	MB_PMIC_MORRO_REG_ID_BUCK_6M,
	MB_PMIC_MORRO_REG_ID_BUCK_7M,
	MB_PMIC_MORRO_REG_ID_BUCK_8M,
	MB_PMIC_MORRO_REG_ID_BUCK_9M,
	MB_PMIC_MORRO_REG_ID_BUCK_10M,
	/* 31 LDOs in M */
	MB_PMIC_MORRO_REG_ID_LDO_1M,
	MB_PMIC_MORRO_REG_ID_LDO_2M,
	MB_PMIC_MORRO_REG_ID_LDO_3M,
	MB_PMIC_MORRO_REG_ID_LDO_4M,
	MB_PMIC_MORRO_REG_ID_LDO_5M,
	MB_PMIC_MORRO_REG_ID_LDO_6M,
	MB_PMIC_MORRO_REG_ID_LDO_7M,
	MB_PMIC_MORRO_REG_ID_LDO_8M,
	MB_PMIC_MORRO_REG_ID_LDO_9M,
	MB_PMIC_MORRO_REG_ID_LDO_10M,
	MB_PMIC_MORRO_REG_ID_LDO_11M,
	MB_PMIC_MORRO_REG_ID_LDO_12M,
	MB_PMIC_MORRO_REG_ID_LDO_13M,
	MB_PMIC_MORRO_REG_ID_LDO_14M,
	MB_PMIC_MORRO_REG_ID_LDO_15M,
	MB_PMIC_MORRO_REG_ID_LDO_16M,
	MB_PMIC_MORRO_REG_ID_LDO_17M,
	MB_PMIC_MORRO_REG_ID_LDO_18M,
	MB_PMIC_MORRO_REG_ID_LDO_19M,
	MB_PMIC_MORRO_REG_ID_LDO_20M,
	MB_PMIC_MORRO_REG_ID_LDO_21M,
	MB_PMIC_MORRO_REG_ID_LDO_22M,
	MB_PMIC_MORRO_REG_ID_LDO_23M,
	MB_PMIC_MORRO_REG_ID_LDO_24M,
	MB_PMIC_MORRO_REG_ID_LDO_25M,
	MB_PMIC_MORRO_REG_ID_LDO_26M,
	MB_PMIC_MORRO_REG_ID_LDO_27M,
	MB_PMIC_MORRO_REG_ID_LDO_28M,
	MB_PMIC_MORRO_REG_ID_LDO_29M,
	MB_PMIC_MORRO_REG_ID_LDO_30M,
	MB_PMIC_MORRO_REG_ID_LDO_31M,
	/* 13 BUCKs in S */
	MB_PMIC_MORRO_REG_ID_BUCK_1S,
	MB_PMIC_MORRO_REG_ID_BUCK_2S,
	MB_PMIC_MORRO_REG_ID_BUCK_3S,
	MB_PMIC_MORRO_REG_ID_BUCK_4S,
	MB_PMIC_MORRO_REG_ID_BUCK_5S,
	MB_PMIC_MORRO_REG_ID_BUCK_6S,
	MB_PMIC_MORRO_REG_ID_BUCK_7S,
	MB_PMIC_MORRO_REG_ID_BUCK_8S,
	MB_PMIC_MORRO_REG_ID_BUCK_9S,
	MB_PMIC_MORRO_REG_ID_BUCK_10S,
	MB_PMIC_MORRO_REG_ID_BUCK_11S,
	MB_PMIC_MORRO_REG_ID_BUCK_12S,
	MB_PMIC_MORRO_REG_ID_BUCK_13S,
	/* 1 BUCK-BOOST in S */
	MB_PMIC_MORRO_REG_ID_BUCK_BOOST,
	/* 28 LDOs in S */
	MB_PMIC_MORRO_REG_ID_LDO_1S,
	MB_PMIC_MORRO_REG_ID_LDO_2S,
	MB_PMIC_MORRO_REG_ID_LDO_3S,
	MB_PMIC_MORRO_REG_ID_LDO_4S,
	MB_PMIC_MORRO_REG_ID_LDO_5S,
	MB_PMIC_MORRO_REG_ID_LDO_6S,
	MB_PMIC_MORRO_REG_ID_LDO_7S,
	MB_PMIC_MORRO_REG_ID_LDO_8S,
	MB_PMIC_MORRO_REG_ID_LDO_9S,
	MB_PMIC_MORRO_REG_ID_LDO_10S,
	MB_PMIC_MORRO_REG_ID_LDO_11S,
	MB_PMIC_MORRO_REG_ID_LDO_12S,
	MB_PMIC_MORRO_REG_ID_LDO_13S,
	MB_PMIC_MORRO_REG_ID_LDO_14S,
	MB_PMIC_MORRO_REG_ID_LDO_15S,
	MB_PMIC_MORRO_REG_ID_LDO_16S,
	MB_PMIC_MORRO_REG_ID_LDO_17S,
	MB_PMIC_MORRO_REG_ID_LDO_18S,
	MB_PMIC_MORRO_REG_ID_LDO_19S,
	MB_PMIC_MORRO_REG_ID_LDO_20S,
	MB_PMIC_MORRO_REG_ID_LDO_21S,
	MB_PMIC_MORRO_REG_ID_LDO_22S,
	MB_PMIC_MORRO_REG_ID_LDO_23S,
	MB_PMIC_MORRO_REG_ID_LDO_24S,
	MB_PMIC_MORRO_REG_ID_LDO_25S,
	MB_PMIC_MORRO_REG_ID_LDO_26S,
	MB_PMIC_MORRO_REG_ID_LDO_27S,
	MB_PMIC_MORRO_REG_ID_LDO_28S,
	MB_PMIC_MORRO_REG_ID_MAX,
};

#define MB_QUEUE_PMIC_REQ_TARGET_WORD_OFFSET 1
#define MB_QUEUE_PMIC_REQ_TARGET_MASK GENMASK(31, 24)
#define MB_POLL_PMIC_REQ_TARGET_WORD_OFFSET MB_QUEUE_PMIC_REQ_TARGET_WORD_OFFSET
#define MB_POLL_PMIC_REQ_TARGET_MASK MB_QUEUE_PMIC_REQ_TARGET_MASK

#define MB_QUEUE_PMIC_REQ_COMMAND_WORD_OFFSET 1
#define MB_QUEUE_PMIC_REQ_COMMAND_MASK GENMASK(23, 16)
#define MB_POLL_PMIC_REQ_COMMAND_WORD_OFFSET \
	MB_QUEUE_PMIC_REQ_COMMAND_WORD_OFFSET
#define MB_POLL_PMIC_REQ_COMMAND_MASK MB_QUEUE_PMIC_REQ_COMMAND_MASK

#define MB_QUEUE_PMIC_REQ_ADDR_WORD_OFFSET 1
#define MB_QUEUE_PMIC_REQ_ADDR_MASK GENMASK(15, 0)
#define MB_POLL_PMIC_REQ_ADDR_WORD_OFFSET MB_QUEUE_PMIC_REQ_ADDR_WORD_OFFSET
#define MB_POLL_PMIC_REQ_ADDR_MASK MB_QUEUE_PMIC_REQ_ADDR_MASK

#define MB_QUEUE_PMIC_REQ_DATA1_WORD_OFFSET 2
#define MB_QUEUE_PMIC_REQ_DATA1_MASK GENMASK(31, 0)
#define MB_POLL_PMIC_REQ_DATA1_WORD_OFFSET MB_QUEUE_PMIC_REQ_DATA1_WORD_OFFSET
#define MB_POLL_PMIC_REQ_DATA1_MASK MB_QUEUE_PMIC_REQ_DATA1_MASK

#define MB_QUEUE_PMIC_REQ_DATA2_WORD_OFFSET 3
#define MB_QUEUE_PMIC_REQ_DATA2_MASK GENMASK(31, 0)
#define MB_POLL_PMIC_REQ_DATA2_WORD_OFFSET MB_QUEUE_PMIC_REQ_DATA2_WORD_OFFSET
#define MB_POLL_PMIC_REQ_DATA2_MASK MB_QUEUE_PMIC_REQ_DATA2_MASK

#define MB_QUEUE_PMIC_RSP_STATUS_WORD_OFFSET 1
#define MB_QUEUE_PMIC_RSP_STATUS_MASK GENMASK(31, 24)
#define MB_POLL_PMIC_RSP_STATUS_WORD_OFFSET MB_QUEUE_PMIC_RSP_STATUS_WORD_OFFSET
#define MB_POLL_PMIC_RSP_STATUS_MASK MB_QUEUE_PMIC_RSP_STATUS_MASK

#define MB_QUEUE_PMIC_RSP_DATA1_WORD_OFFSET 2
#define MB_QUEUE_PMIC_RSP_DATA1_MASK GENMASK(31, 0)
#define MB_POLL_PMIC_RSP_DATA1_WORD_OFFSET MB_QUEUE_PMIC_RSP_DATA1_WORD_OFFSET
#define MB_POLL_PMIC_RSP_DATA1_MASK MB_QUEUE_PMIC_RSP_DATA1_MASK

#define MB_QUEUE_PMIC_RSP_DATA2_WORD_OFFSET 3
#define MB_QUEUE_PMIC_RSP_DATA2_MASK GENMASK(31, 0)
#define MB_POLL_PMIC_RSP_DATA2_WORD_OFFSET MB_QUEUE_PMIC_RSP_DATA2_WORD_OFFSET
#define MB_POLL_PMIC_RSP_DATA2_MASK MB_QUEUE_PMIC_RSP_DATA2_MASK

// 8 bytes ANSI of: "IS-VALID"
#define PMIC_NONCE_MAGIC_VAL (0x49532d56414c4944ULL)

#endif
