// SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause
/*
 * Copyright (c) 2024 Google LLC
 */

#include <dts-define.h>
#include <../mailbox/protocols/mba/cpm/common/service_ids.h>
void mbox_define(void)
{
	/* name, channel, service_id, mba-dest-channel */
	MBOX_DEFINE2(CPM_CI_TEST1, 0, 0);
	MBOX_DEFINE3(CPMLOG, 1, 1, CPM_AP_COMMON_LOG_SERVICE);
	MBOX_DEFINE3(CPM_TRACEPOINT, 2, 2, CPM_AP_COMMON_TRACEPOINT_SERVICE);
	MBOX_DEFINE3(GMC, 3, 3, CPM_AP_COMMON_GMC_MB_SERVICE);
	MBOX_DEFINE3(GSLC, 4, 4, CPM_AP_COMMON_GSLC_MB_SERVICE);
	MBOX_DEFINE2(CPM_DEMO, 5, 0x36);
	/* why not CPM_COMMON_POWER_STATE_SERVICE */
	MBOX_DEFINE3(PF_STATE_CPM, 6, 6, CPM_COMMON_LPCM_SERVICE);
	MBOX_DEFINE2(POWER_CONTROLLER, 7, 7);
	/* IRM ? IPM ? */
	MBOX_DEFINE3(IRM, 8, 8, CPM_COMMON_MIPM_SERVICE);
	/* CPM_COMMON_COMMAND_LINE_SERVICE only define in cpm */
	MBOX_DEFINE3(CPM_CLI, 9, 9, 0xF);
	MBOX_DEFINE3(DA9188_REGULATOR, 10, 10, CPM_COMMON_PMIC_SERVICE);
	MBOX_DEFINE3(DA9188_RTC, 11, 11, CPM_COMMON_PMIC_SERVICE);
	MBOX_DEFINE2(CPM_CLK, 12, 12);
	MBOX_DEFINE2(CPM_CI_TEST2, 13, 13);
	MBOX_DEFINE2(CPM_CI_TEST3, 14, 14);
	MBOX_DEFINE2(CPM_RST, 15, 15);
	/* no enum variable */
	MBOX_DEFINE3(POWERDASHBOARD, 16, 0x68, 0x68);
	/* no enum variable */
	MBOX_DEFINE3(ODPM, 17, 0x69, 0x69);
	MBOX_DEFINE3(THERMAL, 18, 0x6F, CPM_COMMON_THERMAL_SERVICE);
	MBOX_DEFINE3(DA9188_GPIO, 19, 19, CPM_COMMON_PMIC_SERVICE);
	MBOX_DEFINE3(DA9188_VGPIO, 20, 20, CPM_COMMON_PMIC_SERVICE);
	MBOX_DEFINE3(SSRAM_REQUEST, 102, 0x66, CPM_AP_NS_SSRAM_SERVICE);
}
