/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Copyright (c) 2024 Google LLC
 */

#ifndef __DT_BINDINGS_MAILBOX_GOOGLE_LGA_H
#define __DT_BINDINGS_MAILBOX_GOOGLE_LGA_H

/* sort by moxes then service-id	mboxes	service-id	mba-dest-channel */
#define MBOX_CHAN_CPM_CI_TEST1		0
#define MBOX_SERVICE_ID_CPM_CI_TEST1		0

#define MBOX_CHAN_CPMLOG		1
#define MBOX_SERVICE_ID_CPMLOG			1
#define MBOX_DEST_CHAN_CPMLOG					1

#define MBOX_CHAN_CPM_TRACEPOINT	2
#define MBOX_SERVICE_ID_CPM_TRACEPOINT		2
#define MBOX_DEST_CHAN_CPM_TRACEPOINT				2

#define MBOX_CHAN_GMC			3
#define MBOX_SERVICE_ID_GMC			3
#define MBOX_DEST_CHAN_GMC					4

#define MBOX_CHAN_GSLC			4
#define MBOX_SERVICE_ID_GSLC			4
#define MBOX_DEST_CHAN_GSLC					3

#define MBOX_CHAN_CPM_DEMO		5
#define MBOX_SERVICE_ID_CPM_DEMO		0x36

#define MBOX_CHAN_PF_STATE_CPM		6
#define MBOX_SERVICE_ID_PF_STATE_CPM		6
#define MBOX_DEST_CHAN_PF_STATE_CPM				8

#define MBOX_CHAN_POWER_CONTROLLER	7
#define MBOX_SERVICE_ID_POWER_CONTROLLER	7

#define MBOX_CHAN_IRM			8
#define MBOX_SERVICE_ID_IRM			8
#define MBOX_DEST_CHAN_IRM					11

#define MBOX_CHAN_CPM_CLI		9
#define MBOX_SERVICE_ID_CPM_CLI			9
#define MBOX_DEST_CHAN_CPM_CLI					15

#define MBOX_CHAN_DA9188_REGULATOR	10
#define MBOX_SERVICE_ID_DA9188_REGULATOR	10
#define MBOX_DEST_CHAN_DA9188_REGULATOR				10

#define MBOX_CHAN_DA9188_RTC		11
#define MBOX_SERVICE_ID_DA9188_RTC		11
#define MBOX_DEST_CHAN_DA9188_RTC				10

#define MBOX_CHAN_CPM_CLK		12
#define MBOX_SERVICE_ID_CPM_CLK			12

#define MBOX_CHAN_CPM_CI_TEST2		13
#define MBOX_SERVICE_ID_CPM_CI_TEST2		13

#define MBOX_CHAN_CPM_CI_TEST3		14
#define MBOX_SERVICE_ID_CPM_CI_TEST3		14

#define MBOX_CHAN_CPM_RST		15
#define MBOX_SERVICE_ID_CPM_RST			15

#define MBOX_CHAN_POWERDASHBOARD	16
#define MBOX_SERVICE_ID_POWERDASHBOARD		0x68
#define MBOX_DEST_CHAN_POWERDASHBOARD				104

#define MBOX_CHAN_ODPM			17
#define MBOX_SERVICE_ID_ODPM			0x69
#define MBOX_DEST_CHAN_ODPM					105

#define MBOX_CHAN_THERMAL		18
#define MBOX_SERVICE_ID_THERMAL			0x6F
#define MBOX_DEST_CHAN_THERMAL					12

#define MBOX_CHAN_DA9188_GPIO		19
#define MBOX_SERVICE_ID_DA9188_GPIO		19
#define MBOX_DEST_CHAN_DA9188_GPIO				10

#define MBOX_CHAN_DA9188_VGPIO		20
#define MBOX_SERVICE_ID_DA9188_VGPIO		20
#define MBOX_DEST_CHAN_DA9188_VGPIO				10

#define MBOX_CHAN_SSRAM_REQUEST		21
#define MBOX_SERVICE_ID_SSRAM_REQUEST		0x66
#define MBOX_DEST_CHAN_SSRAM_REQUEST				102

#define MBOX_CHAN_GMC_FREQ		22
#define MBOX_SERVICE_ID_GMC_FREQ		22

#define MBOX_CHAN_MEMSS_FREQ		23
#define MBOX_SERVICE_ID_MEMSS_FREQ		23

#define MBOX_CHAN_FABRT_FREQ		24
#define MBOX_SERVICE_ID_FABRT_FREQ		24

#define MBOX_CHAN_FABHBW_FREQ		25
#define MBOX_SERVICE_ID_FABHBW_FREQ		25

#define MBOX_CHAN_FABMED_FREQ		26
#define MBOX_SERVICE_ID_FABMED_FREQ		26

#define MBOX_CHAN_FABSTBY_FREQ		27
#define MBOX_SERVICE_ID_FABSTBY_FREQ		27

#define MBOX_CHAN_FABSYSS_FREQ		28
#define MBOX_SERVICE_ID_FABSYSS_FREQ		28

#define MBOX_CHAN_CPM_IRQ		29
#define MBOX_SERVICE_ID_CPM_IRQ			0x6e
#define MBOX_DEST_CHAN_CPM_IRQ					110

#define MBOX_CHAN_BCL_DA9188_REGULATOR  30
#define MBOX_SERVICE_ID_BCL_DA9188_REGULATOR	30
#define MBOX_DEST_CHAN_BCL_DA9188_REGULATOR		10

#define MBOX_CHAN_BCL			31
#define MBOX_SERVICE_ID_BCL			0x12
#define MBOX_DEST_CHAN_BCL				0x12

#define MBOX_CHAN_THERMAL_V2		32
#define MBOX_SERVICE_ID_THERMAL_V2		0x6d
#define MBOX_DEST_CHAN_THERMAL_V2			0x15

#define MBOX_SERVICE_ID_CPM_FWTP		0x17
#define MBOX_DEST_CHAN_CPM_FWTP					0x17

#endif /* __DT_BINDINGS_MAILBOX_GOOGLE_LGA_H */
